### ISSUE TITLE
Debug fails with [cordova-debug-adapter] Error: Unable to find device

### ISSUE THREAD

**Issue by porjo** [Microsoft/vscode-cordova#100]
Attempting to do `Run Android on device` results in this message in console:
```
Launching for android (This may take a while)...
App successfully launched
Attaching to android
Unable to find device
```
However the 'HelloCordova' app is successfully running on my device! (and was launched by the above action)

I'm using VSCode on Fedora Linux 23. I have Android Studio installed on the same system and it works with my device just fine.

**Comment by MSLaguana** [comment]
What is the exact output of `adb devices`, and please include the line where you input the command. That error message indicates that we tried to find a target listed as a `device`, but we were unsuccessful. We have not tested extensively on linux, and if there is a change in the output format that may cause us issues.

**Comment by porjo** [comment]
```
$ adb devices
List of devices attached
0123456789ABCDEF	device
```

**Comment by MSLaguana** [comment]
To be sure, if you try to launch on android via VS Code again it still gives you the original error that you posted? It looks like it should work from what you show there.

**Comment by porjo** [comment]
I've tried again from a freshly booted system, and the same thing happened again - error in VSCode console, yet app gets launched on my device.

**Comment by MSLaguana** [comment]
Could you please do the following to help us diagnose where we are going wrong:

* Open up your project in VS code with our extension, and try to build, getting the initial error
* Open up a console, and run `adb devices > /tmp/devices.out 2> /tmp/devices.err` to get the exact, whitespace-preserving output of adb devices
* Upload the /tmp/devices.out and devices.err files somewhere. Feel free to anonymise the device ID if you wish, but just replace the device ID with Xs or something, be sure not to change the whitespace. You can e-mail it to me at jithomso@microsoft.com if you don't want to put it somewhere public

Hopefully that will let me see what we are missing and work out a fix.

**Comment by porjo** [comment]
Here is the output file. The `.err` file was empty so I've left that off.

[devices.txt](https://github.com/Microsoft/vscode-cordova/files/235562/devices.txt)

**Comment by MSLaguana** [comment]
The regex that we use to detect devices works fine on that file, so I'm not sure why it is failing for you. I'll have to get a linux machine and test it our myself to see what's going on.

**Comment by porjo** [comment]
FYI, an interesting observation - I tried running vscode under strace e.g.: `strace -o process_dump -f code` and found that it the issue does NOT occur when run that way. Instead, console shows this message instead:
```
Launching for android (This may take a while)...
App successfully launched
Attaching to android
Forwarding debug port
Attaching to app.
Received Event: deviceready
```

**Comment by MSLaguana** [comment]
That's interesting, because unless strace follows through to child processes (which I don't think it does) that should not have any impact, because the debuggers are run as a separate process. You can actually start/debug that process yourself if you want: add `"debugServer": "4712"` to the root-level of your launch.json, go to `~/.vscode/extensions/[our extension]/out/src` and run `node debugger/debugCordova.js --server=4712`. That is the debug adapter process, and when you launch from VS code it will communicate with that process to do all the debug operations.

**Comment by MSLaguana** [comment]
Is it consistent that running vscode under strace has it work, while running it outside of strace leads to the original failure?

**Comment by porjo** [comment]
`strace -f` should pick up forked children also.

I tried your suggestion but get this error from debugServer after attempting to run the app:
```
$ node debugger/debugCordova.js --server=4712
waiting for v8 protocol on port 4712
>> accepted connection from client

/home/ian/.vscode/extensions/vsmobile.cordova-tools-1.1.1/out/debugger/common/v8Protocol.js:52
        this._pendingRequests = new Map();
                                    ^
ReferenceError: Map is not defined
    at CordovaDebugSession.V8Protocol (/home/ian/.vscode/extensions/vsmobile.cordova-tools-1.1.1/out/debugger/common/v8Protocol.js:52:37)
    at CordovaDebugSession.DebugSession (/home/ian/.vscode/extensions/vsmobile.cordova-tools-1.1.1/out/debugger/common/debugSession.js:130:16)
    at new CordovaDebugSession (/home/ian/.vscode/extensions/vsmobile.cordova-tools-1.1.1/out/src/debugger/cordovaDebugSession.js:23:16)
    at Server.<anonymous> (/home/ian/.vscode/extensions/vsmobile.cordova-tools-1.1.1/out/debugger/common/debugSession.js:161:17)
    at Server.emit (events.js:95:17)
    at TCP.onconnection (net.js:1192:8)
```

> Is it consistent that running vscode under strace has it work, while running it outside of strace leads to the original failure?

Yes, seems consistent. I've run it 5-6 times in a row and it worked everytime. Removing strace and running again results in the 'Unable to find device' error.

**Comment by MSLaguana** [comment]
That error when you run it yourself will be because of your node version; vscode uses 4.1.1 (last time I looked) so if you have 0.X that would explain the lack of Map.

I'll definitely have to investigate why things behave differently on linux; the fact that strace has an impact is bizzare but might indicate some kind of timing issue.

**Comment by dlebu** [comment]
@porjo Thanks again for reporting this issue and for using our tools. It is now fixed and will ship soon in the next extension update.

**Comment by dlebu** [comment]
@porjo The updated version of the extension is now published. You can update by typing `ext update` in your command palette. Please keep the feedback coming!
