### ISSUE TITLE
macOS: Javascript: "Go to Definition" opens wrong file

### ISSUE THREAD

**Issue by GitToTheHub** [microsoft/vscode-cordova#1021]
When I want to go to the definition of a property/method of my own declared objects, I'm redirected to the Android platforms folder, instead to the `www` folder, where the original file lies.

# Example

## Custom Object

Located under `www/js/my_javascript_file.js`:

```javascript
const MyObject = {
  property: "value"
}
```

## Usage of Custom Object

```javascript
const variable = MyObject.property
```

## Go to Definition MyObject.property
When I click on `property` of `MyObject.property`, I'm getting redirected to `/platforms/android/app/build/intermediates/assets/debug/mergeDebugAssets/www/js/my_javascript_file.js`
instead to
`www/js/my_javascript_file.js`

**Comment by lexie011** [comment]
Hi @GitToTheHub, it seems like your issue is with vscode or codorva. Please create this issue in vscode or cordova repo. Thanks
