### ISSUE TITLE
macOS: Javascript: Rename Symbol of property in object renames only `this` calls

### ISSUE THREAD

**Issue by GitToTheHub** [microsoft/vscode-cordova#1022]
When I want to rename a property of a custom object, only the occurrences of `this` calls are renamed.

# Example

## Custom Object

Located under `www/js/my_javascript_file.js`:

```javascript
const MyObject = {
  property: "value",
  myMethod() {
    const value = this.property
  }
}
```

## Usage of Custom Object

In another javascript file, like `www/js/my_usage.js`:

```javascript
const variable = MyObject.property
```

## Rename symbol `property` fails
When I want to rename `property` of `MyObject.property`, only `this.property`gets renamed, but not `MyObject.property`

**Comment by lexie011** [comment]
Hi @GitToTheHub, it seems like your issue is with vscode or codorva. Please create this issue in vscode or cordova repo. Thanks
