### ISSUE TITLE
Missing "cordova.properties.launch.hostname" nls message in marketplace version

### ISSUE THREAD

**Issue by yanglb** [microsoft/vscode-cordova#1031]
**Version** v2.7.0

The `"cordova.properties.launch.hostname"` nsl message is missing in marketplace published builds.

But it is in the latest code (master branch).

The marketplace published builds ⬇️
![Image](https://github.com/user-attachments/assets/2dbc91af-78e5-4a4f-a307-da25ee29a14f)

**Comment by EzioLi01** [comment]
Hey @yanglb , thanks for reaching us. We have updated locale in master branch. But currently our release process is blocked since MS is working on updating security steps in pipeline. We'll publish extension new version once it's done. Thank you!
