### ISSUE TITLE
Getting "No handler found for the command: 'cordova.build'" when Cordova project is in subfolder

### ISSUE THREAD

**Issue by mikaoelitiana** [Microsoft/vscode-cordova#125]
I have a project running Cordova in a subfolder, not in project root and I get the following error when trying to build Cordova project: 

`No handler found for the command: 'cordova.build'. An extension might be missing an activation event.`
<img width="1680" alt="capture d ecran 2016-06-01 a 09 16 03" src="https://cloud.githubusercontent.com/assets/674667/15699934/7e066eba-27d9-11e6-80d6-a47325f9e435.png">

I think there should be some configuration where I can tell which is my cordova project.

**Comment by dlebu** [comment]
@mikaoelitiana Thanks for the feedback. Currently we only support project root Cordova projects. As a workaround, if you have the parent (root) project opened in VSCode you can open the Cordova project in a new VSCode instance and edit/run/debug from there.

**Comment by mikaoelitiana** [comment]
Ok thanks Daniel

Le jeu. 2 juin 2016 19:46, Daniel Lebu <notifications@github.com> a écrit :

> @mikaoelitiana <https://github.com/mikaoelitiana> Thanks for the
> feedback. Currently we only support project root Cordova projects. As a
> workaround, if you have the parent (root) project opened in VSCode you can
> open the Cordova project in a new VSCode instance and edit/run/debug from
> there.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Microsoft/vscode-cordova/issues/125#issuecomment-223351111>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AApLa2BYNsZHSooi_IV2AdpBiqpNNGVtks5qHwjrgaJpZM4IrOIJ>
> .
>
-- 

Mika Andrianarijaona
+261340722394
http://mikaoelitiana.name

**Comment by mbraude** [comment]
@PatoBeltran can you check whether @dlebu checked a change in for this?

**Comment by dlebu** [comment]
@mbraude @PatoBeltran This was not addressed yet.
