### ISSUE TITLE
I can't copy a latitude value

### ISSUE THREAD

**Issue by digeff** [Microsoft/vscode-cordova#136]
If I right click, no context menu is shown, and If I use ctrl + C it doesn't copy the value either.

**Comment by dlebu** [comment]
This is a limitation of the `vscode.previewHtml` command. There is a vscode issue already active here: https://github.com/Microsoft/vscode/issues/6924

**Comment by mbraude** [comment]
The VS Code issue was closed 20 days ago. Is there anything for us to do here?

**Comment by PatoBeltran** [comment]
Nothing for us to do here. This was fixed by vscode in https://github.com/Microsoft/vscode/commit/5ed289fe8d70c5169df0a19619c9a559de1e4487
