### ISSUE TITLE
Replace forked Chrome debugger with vscode-chrome-debug-core

### ISSUE THREAD

**Issue by auchenberg** [Microsoft/vscode-cordova#152]
The Cordova debugger is currently using a fork of the [vscode-chrome-debug](https://github.com/Microsoft/vscode-chrome-debug), which makes it hard for this debugger to adapt bug fixes and improvements made in the new [vscode-chrome-debug-core](https://github.com/Microsoft/vscode-chrome-debug-core) library.

A few months ago we separated the core debugger from [vscode-chrome-debug](https://github.com/Microsoft/vscode-chrome-debug), which provides a generic Chrome debugger that's compliant to the Chrome Debugging Protocol, without specific runtime logic.

Today this core debugger is used by [vscode-chrome-debug](https://github.com/Microsoft/vscode-chrome-debug) and [vscode-edge-debug](https://github.com/Microsoft/vscode-edge-debug), and might be used for future Node.js debuggers too, as Node has adapted the same protocol.

You should consider replacing the current Chrome debugger with [vscode-chrome-debug-core](https://github.com/Microsoft/vscode-chrome-debug-core)

**Comment by MSLaguana** [comment]
We actually have a task for this already: #106

**Comment by auchenberg** [comment]
Ah cool @MSLaguana, didn't know! Just wanted to make sure it was on your radar.
