### ISSUE TITLE
Typings for InAppBrowser seem off

### ISSUE THREAD

**Issue by cfjedimaster** [Microsoft/vscode-cordova#154]
I'm having difficulty getting the intellisense for InAppBrowser to work right. 

1) The docs (https://www.npmjs.com/package/cordova-plugin-inappbrowser) show that InAppBrowser is available via the cordova object, but if you type cordova VSC will not suggest InAppBrowswer:

![image](https://cloud.githubusercontent.com/assets/393660/16363489/35a67644-3b91-11e6-8050-bbec2a87bea7.png)

2) If I type "InAp..." then VSC does suggest it, which implies it is in the global scope, but it isn't. 

3) If I'm at the end of InAppBrowser, VSC doesn't seem to recognize it as it doesn't suggest open:

![image](https://cloud.githubusercontent.com/assets/393660/16363497/64e99760-3b91-11e6-9741-78826ac4a06a.png)

**Comment by dlebu** [comment]
Thanks for reporting this issue. I have a PR out for the fix - #155. In the meantime, to get you unblocked, you can go to your typings file (`.vscode/typings/cordova/plugins/InAppBrowser.d.ts`) and append this code at the end:

```typescript
interface Cordova {
    InAppBrowser: InAppBrowser;
}
```

Let me know if this fixes your issues.

**Comment by cfjedimaster** [comment]
Confirmed - thank you!

On Mon, Jun 27, 2016 at 5:20 PM, Daniel Lebu <notifications@github.com>
wrote:

> Thanks for reporting this issue. I have a PR out for the fix - #155
> <https://github.com/Microsoft/vscode-cordova/pull/155>. In the meantime,
> to get you unblocked, you can go to your typings file (
> .vscode/typings/cordova/plugins/InAppBrowser.d.ts) and append this code
> at the end:
>
> interface Cordova {
>     InAppBrowser: InAppBrowser;
> }
>
> Let me know if this fixes your issues.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Microsoft/vscode-cordova/issues/154#issuecomment-228879215>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAYBvPUT4XGmb2PDNFxpXxAo7Hj4AwvWks5qQD6xgaJpZM4I-lnS>
> .
>



-- 
===========================================================================
Raymond Camden, Developer Advocate for StrongLoop at IBM

Email : raymondcamden@gmail.com
Blog : www.raymondcamden.com
Twitter: raymondcamden

**Comment by dlebu** [comment]
@cfjedimaster The updated version of the extension is now published and contains the fixes for the issues you reported. You can update by typing `ext update` in your command palette. Please keep the feedback coming!
