### ISSUE TITLE
Would be great to support windows platform

### ISSUE THREAD

**Issue by udiedrichsen** [Microsoft/vscode-cordova#160]
Hi,

I tried to add Windows to the launch.json file:
{
"name": "Simulate Windows in browser",
"type": "cordova",
"request": "launch",
"platform": "windows",
"target": "ie",
"simulatePort": 8000,
"livereload": true,
"cwd": "${workspaceRoot}"
}

but I get always: 
[cordova-debug-adapter] Error: Unknown Platform: windows

In my project folder "platforms" exists the sub folder windows and in platforms.json:
{
"windows": "4.4.0",
"android": "4.1.0"
}

**Comment by MSLaguana** [comment]
We currently don't support launching and debugging on windows desktop or phone in this extension, but We should still be able to simulate it, you are right. However we also don't currently have support for debugging IE in our extension.

We should be able to unblock the "windows" platform if you specify a browser target, but adding debugging support for IE is more complex and might not make it in for a bit.

Thanks for your feedback!

**Comment by udiedrichsen** [comment]
That would be great if you can unblock the windows platform :+1: 

I want to use cordova-simulate for Windows Cordova Test Automatisation.

**Comment by ridomin** [comment]
+1

**Comment by mbraude** [comment]
Hi @udiedrichsen, thanks for your feedback. We would like this as well. Unfortunately, supporting the Windows platform requires Edge to support the Chrome Remote Debug Protocol which it doesn't at this time. This feedback has made it to the Edge team and is something they've heard from you and other customers.

**Comment by ridomin** [comment]
Even if we can not debug, why not build and/or run appx? (as a workaround, in win10 we can always debug with F12 after deploying).

I also agree with @udiedrichsen on the simulate for windows. (in fact ionic serve --lab support windows theming) .

**Comment by mbraude** [comment]
@ridomin thank you for your feedback. I'm not sure this is an easy thing for us to do but we'll look into it when we have the time.
