### ISSUE TITLE
It would be great if F5 would open the debug console automatically

### ISSUE THREAD

**Issue by Ritzlgrmft** [Microsoft/vscode-cordova#161]
Currently my build/debug workflow for my Ionic2 app is the following, when I need to debug it on the device (which I need since I am testing some hardware functionalities which cannot be simulated):

- run `ionic serve --nobrowser` in the background
- press F6 for the cordova build: this shows automatically the output window
- press F5 for starting the debugger

Here it would be nice to see the debug window automatically - without explicitely showing it with `Ctrl-Shift-Y`.

No big deal, but helpful...

**Comment by MSLaguana** [comment]
I believe that this behavior is controlled by vscode itself, and is also working as-designed since you are also using the build output window. There was a time when the window would automatically switch between different views, and I remember that leading to hiding build failures and debugging against older outputs without realising.

Might be worth opening an issue on https://github.com/microsoft/vscode to discuss how this might best work.

**Comment by Ritzlgrmft** [comment]
I opened an [issue on vscode](https://github.com/Microsoft/vscode/issues/8706).

**Comment by Ritzlgrmft** [comment]
It is quite easy: just add 

    'internalConsoleOptions': 'openOnSessionStart'

to `launch.json`.

@MSLaguana Maybe you can add this option when you generate the `launch.json`?

**Comment by mbraude** [comment]
@Ritzlgrmft thanks for your feedback. I've copied this to our backlog and we'll get to it if we have time and we hear others asking for the feature as well.

**Comment by panarasi** [comment]
@Ritzlgrmft I was talking to other users and I think that this extension should respect the setting that VSCode does. Looks like not everyone wants the debug console to open. Also, when we prototyped this, we noticed that if we explicitly set this, a user's setting is overridden, some thing we do not want. 

My recommendation would be to not do this as a part of the extension, and respect what VSCode does. In you case, you can always add the setting to launch.json, as you mention. Will that be sufficient ?

Closing this issue are we do not plan to implement this. If you still believe that we should do this, please do re-open the bug and we see if other users want it too.
