### ISSUE TITLE
Ask for user consent before adding .vscode folder

### ISSUE THREAD

**Issue by ridomin** [Microsoft/vscode-cordova#162]
Everytime I open a cordova project with this extension, the .vscode folder is created and adding typings that not always I need.

What would be cool is to ask the user, the same way the C# extension does.

![image](https://cloud.githubusercontent.com/assets/1918324/16591257/d7b626dc-428f-11e6-8ddd-993d5c0204eb.png)

**Comment by axemclion** [comment]
@rido-min We are aware of this issue - we are working on a fix where the `typings` tool will instead be responsible for downloading only the required typings. 

This should be happening soon in the future.

**Comment by panarasi** [comment]
@ridomin VSCode is explicitly working on adding typings - so this will no longer be an issue. Closing this as there is another work item that is tracking this.
