### ISSUE TITLE
[FR] Titanium Mobile port

### ISSUE THREAD

**Issue by farfromrefug** [Microsoft/vscode-cordova#164]
I am not sure where to put this. And as it would be a good idea to start from that module, that seems like the right place to try!

Now that you have an extension for cordova, could we ask for an extension for Titanium Mobile?
That would be awesome!
A good starting point would be to fork this extension.

**Comment by panarasi** [comment]
@farfromrefug That is a great idea. I think this extension could be a great starting point, and we could help you write the extension. Did you have any specific questions about writing the extension ? 

Also, for Cordova, we can use the Chrome remote debug protocol for debugging the webViews. How would that work for Titanium ?

**Comment by farfromrefug** [comment]
@panarasi Actually might have a crazy lot of questions!
Plus i think Appcelerator would need to help on this.
There is a way to make the debugger work as TiStudio can debug Titanium application.
@jhaynie would that interest you guys? Would you help?

But even without the debugger, being able to trigger a build and such in vscode would be awesome!

**Comment by MSLaguana** [comment]
I am not personally familiar with Titanium Mobile, but you can define custom build steps in vscode on a per-project basis. See https://code.visualstudio.com/docs/editor/tasks for in-depth information, but essentially you just have to create a task.json file with `"isBuildCommand": true` and then when you Ctrl+Shift+B it will run that task.

**Comment by farfromrefug** [comment]
@MSLaguana Thanks. I know i can do that but we need to do it a little bit more complex. Like it is done [here](https://github.com/dbankier/vscode-titanium) 

I don't really have too much time to work on it now Even though i need to! That would be awesome if Appcelerator would help us

**Comment by axemclion** [comment]
@farfromrefug The [Titanium-VSCode](https://github.com/dbankier/vscode-titanium) repo actually seems to be the right place to do this.  
I think an issue should be opened here. I would also propose closing this issue since this extension is about cordova.

**Comment by farfromrefug** [comment]
@axemclion i opened it here because i thought it should start as a fork of this one. TItanium and Cordova being similar on many levels, it could be a good thing for both.
But yes closing this issue seems fine to me
