### ISSUE TITLE
Browser based debugger broke after successful usage

### ISSUE THREAD

**Issue by cfjedimaster** [Microsoft/vscode-cordova#165]
I have a project where I was debugging in the browser and it worked great. I used it a few times in my project when all of a sudden it stopped working. Hitting debug gave me: 

![image](https://cloud.githubusercontent.com/assets/393660/16659117/706cac6c-442e-11e6-80ec-92d6919aec21.png)

There is nothing wrong in my code - it builds just fine - but the debugger simply can't fire off anymore.

If I open launch.json, nothing seems wrong. I killed Code, restarted, and it worked fine after that.

**Comment by cfjedimaster** [comment]
I'm pretty sure I know how this happens. If I close the browser window for my app, it seems like VSC gets confused. I guess I'm supposed to hit stop first, but I forget.

**Comment by MSLaguana** [comment]
What launch target were you targeting? Does this only happen for the simulator?

**Comment by cfjedimaster** [comment]
It was the new one that is Ripple based - simulate in browser.

**Comment by MSLaguana** [comment]
Thanks, I'll see if I can reproduce it and find out what's causing the issue.

**Comment by MSLaguana** [comment]
I know I've seen this error happen intermittently before, but I can't seem to get it reproducing at the moment. I tried your suggestion of launching the simulation, closing the browser window, then re-launching, but it seems to be working for me so far.

**Comment by MSLaguana** [comment]
If you do have this happen again, it would be great if you could add in a stack trace for the error output: Go to `~/.vscode/extensions/vsmobile.cordova-tools-1.2.1/out/src/debugger/cordovaDebugAdapter.js` on line 422 and add `_this.outputLogger(e.stack);`. That should give some more insight into where exactly this error is coming from.

**Comment by cfjedimaster** [comment]
After being able to consistently get this happening... now it isn't. :\ I'll save this and hopefully I can recreate it later.

**Comment by mbraude** [comment]
@cfjedimaster thanks for reporting this. If you happen to repro this again, please send us an email at vscordovatools@microsoft.com so we can take a look at your machine and learn more.
