### ISSUE TITLE
"Break on exceptions" checkbox missing

### ISSUE THREAD

**Issue by shrishrirang** [Microsoft/vscode-cordova#167]
- The "break on exceptions" checkbox is missing from the breakpoint menu while debugging a Cordova app in VS Code.
- I can see this happening with VS Code 1.3.0 and Cordova tools 1.2.1
- This is a regression since VS Code 1.2.0.

**Comment by PatoBeltran** [comment]
@shrishrirang that was a known issue with `vscode-chrome-debug` which we rely on. We have a fix for this ready on a PR (https://github.com/Microsoft/vscode-cordova/pull/166) just waiting to be merged.

**Comment by shrishrirang** [comment]
Hey, is the Cordova tools 1.2.2 update going to be out anytime soon? I am wondering if I should wait for it or use an older version of VS Code in the meanwhile.

**Comment by MSLaguana** [comment]
We are just finalizing the release now, but I think the code is in a good place at the moment if you wanted to compile the extension yourself. We've tried to keep the barrier to entry low: If you check out this repository, npm install, and then "gulp package" it should produce a vsix, and if you then open the vsix with vscode it will install your custom built version of the extension.

**Comment by shrishrirang** [comment]
Cool, I'll try that out. Thanks!
