### ISSUE TITLE
Ionic2. simulate iOS on  browser does not respect theming

### ISSUE THREAD

**Issue by ridomin** [Microsoft/vscode-cordova#170]
Running the [ionic-conference-app](https://github.com/driftyco/ionic-conference-app)  on vscode with simulate ios in browser option does not render as iOS, and the look & feel is from android.

Note that the same test works in Ripple

**Comment by PatoBeltran** [comment]
Hi @ridomin thanks for reporting this! I'm trying to repro on Ripple so I can investigate their behavior but it seems like they don't support this either (see screenshot), how are you running Ripple?

![ripple-ionic2](https://cloud.githubusercontent.com/assets/2132567/16891089/ee749184-4aa9-11e6-8748-27eaaf0037f3.png)

**Comment by ridomin** [comment]
On iOS the tab bar is at the bottom, while in android is at the top. In Cordova simulate if you select simulate iOS in browser the theme is like android

**Comment by MSLaguana** [comment]
This may be due to the user agent, which we currently don't spoof. We make sure to report the correct platform via cordova, but the browser environment is not guaranteed to be identical to safari (unless you run in safari) and so the theming may depend on how the app checks.

This might be a feature to put into cordova-simulate, although it may also require help via the debugger channel (like the window resizing feature).

**Comment by TimBarham** [comment]
Yeah, I'm pretty confident this is because cordova-simulate doesn't currently spoof the user agent string, where-as Ripple does.

**Comment by PatoBeltran** [comment]
@TimBarham as a workaround in `vscode-cordova` we can append `?ionicplatform=platform` to the simulate url and this will give us the appropriate theme. What do you think about this approach?

**Comment by TimBarham** [comment]
Sounds reasonable. It won't respond to changes in device (via the Device panel), but I think that's ok until we get some sort of device/platform story properly sorted out for `cordova-simulate` (and when we do that, I hope that will also include user agent spoofing).

**Comment by PatoBeltran** [comment]
This is being addressed in https://github.com/Microsoft/vscode-cordova/pull/173, in addition to ionic 2 support.
