### ISSUE TITLE
The README should talk about how to setup Android environment

### ISSUE THREAD

**Issue by changsi-an** [Microsoft/vscode-cordova#180]
Instead of showing messages like "Please manually set ANDROID_HOME" "Missing JAVA_HOME" etc after launching a debug session, the README.md should at least mention the requirement of Android SDK, JDK and the need of creating a default AVD. Or at least add a link to Cordova documentation on how to set up Android environment. This will be very helpful to onboard those people without prior Cordova experience to VS code.

The same thing should apply for IOS-based dev experience as well.

**Comment by jicongw** [comment]
#182
