### ISSUE TITLE
Add support for local ionic/cordova installs

### ISSUE THREAD

**Issue by rob3c** [Microsoft/vscode-cordova#181]
Hi, please add support for using local per-project installs of ionic/cordova, if they exist. Currently, the extension expects a single version of each to be installed globally and on the system path, which makes it difficult to use across projects spanning multiple versions of each. Thanks!

**Comment by panarasi** [comment]
Hey @rob3c - this looks like an interesting feature. How are you currently using per-project ionic install ? Do you simply have node_modules/ionic and use node_modules/.bin/ionic when you need to run the CLI ? 

Also, for VSCode, do you think it would be sufficient if we add this as an option in the `.vscode/settings` folder ?

**Comment by rob3c** [comment]
@panarasi Yes, I'm using that indirectly. Since npm adds the local `node_modules/.bin` folder to the path for executing scripts, I just do `npm install --save-dev cordova ionic2` and then add some pass-through scripts:
```
// package.json
...
  "scripts": {
    "cordova": "cordova",
    "ionic": "ionic"
    ...
  }
```
Then I can use the `--` separator to pass CLI args to the scripts (otherwise they'll go to npm itself):
```
> npm run ionic -- platform add android
> npm run ionic -- serve
```
That also puts other local modules in context that would otherwise need to be available globally.

Unfortunately, `cordova create` and `ionic start` won't generate into an existing directory, but I tend to use my own project templates or start from git repos, anyway.

However, one strategy for leveraging their project generators is to use global installs to bootstrap a new project, and then pin the versions used to create it by installing them locally as devDependencies. Either way, if you have to go back later to work with an older project built with earlier versions, you don't have to worry about whatever your current global versions are. (This is also nice for mocha, typescript and other things that are typically installed globally but can start breaking things across projects of differing vintage.)

Having a configurable option is a good idea, as there may be issues with local installs I haven't seen yet that other users doing things the usual way might run into. First cut, maybe your code can remain as-is (i.e. invoking `cordova` or `ionic` directly) and the vscode setting can just optionally include the `node_modules/.bin` folder on the path like npm does?

**Comment by chawax** [comment]
I need this feature too. For now I use nvm to have a node instance / version per project so I can use both Cordova and Ionic globally. But this works only for dev, when you need to set up continuous integration it is hard to deal with multiple node versions.

**Comment by ocomsoft** [comment]
Ideally it would be good if it would use the node_modules/.bin instance of ionic and cordova but I have found that (in linux) if I set the path correctly then run vs-code it works as expected..
