### ISSUE TITLE
simulate android in browser not working..

### ISSUE THREAD

**Issue by wxb1** [Microsoft/vscode-cordova#183]
On the debug console:

Launching for android (This may take a while)...
Attaching to app
Failed to load resource: the server responded with a status of 404 (Not Found) (http://localhost:8000/favicon.ico)

on the browser (chrome)

http://localhost:8000/http://straightwaysolutions.com/staffing/

in address bar:

in web page body

Cannot GET /http://straightwaysolutions.com/staffing/

**Comment by MSLaguana** [comment]
That missing favicon is expected since the apps do not include a favicon.

Are you explicitly typing the `http://localhost:8000/http://straightwaysolutions.com/staffing` URL yourself, or is our extension trying to navigate to that page when you try to simulate in browser? What is the start page of your app in config.xml?

**Comment by wxb1** [comment]
The extension is opening the chrome browser with the url:
![chrome](https://cloud.githubusercontent.com/assets/19365422/18075141/e4638b9e-6e37-11e6-850e-7633c481f517.png)


here is the start page:   <content src="http://straightwaysolutions.com/staffing/" />

**Comment by MSLaguana** [comment]
What does your config.xml specify as your start page? It should be a `<content src="" />` tag.

**Comment by wxb1** [comment]
<content src="http://straightwaysolutions.com/staffing/" />

**Comment by MSLaguana** [comment]
That explains it then. We use `cordova-simulate` to provide the simulation, and it doesn't support hosted apps, where the app content is served from a webserver rather than part of the app itself.

You could add a request for that feature over at https://github.com/microsoft/cordova-simulate

**Comment by wxb1** [comment]
thanks for the help... I will ask for the feature
