### ISSUE TITLE
InAppBrowser not working with simulate android in chrome

### ISSUE THREAD

**Issue by tiansivive** [Microsoft/vscode-cordova#184]
Hi!

I've been trying out this extension mostly for the great debugging abilities.
I usually develop my ionic apps in the browser but then I have to switch to an emulator when I need cordova plugins, which makes the whole build/debug cycle rather tedious.
I thought the 'simulate in browser' option supported cordova plugins but apparently the InAppBrowser doesn't work properly as the event handler doesn't get called after the first event. However, the simulate window in VScode recognizes the plugin and displays some options, in my case, whether to open _blank as window._system or on an iFrame. Regardless of choice, the event handlers aren't triggered. 

Am I missing something?
Thanks in advance

Here's my code
```
private login(uri: string) {

		// Add event listener on every load (i.e. refresh), redirect is an example event
		let iBrowser = new InAppBrowser(uri, '_blank', "location=yes");
		let obs = iBrowser.on('loadstart');
		let disposable = obs.subscribe(
			(event: InAppBrowserEvent) => {

                /**This only runs on the first redirect event**/
				let foundToken = event.url.indexOf('token=');
				let foundId = event.url.indexOf('userId=');

				if (foundToken > -1 && foundId > -1) {
					//figure out token and user ID

					disposable.unsubscribe();
					this.storeToken(obj.token);
					this.nav.setRoot(Pages.Profile);
					iBrowser.close();
				}
			})
```

**Comment by MSLaguana** [comment]
Thanks for reporting this. Sounds like it may be an issue with cordova-simulate, the library that we use for the "simulate in browser" feature. Could you please report the issue at https://github.com/Microsoft/cordova-simulate/issues

**Comment by tiansivive** [comment]
@MSLaguana Ok, will do

**Comment by MSLaguana** [comment]
Issue has moved to https://github.com/Microsoft/cordova-simulate/issues/144
