### ISSUE TITLE
Set emulator target by default in a project

### ISSUE THREAD

**Issue by victorsosa** [Microsoft/vscode-cordova#187]
I would like to have this feature in this extension; In Cordova to run a specific emulator you run this command line:
`cordova run --target=name_of_your_emulator android`

Right now I got this:
```
No emulator specified, defaulting to demo
Waiting for emulator to start...
```
It load the last emulator in the list

By adding a nw config parameter in the launch.json like:
```
        {
            "name": "Run Android on emulator",
            "type": "cordova",
            "request": "launch",
            "platform": "android",
            "target": "emulator",
            "emulatorName": "demo"
            "port": 9222,
            "sourceMaps": true,
            "cwd": "${workspaceRoot}",
            "ionicLiveReload": false
        }
```

**Comment by MSLaguana** [comment]
You should be able to do this already: Instead of specifying `"target": "emulator"`, specify `"target": "<name of emulator>"`. E.g., if you would write `cordova run --target=foo` on the command line, you can specify `"target": "foo"` in launch.json and we will pass that argument along.

**Comment by victorsosa** [comment]
Thank you, it works.
