### ISSUE TITLE
"Unable to mount developer disk image." with ios10 and xcode 8.0

### ISSUE THREAD

**Issue by brusinow** [Microsoft/vscode-cordova#192]
I am trying to "run ios on device" and can't seem to get past this error. The simulator works fine. I read some other suggestions to reset my device - tried that with no success. Any ideas/suggestions?

**Comment by MSLaguana** [comment]
You need to update the library that we use to interact with iOS devices. Please run `brew update && brew upgrade libimobiledevice --HEAD && brew upgrade ideviceinstaller ios-webkit-debug-proxy` and try again.

**Comment by brusinow** [comment]
Awesome - that did it for one of my apps but I'm still getting a "Timeout launching application. Is the device locked?" error on the other one. Device is not locked and I tried adding an attachDelay and increased attachAttempts with no luck. Thanks, any help is really appreciated.

**Comment by MSLaguana** [comment]
These are separate apps on the one device, is that correct? And the app appears to be running on the device, but we fail to attach to it? Or does the app not launch?

If the app is installed, can you manually launch it?

**Comment by MSLaguana** [comment]
If you can successfully launch the app yourself but it's failing when we try to launch it, you could also try increasing the `"appStepLaunchTimeout"` in the launch.json. That value is specifically how long we allow for the each of 3 steps in the app launching process and defaults to `5000` (5 seconds).

**Comment by brusinow** [comment]
The app is successfully launching on the device but is not attaching to the vscode debugger. I tried increasing the "appStepLaunchTimeout" (tried 10000 and 15000) and didn't see an improvement. Still getting that "Is your device locked?" error.

**Comment by MSLaguana** [comment]
Could you please try something for me:

Go to `~/.vscode/extensions/vsmobile.cordova-tools-1.2.2/out/src/debugger/` and edit `cordovaIosDeviceLauncher.js`. You should find 3 instances of the `Timeout launching applicaiton` string, could you add a number to them to distinguish them? I suspect that it will be the third one which is triggering, but I'd like to be sure.

While you're in that file, could you also look for the `socket.on('data', function (data){ `handler, and just after `data = data.toString()` add the following:

```
var tmpContents = fs.readFileSync("/tmp/socketContents.txt");
tmpContents += data;
fs.writeFileSync("/tmp/socketContents.txt", tmpContents);
```

then in a console `touch /tmp/socketContents.txt`

Once you've made those changes, try debugging again, then could you please upload the temp file somewhere for me to look at. We determine that the app has launched by waiting for console output from the app, but if that is not coming (and only in the one app) it could explain why we don't believe the app has started. If I can get a look at the socket communication above, then I can get a good idea of what is happening and hopefully sort out a fix.

**Comment by brusinow** [comment]
Alright, confirmed that it is the 3rd timeout that is triggering and here is the content of the socketContents.txt file:
+$OK#9a+$OK#9a++$OK#9a+$OK#9a++$OK#9a+$OK#9a++$OK#9a+$OK#9a++$OK#9a+$OK#9a+

**Comment by MSLaguana** [comment]
Ok, that explains the cause then. If you clear out the file and try to run your other app which launches successfully then you should see an entry in there that looks something like `$O#<hex string>#<hex digits>+` which means "This is some console output of your app". In the cordova applications we've seen in the past there have always been console messages as they start up, so we use that to determine "the app really has started", but it looks like this particular app goes against that trend.

Something that might resolve the situation for you while we sort out a better approach (or implement this one for everyone): Back in that file I asked you to edit, remove the `writeFileSync` changes before we forget, and then go look for `//last command was received OK` and find the conditionals after it. Add in 

```
else if (initState === 3) {
    deferred3.resolve(socket);
    initState++;
}
```

then try debugging again and hopefully it will proceed.

I'm curious about what may have caused this. What plugins differ between your two apps? Specifically are there any added to the one that fails that are not in the one which worked?

**Comment by brusinow** [comment]
Added in this conditional and it's still timing out. Really strange.

I built the app that is working correctly from scratch, this app is one that I am doing some freelance work on. The only plugin that they're using that isn't in the working app is DeviceOrientation.

**Comment by MSLaguana** [comment]
Hmm, that is odd. Just to be sure, could you please try replacing the file with this https://gist.github.com/MSLaguana/a096f56c8db83a005ff33545d38e441b

That should just have the added conditional that I mentioned above, added https://gist.github.com/MSLaguana/a096f56c8db83a005ff33545d38e441b#file-cordovaiosdevicelauncher-js-L141

**Comment by MSLaguana** [comment]
Also, I would hope that DeviceOrientation wouldn't have an impact on whether it prints anything to the native console; are they targeting different versions of cordova-ios? `cordova platform ls` should show what they are using.

**Comment by brusinow** [comment]
I replaced CordovaIosDeviceLauncher.js, confirmed that Cordova version is 4.2.1, and still getting same timeout/phone locked error. Really strange!

I really appreciate you trying all these suggestions, it's not vital for me to keep working on the app.

**Comment by mouli-preddy** [comment]
Updating the thread as I have a similar problem.

After changing the mentioned file I go rid of "Developer disk image not found" and it is the 3rd 
statement causing the trouble here.
appStepLaunchTimeout is already set to 15000.

My current error is "Timeout launching application. Is the device locked? 3".

Thanks for any help in this case.

**Comment by sbryfcz** [comment]
Same issue.
