### ISSUE TITLE
can't hit a breakpoint for ios

### ISSUE THREAD

**Issue by crich1979** [Microsoft/vscode-cordova#193]
Do you guys have any plans on how you will support ios 10.  I logged the following issue on ios_webkit_debug_proxy and it looks like they are not going to support debugging on ios going forward https://github.com/google/ios-webkit-debug-proxy/issues/164.

**Comment by MSLaguana** [comment]
What version of VSCode are you using? I've seen a report that the insiders build 1.6.0 had an issue with breakpoints and I'd like to rule that out as a possibility.

**Comment by crich1979** [comment]
1.5.3  It looks like an issue with using the ios_webkit_debug_proxy in this way based on the response.

**Comment by MSLaguana** [comment]
Thanks for letting us know about this, we'll have to investigate closer to see how their debugging protocol differs from what we currently expect.

**Comment by MSLaguana** [comment]
A colleague just investigated this and found that the debugging protocol should not be any different, but the debugger frontends behave differently. Specifically, chrome devtools (and possibly our tools, I need to double check still) do not send a `Debugger.setBreakpointsActive` message to the device, while Safari web inspector does. We will need to make sure that we do send that message to ensure that breakpoints and debugger statements work correctly.

**Comment by crich1979** [comment]
That's good news, hope it works out .  I will keep an eye out for an update.  Thanks for looking at this so quickly.

**Comment by vejja** [comment]
Same issue here.
Breakpoints are not hit when attaching device running on iOS 10 simulator.
Breakpoints are hit on iOS9 though.

**Comment by jainpiyushb** [comment]
Facing the same issue. Works on iOS 9 devices but not on iOS 10 simulator/device.

**Comment by jimwhitelaw** [comment]
I've encountered the same issue. My temp workaround is to run the vscode debugger then open Safari web inspector for the app. After that, debugging in VSCode works properly, even if Safari is quit.
