### ISSUE TITLE
Question - Any roadmap for Ionic 2 support?

### ISSUE THREAD

**Issue by Martin-Andersen** [Microsoft/vscode-cordova#198]
First this plugin is uber cool, thank's

I know that Ionic RC1 is just out, but how is it going with adding support for this great framework?

**Comment by jmatthiesen** [comment]
Glad to hear that you like the plugin! Ionic 2 works by default with our extension for several features, are there any specific issues you're running into?

**Comment by Martin-Andersen** [comment]
No it seems to work, but you write that there is no support for Ionic beta 2 in the plug-in manager for VSCode

**Comment by andybeaulieu** [comment]
I don't think debugging works from VSCode with Ionic 2. Unless I am missing something.

When I debug from VSCode using "Serve to the browser (ionic serve)", it appears the SourceMaps are not being used (I get a breakpoint in minified .js instead of the .ts). 

Debugging .ts from Chrome works OK though.

Is anyone else able to get this working with RC1 of Ionic 2?

**Comment by Martin-Andersen** [comment]
I think the should stop bundle js when you are in development / browser mode. Use JSPM and transpile in the browser.

**Comment by suil** [comment]
@Martin-Andersen do you know how to stop bundle js in development mode?

**Comment by Martin-Andersen** [comment]
I have not looked into the Iconic build process as I am still new to the Ionic framework.
I know how to setup jspm, but has never worked with webpack. My personally preference is to only bundle when deploying to test or production. But thats for web, guess you have to do the same when deploying to an emulator or phone.

**Comment by vladimir-kotikov** [comment]
Now after Ionic 2 is out of preview we're going to address a number of ionic related issues, so expect more robust Ionic 2 support in one of next releases.

Closing this for now, If you guys are having any particular issues about Ionic 2, feel free to reopen or create separate issues. Thanks.
