### ISSUE TITLE
Breakpoints not being hit in typescript code

### ISSUE THREAD

**Issue by fjtest** [Microsoft/vscode-cordova#203]
I am using ionic 2 rc1 ( version 2.1.4 ) and created a tutorial starter app with $ionic start testme tutorial --v2. Using vscode 1.6.1 and Cordova tools 1.2.3. When I set breakpoints in the ts files they show up as "unverified breakpoints" and are never hit at runtime. I am debugging on an Android device, and have also tried debugging in browser simulating Android, and debugging using Serve to Browser.  All did not work.  My tsconfig and launch.json files remain unchanged from when initially created. Any ideas why breakpoints are not hit in the ts files?   Note if I put a hardcoded "debugger;" statement it does get hit in the generated main.js file.  Thanks for any help!

I see under the project directory/.tmp/pages/list/list.js.map the following in the file: 
{"version":3,"file":"list.js","sourceRoot":"","sources":["list.ts"],"names":[],

The tsconfig file has:
{
"compilerOptions": {
"allowSyntheticDefaultImports": true,
"declaration": false,
"emitDecoratorMetadata": true,
"experimentalDecorators": true,
"lib": [
"dom",
"es2015"
],
"module": "es2015",
"moduleResolution": "node",
"sourceMap": true,
"target": "es5"
},
"include": [
"src/*/.ts"
],
"exclude": [
"node_modules"
],
"compileOnSave": false,
"atom": {
"rewriteTsconfig": false
}
}

And the launch.json has:

"version": "0.2.0",
"configurations": [
{
"name": "Run Android on device",
"type": "cordova",
"request": "launch",
"platform": "android",
"target": "device",
"port": 9222,
"sourceMaps": true,
"cwd": "${workspaceRoot}",
"ionicLiveReload": false
},

**Comment by MSLaguana** [comment]
Can you please look at the source map next to your compiled JS, I believe it's in something like `www/build/`? If that sourcemap has a `file:["webpack://..."` element which is full of `webpack://` references, then we don't support that at the moment.

I suggest following the documentation at https://webpack.github.io/docs/configuration.html#output-devtoolmodulefilenametemplate and creating a `webpack.config.js` file specifying something like `[absolute-resource-path]`

**Comment by fjtest** [comment]
Thanks for the response.  I am seeing a couple of things:

- if I do a command line build I see main.js.map get generated and placed under www/build/ right next to the main.js file.  The map file does not have a bunch of file:["webpack.. elements in it from what I see

- if I then debug ( Serve to browser at the moment ) the map file is getting deleted from the www directory.   No idea why

- I created a web pack.config.js file and placed it in the top level directory, and did a build but am not seeing any difference in the map output.  Does this file need to go any other location than the ${workspaceRoot} directory?

- Lastly, the standard build process seems to compile everything under .tmp, and this is where the individual map files for each ts file live.  the amalgamated main.js file and its map are assembled here too; whereas the www/build directory only contains main.js ( and associated other main files ).  Does the debugger need to know or care about the individual ts map files?  I ask because if I grep main.js.map for list.ts ( one of the tutorial typescript files ) I do not see it contained in the map, yet obviously it is in the .tmp/pages/list/list.js.map file

Thanks for any insight into this!!!!

**Comment by MSLaguana** [comment]
The debugger knows that you are running `main.js`, and `main.js` should include a reference to `main.js.map`. This map links the compiled sources with the original source files, and we expect that to be done in a single step so the `main.js.map` should refer back to the original `foo.ts` source files if you want to set breakpoints in them.

I know that ionic 2 is currently undergoing rapid changes, especially to do with the build infrastructure, so it might be worth your while asking what the current expectation is with ionic 2. I'm not sure why your map file would be deleted, it's certainly not something that we do in our extension.

**Comment by fjtest** [comment]
Thanks again, and agree on the rapid change - you guys are doing a great job just trying to keep up in the plugin!

in main.js ( not the map file ) I see a reference to the list.js.map file:
      build/main.js:     //# sourceMappingURL=list.js.map

where build/main.js is just the file grep found the match in.

if this is the reference that the debugger is keying off of, obviously its not a full path to the file.  Is there somewhere besides the project root dir that web pack.config.js should live?   Thanks again for your help.  In the mean time I'm just going to edit in the full path in this reference and see if it works at all...

**Comment by MSLaguana** [comment]
From that reference, we would expect to find a `list.js.map` adjacent to `main.js` in the filesystem. Was that reference right at the bottom of the file? Based entirely on the name, I suspect that it may have been erroneously included and would just be referring to a small component of the project (possibly `list.ts`) rather than the whole thing.

**Comment by fjtest** [comment]
No - its right in the middle of the main.js file where the list.js content ( coming from list.ts ) is located.  This is the code I want to set my breakpoint at :)

I copied the list.js.map to the same directory, but as before something is deleting it from the directory.  I'll try changing the URL to be an absolute path and see if that helps at all...

**Comment by MSLaguana** [comment]
Even if you did point at the `list.js.map` file it sounds like it wouldn't work for you: sourcemaps map lines to lines, and I believe that `list.js.map` file is expecting to map `list.js` to `list.ts`, which means that "line 0" in `list.js` is different to "line 0" in `main.js` and the mapping will probably be messed up.

It sounds like part of the source map pipeline is messed up, since a js file should have exactly one `sourceMappingUrl=` in order to work correctly, not to mention the files being removed for some reason. I suggest asking on the ionic slack channel for information on what is going on there.

**Comment by fjtest** [comment]
Cool, will do :)

**Comment by fjtest** [comment]
For anyone else dealing with this, the following blog posts summarizes the changes going on the last couple of days / weeks to the ionic build process

http://blog.ionic.io/ionic-build-process-updates/

**Comment by fjtest** [comment]
@MSLaguana - is there a time table when webpack:// references will be understood by the plugin?   ionic has a build change coming out where map files have these in them.  Also, if the reference is just: webpack:///hello-ionic.ts","webpack:///item-details.ts","webpack:///list.ts", does the plugin make any assumptions on where to find these files?   And if so, does the map file for these files need to be in the same directory???   Thanks!!!

**Comment by pantonis** [comment]
Have the same problem here. Breakpoints are not hit when debuggin Ionic 2. Shame because VS Code is amazing and this plugin would make life much more easier

**Comment by meeximum** [comment]
+1

**Comment by sahildaga95** [comment]
+1

**Comment by zmirza** [comment]
I am unable to debug typescript code. I am using VS Code with Cordova tools 1.2.4 extensions and Ionic 2 RC3
On breakpoint I message "unverified breakpoint"
Tried attaching to device and IOS simulator with no success. It runs and deploys code on IOS simulator but it does not stop on typescript code.
Also what is the difference between "Run IOS on simulator" and "Attach to running IOS on simulator"

However, I am able to debug the code when selected "Simulate IOS in browser"
here is lanuch.json

{
            "name": "Simulate iOS in browser",
            "type": "cordova",
            "request": "launch",
            "platform": "ios",
            "target": "chrome",
            "simulatePort": 8000,
            "livereload": true,
            "sourceMaps": true,
            "cwd": "${workspaceRoot}"
        },
{
            "name": "Run iOS on simulator",
            "type": "cordova",
            "request": "launch",
            "platform": "ios",
            "target": "emulator",
            "port": 9220,
            "sourceMaps": true,
            "cwd": "${workspaceRoot}",
            "ionicLiveReload": false
        },

**Comment by MSLaguana** [comment]
The difference between `Run iOS on simulator` and `Attach to running iOS on simulator` is that the second option will not build and run your app: it expects the app to already be running, and it will simply attach to it to begin debugging.

As for the debugging failure, I believe that the issue remains with the sourcemaps. If your `main.js` has a `sourceMappingUrl` which references a `main.js.map` (or similar), please check whether the `main.js.map` has a `files:[` entry which references typescript files on disk, or if they are `webpack://` references or something else. We still don't support `webpack://` references at the moment, but if they are file paths then we should be able to work with it.

**Comment by zmirza** [comment]
Thanks  for the quick response.
Yes, main.js does have sourceMappingURL at the end of the file.
//# sourceMappingURL=main.js.map

I looked at main.js.map and did not find files:[entry which references typescript files]

I also did not find entry like webpack:// 

however, I found few entries with __WEBPACK. here are some of them from main.js.map file

"version":3,"sources":["/Users/zeeshanmirza/Documents/Ionic/Research/Ionic2/test3/www/build/main.js"],
"names":["modules","__webpack_require__","moduleId","installedModules","exports","module","i","l","call","m","c","value","d","name","getter","o",
"Object","defineProperty","configurable","enumerable","get","n","__esModule","object","property","prototype","hasOwnProperty","p","s",

"__WEBPACK_IMPORTED_MODULE_0__src_core__","setIndex","args","opts","resolve","reject","sync","callbackOrder","unshift","callbackStyle","push","err","result","successName",
"errorName","obj","successIndex","errorIndex","length","splice","callCordovaPlugin","pluginObj","methodName","pluginInstance","getPlugin","pluginRef",

"__WEBPACK_IMPORTED_MODULE_0__util__","window","apply","cordova","pluginWarn","error","cordovaWarn","getPromise","cb","tryNativePromise","Promise","console","angular","injector",
"element","document","querySelector","body","$q","warn","wrapPromise","pluginResult","rej","catch","wrapOtherPromise","then","wrapObservable",

"__WEBPACK_IMPORTED_MODULE_1_rxjs_Observable__","observer","next","bind","clearFunction","clearWithArgs","e","callInstance","_objectInstance","wrapInstance","_i","arguments","observable","otherPromise","wrapEventObservable","event","addEventListener","removeEventListener","overrideFunction","method","complete","Plugin","config","cls","k","printWarning","Cordova","target","descriptor","wrap","this","CordovaInstance","CordovaProperty","key","originalMeth

I have also attached a zip file which contains main.js, main.js.map, polyfills.js from BUILD folder

Again thanks for your
[main.zip](https://github.com/Microsoft/vscode-cordova/files/656086/main.zip)
 help.

**Comment by MSLaguana** [comment]
It looks like the sourcemap is missing references to the actual sources... The `sources` array which just references `main.js` is supposed to be the original sources that were compiled, e.g. `"sources": ["foo.ts", "bar.ts"]`, but instead it just claims to be its own source which doesn't make any sense to me. The end of the file is a bunch of encoded offsets, something like "line X column Y corresponds to file number A line B column C", but nowhere in that sourcemap does it say which files are the real source files.

**Comment by zmirza** [comment]
Anytime I debug in VS Code it generates (main.js,main.js.map and polyfills.js) under www/build folder. Not sure what type of mapping it generated earlier when I used Ionic 2 RC3.

I just installed Ionic 2 RC4 and tried to debug TypeScript file in VS Code. This time I do see red break points in Type Script code. However, it still does not stop at any break point.

I looked into main.js.map file and I do see some .TS files.  But they are not under files:[]

I attached zip file with all files that build script generated when I clicked on debug button in VS Code with "Run IOS on simulator"

Thanks for your help again

[main.zip](https://github.com/Microsoft/vscode-cordova/files/658339/main.zip)

**Comment by MSLaguana** [comment]
I misspoke initially and I meant to refer to the `sources` property, which does look to be correctly configured there. I'll have to look further to understand why the breakpoints aren't being hit now though.

**Comment by zmirza** [comment]
I even created new Ionic 2 RC4 project and tried debug it in VS code. I see red break points but still unable to hit them. Attached screen shot shows following information:

1. Ionic version details
2. App running in IOS simulator
3. VS code with break points enabled and running in debug mode
4. main.js, main.js.map generated

Thanks for looking into this issue. 

<img width="1841" alt="screen shot 2016-12-17 at 7 31 58 pm" src="https://cloud.githubusercontent.com/assets/7378775/21290638/7417fa8c-c490-11e6-9518-c41cfb53f80d.png">

**Comment by jmesa-sistel** [comment]
Add 
```
"config": {
    "ionic_bundler": "webpack",
    "ionic_source_map": "source-map"
  },
```
in `package.json` to be able to debug properly.
By default ionic2 use eval sourcemap which is faster but not compatible to be used with an IDE.

**Comment by fxlemire** [comment]
@jmesa-sistel Yeah it did the trick! Thanks so much man!

**Comment by vladimir-kotikov** [comment]
Looks like this has been already resolved - I'm now able to debug Ionic 2 project without any additional configuration. Closing this
