### ISSUE TITLE
"Cannot connect to the target: socket hang up"

### ISSUE THREAD

**Issue by Tsmith18256** [Microsoft/vscode-cordova#204]
I am trying to debug our app on my Android phone with this extension for the first time, but I am getting "[cordova-debug-adapter] Error: Cannot connect to the target: socket hang up" when trying to run the app or manually attach after.

I have tried running `adb -s FA6910305614 forward tcp:9222 localabstract:webview_devtools_remote_22202`, as suggested in #38, but that didn't work either; opening "http://localhost:9222/" in Chrome did nothing but say "The localhost page isn't working; localhost didn't send any data; ERR_EMPTY_RESPONSE."

I tried the same command to forward just to the normal Chrome Dev Tools (the Chrome app itself) and that worked fine. I also tried using a few different ports with no luck. I have attempted this on a couple devices: a Google Pixel on Android 7 and a Nexus 4 on Android 5.1.

We are using Crosswalk for our project, if that makes a difference, but I tried temporarily removing Crosswalk and it still didn't work.

**Comment by MSLaguana** [comment]
If you are using crosswalk then the currently published version of the extension doesn't work for debugging android, but there was a PR a couple of weeks ago to add that support and we should be publishing an update in the near future which will include that. Alternately you can check out this repo and try building it yourself.

If it was still failing when you had removed crosswalk, then that must be a separate issue. Are you able to create a fresh `cordova create fooApp` project and attach to that for debugging?

**Comment by Tsmith18256** [comment]
Okay yeah I just created a new Ionic app (forgot to mention in my original post that it was Ionic) with `ionic start myApp tabs` and tried it out. It worked perfect on that app so it must be Crosswalk.

I don't know why removing Crosswalk wasn't helping before, unless there was some caching or something causing it to still use it. 

Thanks for your help!

**Comment by danieltorrecillas** [comment]
> If you are using crosswalk then the currently published version of the extension doesn't work for debugging android

Is this still correct? That is, does v1.3.5 work with apps using Crosswalk?
