### ISSUE TITLE
Unable to find a .app or a .ipa to install 

### ISSUE THREAD

**Issue by jlsuarezs** [Microsoft/vscode-cordova#205]
VSCode Version: 1.7.1
OS Version: macOS Sierra 10.12.1
XCode: 8.1 (8B62)

Before install the last version of Xcode, its was working and I could debug my ionic 2/cordova app, but now I am alwasy getting this error:
[cordova-debug-adapter] Error: Unable to find a .app or a .ipa to install

Please, any help?
Thanks.

**Comment by MSLaguana** [comment]
What are you targeting, device or simulator? Xcode 8 changed some parts of how device builds work, and so you now must specify a `developmentTeam` in `build.json`, and either update your version of the iOS platform or add a hook: https://dpogue.ca/articles/cordova-xcode8.html

If you haven't done that, and you are targeting a device, then I believe that the build is failing and so there is no compiled application to install on the device and debug.

**Comment by brassier** [comment]
I am having this same problem when targeting a device.  I'm able to build & deploy to the device via Xcode without issue.

**Comment by MSLaguana** [comment]
Does `ionic build ios --device` also successfully build your app?

**Comment by jlsuarezs** [comment]
Exactly, I am building targeting a device. And yes, I can build & deploy to the device via xcode without any issue too.

ionic build ios --device   >>> It's not successful, while ionic build ios yes.

**Comment by MSLaguana** [comment]
That's the issue then: when building in vscode we use ionic/cordova CLI to build the app. That step is failing for you for some reason when building for a device. What error does it give? I suspect it will be something to do with signing or development teams.

**Comment by jlsuarezs** [comment]
There are no errors, its just incomplete :(

I will to check what you've said before...

**Comment by vladimir-kotikov** [comment]
@jlsuarezs, this is fairly outdated issue, so I'll close this for now, but feel free to reopen in case if you're still having any problems w/ building for iOS
