### ISSUE TITLE
Error in Toggle Developer Tools

### ISSUE THREAD

**Issue by julientype** [Microsoft/vscode-cordova#209]
Help/Toggle Developer Tools/
vs debuger opens and i get...error
conflic detected, commands 'workbench.action.run cannot be triggered by ctrl+f5 due to cordova.run

how do i fix this bug???? or will you create a patch.... its a shortcut conflict
============
web host ceo julien
http://3taccont.com

**Comment by iTOYS** [comment]
It's not a bug. 
We're overriding default VSCode command "Start Without Debugging" to our "Cordova.Run" command
