### ISSUE TITLE
Run on android emulator error

### ISSUE THREAD

**Issue by mysterytony** [Microsoft/vscode-cordova#210]
When I attempt to run on android emulator, vscode gives me:

```
error: cannot bind listener: Address already in use
Error running 'adb -s emulator-5554 forward tcp:9222 localabstract:webview_devtools_remote_3517'
```

Regards

**Comment by MSLaguana** [comment]
This sounds like your port 9222 is already in use by something else. Do you have other debugging sessions open, or other instances of chrome which are configured to be debuggable? For a quick check, in your `launch.json` you can modify the `"port": 9222` to another (not-in-use) value and see if that resolves the issue for you.

**Comment by mysterytony** [comment]
Is this port number arbitrary?

**Comment by MSLaguana** [comment]
Yes, it just has to be a free port that we will use to debug the app.

**Comment by mysterytony** [comment]
It works. Thank you.
