### ISSUE TITLE
Android debug fails with "Permission denied" on Android 7

### ISSUE THREAD

**Issue by corran2go** [Microsoft/vscode-cordova#217]
On Android 7 the attempt to use the debugger on a actual device fails with:

ls: /proc/12309/fd: Permission denied
Error running 'adb -s xxxxxxxxxx shell ls -l /proc/12309/fd'

Running 'adb -s xxxxxxxxxx shell ls -l' on the cmd works as expected.

See http://stackoverflow.com/a/38728738

**Comment by MSLaguana** [comment]
This looks like the same issue as #215 which should be fixed in the next release.

**Comment by MSLaguana** [comment]
I have just published a new release with a fix for this. Please update and try again.
