### ISSUE TITLE
Support "skipFiles" options in launch.json to avoid debugging certain files/directories

### ISSUE THREAD

**Issue by gianpaj** [Microsoft/vscode-cordova#219]
Also called "just my code"

https://code.visualstudio.com/Docs/editor/debugging#_just-my-code-skipfiles

**Comment by MSLaguana** [comment]
This should be supported once we upgrade to the newest vscode-chrome-debug-core I believe.

**Comment by iTOYS** [comment]
Implemented in #328
Added 'runArguments' options

**Comment by hqp6684** [comment]
@iTOYS if is it possible, can you please give me an example for skipping files ? 
This is what I have but it doesn't seem to work
`{
  "configurations": [
    {
      "name": "Run android|ios on device|emulator",
      "type": "cordova",
      "request": "launch",
      "platform": "android",
      "target": "emulator",
      "sourceMaps": true,
      "cwd": "${workspaceRoot}",
      "livereload": true,
      // "ionicLiveReload": true
      "runArguments": ["skipFiles", "core.es5.js"]
    }
  ]
}
`

**Comment by svekl** [comment]
Hi @hqp6684,
looks like some misunderstanding occurred, you can pass any parameters to chrome debugger, including `skipFiles`, you might be confused of lack of autocomplete for this parameter, we will add it in future version, but it will be passed to chrome debugger anyway. So your configuration might look like that
```
    {
      "name": "Run android|ios on device|emulator",
      "type": "cordova",
      "request": "launch",
      "platform": "android",
      "target": "emulator",
      "sourceMaps": true,
      "cwd": "${workspaceRoot}",
      "livereload": true,
      // "ionicLiveReload": true
      "skipFiles": ["core.es5.js"]
    }
```

not sure if you need to add path to `core.es5.js` or not, depends on your project configuration, but chrome debugger uses glob pattern for `skipFiles` so you may use it if you need.
