### ISSUE TITLE
brew installation error

### ISSUE THREAD

**Issue by jdnichollsc** [Microsoft/vscode-cordova#221]
Hi guys,

I'm trying to install the packages using brew, but the following errors appear:

```cmd
bash-3.2$ brew install ideviceinstaller ios-webkit-debug-proxy
Error: You must `brew link libtasn1` before ideviceinstaller can be installed
Error: You must `brew link libtasn1` before ios-webkit-debug-proxy can be installed
```

Regards, Nicholls

**Comment by MSLaguana** [comment]
Have you tried `brew link libtasn1`?

**Comment by vladimir-kotikov** [comment]
Closing this due to lack of response. @jdnichollsc, if you're still having problems with this, feel free to reopen. Thanks.
