### ISSUE TITLE
Breakpoints are not hit in Ionic 1.x app

### ISSUE THREAD

**Issue by sryze** [Microsoft/vscode-cordova#225]
Hello, I'm using VS Code's debugger for the first time and having an issue with breakpoints. For some reason none of them are hit during app execution, and additionally they are shown as "unverified".

I'm using the "Run Android on emulator" launch configuration (generated by VS Code, didn't change it).

I'm using gulp to combine all JS files into one giant app.min.js file and it contains an inline sourcemap. Could it be related to the issue?

Version info:

```
Ionic version: 1.3.1
Ionic CLI version: 2.1.17
Extension version: 1.2.5

VS Code:
Version 1.8.1
Commit ee428b0eead68bf0fb99ab5fdc4439be227b6281
Date 2016-12-19T14:49:23.350Z
Shell 1.4.6
Renderer 53.0.2785.143
Node 6.5.0
```

**Comment by MSLaguana** [comment]
We don't currently support inline source maps, the source map must specify how to find the original sources so we know how to map a breakpoint in `foo.ts` to `bundle.js` and vice versa.

**Comment by sryze** [comment]
Thanks, didn't know that. Where should I put the *.map file(s)? I converted my gulpfile to produce external source maps and output app.min.js.map next to my app.min.js file (where all my JS code is after build) like this:

```js
gulp.task('js', () => {
  return gulp.src('src/js/**/*.js')
    .pipe(sourcemaps.init())
    .pipe(ngAnnotate().on('error', gutil.log))
    .pipe(concat('app.min.js').on('error', gutil.log))
    .pipe(sourcemaps.write('.').on('error', gutil.log))
    .pipe(gulp.dest('www/js').on('error', gutil.log))
});
```

however, I'm still having trouble getting it to work and breakpoints are marked as unverified nevertheless. Any ideas what might be wrong?

**Comment by sryze** [comment]
Forgot to mention: setting breakpoints inside app.min.js doesn't work either 😞  (it's not minified, just concatenated).

Based on other people's numerous issues I came across this seems to be a problem with debugging JS in VS Code in general, not just Cordova/Ionic.

I was really hoping I could finally debug Ionic apps without console.log() or manually opening up Chrome dev tools each time with this extension. There isn't any alternative right now.

**Comment by vladimir-kotikov** [comment]
@sryze, sorry for late response. Are you still experiencing the problem?

**Comment by jmargolese** [comment]
I am experiencing the problem of not hitting breakpoints in debug using Ionic 1 with VS Code 1.12.1

I'm unclear on how to setup the source maps (which I presume is the problem).  Is there any documentation or references?

thx

**Comment by iTOYS** [comment]
Checked with default `ionic start IonicApp1 tabs --type=ionic1`
All works fine.
Closing now! Feel free to reopen if you still have this issue
