### ISSUE TITLE
Command 'cordova.simulate.ios' not found

### ISSUE THREAD

**Issue by tjvg91** [Microsoft/vscode-cordova#226]
Hi,

I get this error! What should I do?

![screen shot 2016-12-31 at 9 52 04 am](https://cloud.githubusercontent.com/assets/5625925/21575163/ee805018-cf3e-11e6-9936-68e3d295f286.png)

**Comment by MSLaguana** [comment]
Apologies for the delay in responding. What caused this to happen? Did you explicitly run a command through the cmd-p menu? Did this happen as part of an f5?

**Comment by vladimir-kotikov** [comment]
Closing due to lack of response. @tjvg91, if you're still experiencing this, please reopen this one and provide additional information, as asked above. Thanks.
