### ISSUE TITLE
Breakpoints are not hit in Ionic 2.x app

### ISSUE THREAD

**Issue by gtzinos** [Microsoft/vscode-cordova#228]
Hello, 
I found an issue during debugging. Breakpoints are not hit when my code is inside an ionic custom event like ionViewWillEnter which runs when the page is about to enter and become the active page.

**Comment by jmesa-sistel** [comment]
Have you added
```
"config": {
    "ionic_bundler": "webpack",
    "ionic_source_map": "source-map"
  },
```
in `package.json` to be able to debug properly ?

**Comment by gtzinos** [comment]
I will check it thank you. This was documented ?

**Comment by vladimir-kotikov** [comment]
@gtzinos this is not yet documented, though this advice helped a lot of people to resolve debugging issues w/ Ionic2. We'll do some additional verification and add this to README

**Comment by vladimir-kotikov** [comment]
Hmm... Not sure if it still needs to be added to `package.json`. According to [Ionic docs](https://github.com/driftyco/ionic-app-scripts/blob/28036c5c32780112bcaafc2e6edcf2cc67a58010/README.md#overriding-config-values) `ionic_bundler` is already defaults to `webpack` and `ionic_source_map` doesn't even exist - there is `ionic_source_map_type` property that has `source-map` as default, so I guess that debugging should work now out of the box with latest Ionic.

**Comment by vladimir-kotikov** [comment]
@gtzinos, @jmesa-sistel, I've just verified that debugging works just fine without any additional setup (in particular breakpoints in `ionViewWillEnter` are working), so I'll close this, but feel free to reopen if you still experience any problems w/ debugging.

**Comment by jmesa-sistel** [comment]
Since version 0.0.47 (2016-12-12) [Changelog](https://github.com/driftyco/ionic-app-scripts/blob/28036c5c32780112bcaafc2e6edcf2cc67a58010/CHANGELOG.md) they have changed ionic_source_map_type to source-map instead eval.
I discussed with them a [few times](https://github.com/driftyco/ionic-app-scripts/issues/289#issuecomment-261067646) but with no luck. I guess that they had a lot of reports about debugging and they changed it finally.

**Comment by Rainson12** [comment]
debugging doesnt work again, it hits the breakpoint but all variables are empty when watching the stack im  getting "ReferenceError: navCtrl is not defined
    at eval (eval at <anonymous> (http://localhost:4400/build/main.js:63581:5), "
