### ISSUE TITLE
"Run Android on device" runs into endless loop

### ISSUE THREAD

**Issue by Cedware** [Microsoft/vscode-cordova#229]
Hello.
If I choose the debug option "Run Android on device", the plugin seems to get stuck in a loop.
The terminal prints "Launching for android (This may take a while)...", after a while the terminal relaunches with the same message and each time a "strange" log-file appears in the project root with the following filename:
`npm-debug.log.{a-number}`
Those log file have no content.
If i launch the application with:
`cordova run android`
or
`ionic run android`
I can use "attach to running android device" and everything works fine.

**Comment by MSLaguana** [comment]
Can you please copy the exact output of the debugging console when this is happening at some point? There is one time that we attempt to npm install something, and I'd like to see if that is what's happening here.

**Comment by HugoMarteau** [comment]
![image](https://cloud.githubusercontent.com/assets/8122998/22365360/5150dcba-e477-11e6-8916-1bdffea30567.png)

The debbug message in the console. nothing more or less.
Just disapearing and appearing

**Comment by Cedware** [comment]
I'm sorry, I totally thought, I had answered your question.
But HugoMarteau hit the point, the Console doesn't show anything beside the "Launching for android" Text.
If you ne more information, let me know

**Comment by vladimir-kotikov** [comment]
The fix has been merged into master branch and will be available in the next release. Closing this fo now.
