### ISSUE TITLE
Duplicate declare in ts  ...lol ...error..nice code job

### ISSUE THREAD

**Issue by julientype** [Microsoft/vscode-cordova#231]
/** Apache Cordova instance */
declare var cordova: Cordova;

declare module 'cordova' {
    export = cordova;
}

====== whats up with that...... ohhh 2 identifires.... debug inserts the code files into the project..... shows up as error.....  create a new project.... vscode injects the files

**Comment by MSLaguana** [comment]
Can you please clarify what you are saying?

The definition file that we add declares cordova in two different contexts: once as a global object, and once as a module which may be `require`d (It's arguable that we shouldn't do the latter, but we are using the community contributed cordova typings). These are not conflicting declarations, and should not cause an error on their own.

Are you working on a typescript project, or have you added your own typings to the project? Where does this error show up for you?

**Comment by julientype** [comment]
when i hit the debuger it adds the files...... its not something i control......
it show up as an error in the blue status bar..... 2 identifires,,,,, error
..... in the tb file....  your code not my code.....
/** Apache Cordova instance */
declare var cordova: Cordova;<-----declare 1

declare module 'cordova' {<-------declare 2
export = cordova;<---------error
}

**Comment by vladimir-kotikov** [comment]
@julientype, I confirm that I can see the same error when I have `cordova.d.ts` opened in separate editor tab. However this syntax is a perfectly valid typescript (see https://www.typescriptlang.org/docs/handbook/modules.html, section named 'export = and import = require()'). Also despite of highlighting this as an error completions continue to work just fine for both cordova as a global object and imported module.

So you could probably just safely ignore this error, or, if you really want to get rid of it - just change `export = cordova` to `export default cordova`.
