### ISSUE TITLE
Breakpoints not reloaded properly in ionic2 with livereload attaching to a device

### ISSUE THREAD

**Issue by jmesa-sistel** [Microsoft/vscode-cordova#235]
Create a simple ionic2 project `ionic start cutePuppyPics --v2` with a button and onclick event
`<button ion-button (click)="Click()">Test</button>`
```
 Click() {
    console.log('Test');
  }
```

Add a break point in `console.log('Test');` line

Add 
```
"config": {
    "ionic_bundler": "webpack",
    "ionic_source_map": "source-map"
  },
```
in `package.json` to be able to debug properly.

run project with LiveReload: `ionic run android -l`
PS: Same problem using `Serve to the browser (ionic serve)`
Wait to the device to get the project loaded then  `Attach to running android on device` from debug tab
Press button test on project.
Everything works fine. The breakpoint works fine. Now press continue. 
Now add a line before the breakpoint, example:

```
 Click() {
    let x = ' Test';
    console.log(x);
  }
```
Save the project, wait for the device to be ready. 
Now the breakpoints go mad. You will loose the breakpoints.
If you delete and create breakpoints again everything works. 

The workaround is: disconnect -> save -> wait device be ready -> attach again

PS
Same problem using `Serve to the browser (ionic serve)`

**Comment by MSLaguana** [comment]
This sounds like it might need some additional support from the chrome debugger that we depend on. @roblourens, any idea what the issue here might be? Does vscode-chrome-debug-core support live-reload of scripts?

**Comment by roblourens** [comment]
Thought I had fixed this at some point, I'll take another look

**Comment by roblourens** [comment]
I just made a simple fix to use the correct sourcemap after reloading. Stepping should work once this is adopted, although breakpoints may still shift. I guess the debug adapter sort of doesn't know which BP line number should be associated with which instance of the page. Maybe we will need to save the original line number for the BP and try to reset it when the script loads a second time.

**Comment by MSLaguana** [comment]
Great; this should be fixed once we take an updated dependency then.

**Comment by jmesa-sistel** [comment]
Any news? 
Can I test @roblourens fix?

**Comment by jmesa-sistel** [comment]
@MSLaguana  news?

**Comment by vladimir-kotikov** [comment]
@MSLaguana, @roblourens, do you guys happen to remember which version of chrome debug core has the aforementioned fix? We've recently upgraded to 3.12 (in #242) - is that enough?

**Comment by MSLaguana** [comment]
I believe the relevant commit was https://github.com/Microsoft/vscode-chrome-debug-core/commit/107466fe55505e917b2619dfa84700faadea1d65 and so it should be in 3.12

**Comment by vladimir-kotikov** [comment]
Thanks, @MSLaguana. So i'll close this since we've already upgraded chrome-debug-core and just need to release updated extension
