### ISSUE TITLE
Unable to debug ionic 2 app remotely on my android device

### ISSUE THREAD

**Issue by sgadekar81** [Microsoft/vscode-cordova#236]
I am trying to debug ionic app using cordova tools plugin, I have tried reinstalling plugin for several times, on reinstalling first time it works and gives following error since i am new, can any one help?

![image](https://cloud.githubusercontent.com/assets/14721916/22403645/03b755fa-e644-11e6-9daa-0bf0bc2aa2e5.png)

![screenshot_2017-01-29-16-58-35](https://cloud.githubusercontent.com/assets/14721916/22403694/4d921b78-e645-11e6-9257-58077c1f45c8.png)

**Comment by jmesa-sistel** [comment]
add
```
"config": {
    "ionic_bundler": "webpack",
    "ionic_source_map": "source-map"
  },
```
in package.json to be able to debug properly 
Then execute in console: `ionic run android -l`
When the app is running in the device, then click to debug in VSCode using the option:
`Attach to running android on device`
Now you can debug properly and livereload is working, there is only one bug about breakpoints: [issue 235](https://github.com/Microsoft/vscode-cordova/issues/235)

**Comment by sgadekar81** [comment]
thanks, now i am able to debug, thanks for suggestion

**Comment by matrosov-nikita** [comment]
@sgadekar81, what version of Node are you running on? I was able to reproduce this bug using node 6.3.0, but after upgrading to 6.7.0 the problem has disappeared.

**Comment by sgadekar81** [comment]
node v7.0.0;
npm 3.10.8

**Comment by vladimir-kotikov** [comment]
This seems to has been resolved, so closing this. @sgadekar81, feel free to reopen if you're still having any issues. Thanks
