### ISSUE TITLE
I cannot find the Cordova debug configuration in Visual Studio Code

### ISSUE THREAD

**Issue by airimiea** [Microsoft/vscode-cordova#238]
I am working on a Windows 10 Home Edition os. I have installed Visual Studio Code Version 1.9.0 and added to it the Cordova Tools 1.2.6. I hava a fresh Ionic 2 blank project and I am running it with  ionic run android --device or emulating it with ionic emulate android. I want to test debugging from Visual Studio Code but when I go to Debug/Add Configuration I don't see a Cordova option. What am I missing?

**Comment by MSLaguana** [comment]
Do you already have a `.vscode/launch.json` in your project? If you do not, then are you saying that when you try to follow the instructions at https://github.com/Microsoft/vscode-cordova#choose-the-cordova-debug-environment the drop-down list of suggestions does not include cordova?

**Comment by airimiea** [comment]
I have a .vscode/launch.json file. The content looks like this:

```
{
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [

        {
            "name": "Launch Chrome (with userDataDir)",
            "type": "chrome",
            "request": "launch",
            "url": "http://localhost:8100",
            "sourceMaps": true,
            "webRoot": "${workspaceRoot}/www",
            "userDataDir": "${workspaceRoot}/.vscode/chrome"
        }
    ]
}

```

If I try to follow the instructions that you pointed out there is no Cordova option. When I click the configure gear icon launch.json opens and at the bottom right corner I have a blue button Add Configuration... If I press this button I see a couple of Chrome configurations, a bunch of nodejs configurations and a vs code extension development configuration.

**Comment by AlGantori** [comment]
One way to get the steps to work and see the Cordova option, one counter-intuitive :) approach is too delete launch.json, don't worry you have it saved above :)

**Comment by airimiea** [comment]
If I delete launch.json then when I click the configure grear icon a new launch.json is automatically created with the following content:

```
{
    // Use IntelliSense to learn about possible Node.js debug attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "program": "${file}",
            "cwd": "${workspaceRoot}",
            "outFiles": []
        },
        {
            "type": "node",
            "request": "attach",
            "name": "Attach to Process",
            "port": 5858,
            "outFiles": []
        }
    ]
}
```

Again Cordova is not available as an option.

**Comment by jmesa-sistel** [comment]
Have you installed the codova plugin?

**Comment by airimiea** [comment]
The extension is installed and enabled. I have disabled and re-enabled it to verify this.

**Comment by SamArmand** [comment]
I have the same issue.

**Comment by matrosov-nikita** [comment]
@airimiea, @SamArmand, it's new feature of VSCode which automatically chooses a debug environment  depending on the active file (https://code.visualstudio.com/updates/v1_9#_automatically-choosing-debug-environment). Could you please try to close your files in VSCode and choose configuration again?

**Comment by SamArmand** [comment]
@matrosov-nikita I just tried it. It doesn't make a difference. Thanks for looking into it!

**Comment by fredgalvao** [comment]
@matrosov-nikita That worked, thanks. Closing all files in the workspace, restarting vscode, and clicking `Configure or fix "launch.json"` fixed it for me. I'm on vscode 1.9.1, xubuntu, with all extensions up-to-date.

**Comment by matrosov-nikita** [comment]
@SamArmand, thanks for trying. Did you remove existing `launch.json` before choosing configuration?

**Comment by NuSkooler** [comment]
Thought I'd add my 2 cents to this:
I had the same issue with Cordova not showing up on the "gear" icon at all. Closing the folder/project, removing `.vscode`  and re-launching did not work.

I had to close all open file/tabs *and* close the folder/project, exit VSCode, remove `.vscode` then re-launch and re-open the folder. From there the option appeared in the drop down.

**Comment by SamArmand** [comment]
@NuSkooler I confirm that your solution works perfectly. Thanks!

**Comment by nevillekatila** [comment]
Yes, the solution provided works.

**Comment by airimiea** [comment]
@NuSkooler the solution works, thank you!

**Comment by mumairofficial** [comment]
Delete existing **launch.json** file from **.vscode** directory and go to **Debugger** and click on **setting icon** it will show you installed debuggers and select one of them...

cheers :)

**Comment by chitgoks** [comment]
That solution does not work anymore at this time.
