### ISSUE TITLE
Start Ionic2 project using Cordova Tools and VS Code

### ISSUE THREAD

**Issue by nebojsakg** [Microsoft/vscode-cordova#245]
I successfully created Ionic 2 project using Ionic CLI, then added android platform using cordova. Here are commands I used:

- ionic start TestProject tabs --v2
- cd TestProject
- cordova platform add android

Everything passed Ok and project was created. Then I started VS Code with command

- code .

VS Code started and loaded newly created project. I set Cordova for debugging environment and started project as "Simulate Android in browser".

Chrome was started but application was not loaded. Instead I got only white page with text Not Found.

Also www folder in my project was empty, nothing was copied to it.

If I try to run application as "Serve to the browser (ionic serve)", application is normally started and files are copied to www folder. Also I was able to start and debug application on Android device.

Any idea why "Simulate Android in browser" didn't work?

**Comment by MSLaguana** [comment]
I believe that this is because for "simulate in browser" scenarios, we do `cordova/ionic prepare` to copy the contents of www into the platform without doing a full build because we don't care about the android / iOS native code. However, ionic projects have switched to only placing things in www after actually building (or as part of ionic serve).

**Comment by nebojsakg** [comment]
Thanks for fast reply.. What can I change to make this work? Thanks

**Comment by MSLaguana** [comment]
You need to make sure to run `node_modules/.bin/ionic-app-scripts build` prior to trying to run your app. Probably the simplest way to do this is to set up a "task" in vscode following https://code.visualstudio.com/Docs/editor/tasks which has `"isBuildTask": true` set, which will cause it to run every time you hit f5 or start debugging.

**Comment by nebojsakg** [comment]
I did something similar to your suggestion and it worked. I created a task and added "preLaunchTask" in launch.json where I called task I previously created.

Thanks for help..
