### ISSUE TITLE
[cordova-tools] Error processing "launch": {_stack}

### ISSUE THREAD

**Issue by jlsuarezs** [Microsoft/vscode-cordova#246]
Hi,

I am getting this error after the last update everytime I try to run my app in ios:
[cordova-tools] Error processing "launch": {_stack}

Please, any help?

**Comment by vladimir-kotikov** [comment]
@jlsuarezs, is there anything logged to debug console? I was able to repro the issue, but I'm not sure if you're having the same problem.

In my case `ideviceinstaller` was failing to install app on device with the following message: "Could not connect to lockdownd. Exiting." yet it was exiting with error code 0. When the error code is 0 we think that execution succeeded and continue with running "installed" app and end up with popup, saying "[cordova-tools] Error processing "launch": {_stack}" and "Unable to find developer disk image" error message in debug console.

To resolve the problem I had to install `ideviceinstaller` from HEAD as described here: https://github.com/libimobiledevice/ideviceinstaller/issues/47#issuecomment-251384892

**Comment by jlsuarezs** [comment]
Huuumm, thank you for your help.

Now I can execute the app, but still can't debug:

** EXPORT SUCCEEDED **
Installing app on device
Launching app
Timeout launching application. Is the device locked?

And the device is not locked...

Any thoughts?

Thanks again!

**Comment by vladimir-kotikov** [comment]
Not sure, but it looks like there are still some problems w/ libimobiledevice. Could you please try running the following commands one by one to see if there are any errors (this is exactly what our extension tries to execute to run app after build):

1. `ideviceinfo -s -k ProductVersion`
1. `xcrun -sdk iphoneos --show-sdk-platform-path`
1. `find <sdk_path> -path *<version>* -name DeveloperDiskImage.dmg` (where `<version>` is the output of the first command and `<sdk_path>` - of the second and typically should be something like `/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform`)
1. `ideviceimagemounter <path>`, where `<path>` is the output of previous command
1. `idevicedebugserverproxy 9221`

If all these commands succeed, then there is probably some miscommunication between our extension and debug server which would require adding some logging to installed extension.

**Comment by vladimir-kotikov** [comment]
@jlsuarezs, any updates? Are you still seeing this?

**Comment by dually8** [comment]
I'm seeing this, myself. Getting `Timeout launching application. Is the device locked?` and that popup: `Error processing "launch": {_stack}`. I ran the commands you posted, @vladimir-kotikov, and stopped at 3. Here's what I found.
![error](https://cloud.githubusercontent.com/assets/6304040/23711229/43c4508c-03ed-11e7-8364-0d8be222fb0a.png)
Apparently, there's no 10.2.1 folder. I'd be happy to help debug this further if someone tells me what they need from me.

**Comment by TeliNatsis** [comment]
Hi -

I am facing the same problem, I followed the above steps and on step 3 i ran the following and it finds nothing.

find /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform -path *10.2.1* -name DeveloperDiskImage.dmg

Any help would be appreciated.

Thanks for your time in advanced. 

Regards,
Teli

**Comment by urteli** [comment]
Hi 

I forgot to mention my environment 

Below is my environment.
OS X EL CAPITAN v10.11.16
Node v7.6.0
Cordova –v 6.5.0
Ionic 2 – v 2.2.1
VS code – 1.10.2

Thanks,
Teli

**Comment by JKeetman** [comment]
I'm also facing this issue. I'm also getting a **ERROR: Could not connect to lockdown, error code -5**. with ideviceimagemounter.

Kind regarts,

john Keetman

**Comment by vladimir-kotikov** [comment]
Thanks for updates! I think I've found where the issue is (at least for iOS 10.2.1) - it looks like the app is responding a bit different to GDB commands we're using to launch it and we're not recognizing that response. I'll send a PR shortly.

@JKeetman, as for your problem, this is a known issue w/ `ideviceinstaller` - you'd need to update it as mentioned in https://github.com/Microsoft/vscode-cordova/issues/246#issuecomment-281091543 (or just simply run `brew uninstall --ignore-dependencies libimobiledevice && brew install --HEAD libimobiledevice` if you're using brew)

**Comment by vladimir-kotikov** [comment]
Ok, sent a PR. Would appreciate if someone could test it and let me know whether it works.

**Comment by urteli** [comment]
Hi -

Can you tell me the steps need to install the PR? Thanks, Then I will test it right now.

Thanks,
Teli

**Comment by vladimir-kotikov** [comment]
Hmm.. You'll need to clone this repo, then do `npm install && typescript -p .` inside the cloned directory. After that you'll just need to create a symlink inside your extensions directory (this is `~/.vscode/extensions` on Mac or `%USERPROFILE%\.vscode\extensions`) pointing to the location, where you built the extension, e.g. `ln -s ~/repos/vscode/vscode-cordova vsmobile.cordova-tools-dev` or `mklink /j vsmobile.cordova-tools-dev D:\projects\vscode\vscode-cordova` (Mac and Windows correspondingly)

**Comment by urteli** [comment]
Hi -

Thanks for the info I can get up to ~/.vscode/extensions part. I cloned the repo and used npm install && typescript -p. changed directories to ~/.vscode/extensions then I am lost. 

Where do i find the vscode-cordova i am on a mac. I did a sudo find / -name "vscode-cordova" found nothing also did a search for just vscode found nothing useful. 

The following below is not as clear. Can you further explain the below. Thank you.

where you built the extension, e.g. ln -s ~/repos/vscode/vscode-cordova vsmobile.cordova-tools-dev or mklink /j vsmobile.cordova-tools-dev D:\projects\vscode\vscode-cordova (Mac and Windows correspondingly)

Upd.: Or you can just find corresponding JS files inside the extension directory (i.e. ~/.vscode/extensions/vsmobile.cordova-tools-1.2.6) and apply the changes from PR manually

Thanks for your time,
Regards,
Teli

**Comment by vladimir-kotikov** [comment]
@urteli, see below for complete instructions:
```
cd ~ && git clone https://github.com/Microsoft/vscode-cordova
cd vscode-cordova && npm i && tsc -p .
cd ~/.vscode/extensions
rm -rf vsmobile.cordova-tools-* && ln -s ~/vscode-cordova vsmobile.cordova-tools-dev
```
and then restart VSCode.

**Comment by urteli** [comment]
Hi -

I just followed the above steps. I now receive this error.

Debug adapter process has terminated unexpectedly.

I will not be available most of the day until tonight. If you can suggest a fix in the next 10 min I can try it other wise it will have to wait till I return.


Thanks for your help so far,

Regards,

Teli
