### ISSUE TITLE
Not debugging with target iOS 10

### ISSUE THREAD

**Issue by pcecchetti** [Microsoft/vscode-cordova#247]
After 2 days fighting with cordova extension and ionic with iOS 10 simulator, I tried  as "target": "iPhone-6s, 9.3" and the debugger works. 
Is there a way to have vscode-cordova working with debugger using iOS 10 targets?

**Comment by matrosov-nikita** [comment]
Hi @pcecchetti , could you please provide some additional info about your issue: 
 - what version of extension are you using (there is a known bug with iOS10 in pre-1.2.6)
 - can you see any errors in debug console

Could you also paste here your ios launch configuration from `<PROJECT_PATH>/.vscode/launch.json`?

**Comment by pcecchetti** [comment]
Hi @matrosov-nikita  and thanks for the answer.
version is 1.26

No errors in debug

Launching for ios (This may take a while)...
Launching app (This may take a while)...
> ionic-hello-world@ ionic:build /Users/paolo/IonicProjects/ionicSample
> ionic-app-scripts build "ios"
[15:32:35]  ionic-app-scripts 1.1.0 
[15:32:35]  build dev started ... 
[15:32:35]  clean started ... 
[15:32:35]  clean finished in 6 ms 
[15:32:35]  copy started ... 
[15:32:35]  transpile started ... 
[15:32:38]  transpile finished in 2.51 s 
[15:32:38]  preprocess started ... 
[15:32:38]  preprocess finished in less than 1 ms 
[15:32:38]  webpack started ... 
[15:32:38]  copy finished in 2.65 s 
[15:32:44]  webpack finished in 5.91 s 
[15:32:44]  sass started ... 
[15:32:44]  sass finished in 853 ms 
[15:32:44]  postprocess started ... 
[15:32:44]  postprocess finished in less than 1 ms 
[15:32:44]  lint started ... 
[15:32:44]  build dev finished in 9.31 s 
[15:32:46]  lint finished in 1.55 s 
Building project  : /Users/paolo/IonicProjects/ionicSample/platforms/ios/ionicSample.xcodeproj
	Configuration : Debug
	Platform      : emulator

then the log from xcode building

Attaching to ios
Configuring debugging proxy
Attaching to app.

launch.json for the iOS emulator
        {
            "name": "Run iOS on simulator",
            "type": "cordova",
            "request": "launch",
            "platform": "ios",
            "target": "iPhone-6s, 10.2",
            "port": 9222,
            "sourceMaps": true,
            "cwd": "${workspaceRoot}",
            "ionicLiveReload": false,
            "attachAttempts": 10,
            "attachDelay": 15000
        },

with 
"target": "iPhone-6s, 9.3", breakpoints work.

**Comment by MSLaguana** [comment]
If the issue that you see is breakpoints not being hit in iOS 10, then I believe I know the cause: iOS 10 changed the webview so that breakpoints only work if the debugger explicitly enables them (Previously breakpoints were enabled by default). I thought that we had made that change, but I may have confused that with a similar fix elsewhere.

**Comment by pcecchetti** [comment]
Yes @MSLaguana.
Is it then something you have to fix in the plugin?
Thanks for the help.

**Comment by MSLaguana** [comment]
Yes, it's a change in the debugging protocol.

For a workaround, if you open up Safari and go to the developer menu, if you attach to the app in the simulator then that will enable breakpoints, and you can use either safari's devtools or you can re-attach with VSCode and continue debugging. Unfortunately this will need to be done each time you restart the app.

**Comment by pcecchetti** [comment]
I'll stay with iOS 9 for now then. Thanks

**Comment by jainpiyushb** [comment]
@MSLaguana @vladimir-kotikov Thank you for the workaround which enables debugging on iOS 10. Any idea on when it would be fixed as it is getting tedious to develop on iOS 10? 
Thanks.
