### ISSUE TITLE
'Ionic: Build' and 'Ionic: Run' commands should allow user to specify platform

### ISSUE THREAD

**Issue by vladimir-kotikov** [Microsoft/vscode-cordova#250]
Curently all contributed commands are just invoking corresponding Cordova/Ionic command without giving use a choice which platform to build/run for. This may lead to odd problems, e.g.:
1. when there are multiple platforms added to the project, running them all (as "Ionic/Cordova: Run" behaves currently) ususally doesn't make sense
1. when iOS platform is added to the app and user tries to call `Ionic: Build` on Windows machine this leads to an error “You cannot run iOS unless you are on Mac OSX”

To choose platform, there should probably be a dropdown, similar to command palette, that would allow to choose platform to run/build. Also it'd be nice to have an ability to save the default value or pick it from workspace configuration.

**Comment by iTOYS** [comment]
Implemented in #328
