### ISSUE TITLE
Detect chromium-browser vs chrome browser on linux, when creating launch.json

### ISSUE THREAD

**Issue by dotnetCarpenter** [Microsoft/vscode-cordova#273]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:01:14.464Z)
- OS Version: Linux x64 4.4.0-75-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|project-manager|alefragnani|0.15.0|
|gitignore|codezombiech|0.5.0|
|git-extension-pack|donjayamanne|0.1.2|
|githistory|donjayamanne|0.2.0|
|vscode-coffeescript-preview|drewbarrett|0.1.4|
|gitlens|eamodio|3.4.5|
|vscode-great-icons|emmanuelbeziat|1.1.52|
|php-intellisense|felixfbecker|1.2.1|
|beautify|HookyQR|1.0.2|
|vscode-apache|mrmlnc|1.1.1|
|ejs-language-support|QassimFarid|0.0.1|
|spellchecker|swyphcosmo|1.2.13|
|ayu|teabyii|0.2.1|
|cordova-tools|vsmobile|1.2.7|
|vscode-open-in-github|ziyasal|1.2.5|;

---

Steps to Reproduce:

1. Click on the _Debug_ icon (Ctrl + Shift + D)
2. Click on the cog (fix/open `launch.json`)

```json
{
      "name": "Simulate Android in browser",
      "type": "cordova",
      "request": "launch",
      "platform": "android",
      "target": "chrome",
      "simulatePort": 8000,
      "livereload": true,
      "sourceMaps": true,
      "cwd": "${workspaceRoot}"
    }
```

Should be (if chrome is not installed but chromium-browser is):
```json
{
      "name": "Simulate Android in browser",
      "type": "cordova",
      "request": "launch",
      "platform": "android",
      "target": "chromium-browser",
      "simulatePort": 8000,
      "livereload": true,
      "sourceMaps": true,
      "cwd": "${workspaceRoot}"
    }
```

Can be detected via: `which chrome` and `which chromium-browser` **OR** `command -v chrome` and `command -v chromium-browser`.

**Comment by dotnetCarpenter** [comment]
This should probably not be implemented before #274 is fixed.

**Comment by vladimir-kotikov** [comment]
@dotnetCarpenter given that with #295 you can easily set up either chrome or chromium as a browser of your choice I think this can be closed.

**Comment by vladimir-kotikov** [comment]
If you feel that automatic detection is still important - feel free to reopen
