### ISSUE TITLE
Error running 'ideviceinstaller -i 

### ISSUE THREAD

**Issue by aocarmo** [Microsoft/vscode-cordova#275]
When I do deploy run ios device, the error appears: **
Installing 'com.ionicframework.ampebapp914475'
 - CreatingStagingDirectory (5%)

 - ExtractingPackage (15%)

 - InspectingPackage (20%)

 - TakingInstallLock (20%)

 - PreflightingApplication (30%)

 - InstallingEmbeddedProfile (30%)

 - VerifyingApplication (40%)

 - CreatingContainer (50%)

 - InstallingApplication (60%)

 - PostflightingApplication (70%)

 - SandboxingApplication (80%)

 - GeneratingApplicationMap (90%)
Error running 'ideviceinstaller -i /Users/alex/Documents/Projetos/AmpebApp/platforms/ios/build/device/Ampeb.ipa'
**

**Comment by stevenyix** [comment]
i'm experiencing the same issue, but this may be an issue with ideviceinstaller, not necessarily vs code.  when i try running ideviceinstaller from command line, here is the output:

ideviceinstaller -i /Users/steve/Documents/DevProjects/ionicapp/treadbeacon2/platforms/ios/build/device/treadbeacon2.ipa
WARNING: could not locate iTunesMetadata.plist in archive!
WARNING: could not locate Payload/treadbeacon2.app/SC_Info/treadbeacon2.sinf in archive!
Copying '/Users/steve/Documents/DevProjects/ionicapp/treadbeacon2/platforms/ios/build/device/treadbeacon2.ipa' to device... DONE.
Installing 'com.ionicframework.treadbeacon2901805'
 - CreatingStagingDirectory (5%)
 - ExtractingPackage (15%)
 - InspectingPackage (20%)
 - TakingInstallLock (20%)
 - PreflightingApplication (30%)
 - InstallingEmbeddedProfile (30%)
 - VerifyingApplication (40%)
 - CreatingContainer (50%)
 - InstallingApplication (60%)
 - PostflightingApplication (70%)
 - SandboxingApplication (80%)
 - GeneratingApplicationMap (90%)
Segmentation fault: 11

**Comment by jalchr** [comment]
I'm experiencing same issue. Anyone got this resolved ?

**Comment by jalchr** [comment]
#286 #287

**Comment by iTOYS** [comment]
Fixed #322
