### ISSUE TITLE
Variable inspection doesnt work when hovering

### ISSUE THREAD

**Issue by Rainson12** [Microsoft/vscode-cordova#276]
- VS Code Version:
Version 1.11.2
Commit 6eaebe3b9c70406d67c97779468c324a7a95db0e
Date 2017-04-13T08:03:11.395Z
Shell 1.4.6
Renderer 53.0.2785.143
Node 6.5.0

Steps to reproduce:

1. set a breakpoint
2. attach debugger to android device
3. breakpoint will be hit
4. hovering over a set variable doesnt show the variable content

its an ionic 2 solution btw.

when selecting the text and right clicking it (and then -> Debug: Evaluate) the content will of the variable will be shown in the debug console.

**Comment by vladimir-kotikov** [comment]
@Rainson12 sorry for late response. Are you still having this issue? If yes could you please provide some additional details, specifically Ionic and Cordova versions and platform you're running this on (Mac, Windows, Linux)

**Comment by iTOYS** [comment]
Hi @Rainson12!
I can't exactly reproduce this.
I tried debugging Ionic 2 tabs app and had two cases:
1. Hover works, evaluate works
2. Hover doesn't work, same as evaluate
I saw the same behavior with Chrome debugger.

I guess it's problem with Ionic TS compilation and source map.

**Comment by vladimir-kotikov** [comment]
@Rainson12, pinging once more. Is this still relevant? I.e can you reproduce this using latest version of extension ([1.2.9](https://github.com/Microsoft/vscode-cordova/releases/tag/v1.2.9))?

**Comment by Rainson12** [comment]
Hey,
It seems to be working in vs code now thank you. Sorry for the late response i haven't been doing mobile development since one or two months.

**Comment by vladimir-kotikov** [comment]
Ok, thanks for the update!
