### ISSUE TITLE
F6 Build config

### ISSUE THREAD

**Issue by andreujuanc** [Microsoft/vscode-cordova#281]
Hello,

I could not find docs to configure the behaviour of Cordova Build. Is this possible?

It'd be nice to have, like we have launch.json, a build.json, where you can set defaults, presets etc.

For example, now i'm developing a hook that works on windows and android. I have to bring the console up, arrow up, enter. All the time. I'd lose less time and be more productive if I could just press F6 and set a default build platform and architecture. This is because i'm using certain plugins that don't allow me to build on AnyCPU.

Is this possible? Should I just modify cordova.cmd?

**Comment by vladimir-kotikov** [comment]
See also #250.

As a workaround you can use a concept of [vscode tasks](https://code.visualstudio.com/docs/editor/tasks) to run any arbitrary command (including `cordova build`) and bind it to hotkey of your choice.

As a side note - IMHO tasks are really powerful and even more appropriate for this than having a special command, that just builds app

**Comment by iTOYS** [comment]
Implemented in #328
