### ISSUE TITLE
how Use IntelliSense with Vue?

### ISSUE THREAD

**Issue by cinos1** [Microsoft/vscode-cordova#282]
can I use IntelliSense in vue?

**Comment by vladimir-kotikov** [comment]
@cinos1, can you please elaborate?
The extensions provides some additional Intellisense capabilities for _Cordova plugins_ and agnostic to JS framework used for the app as long as it uses standard cordova plugins/interfaces.

Please also note that not all plugins are covered by this extension - you can take a look at the list of supported plugins here:  https://github.com/Microsoft/vscode-cordova/blob/master/pluginTypings.json
