### ISSUE TITLE
unable to debug with ionic 3

### ISSUE THREAD

**Issue by sgadekar81** [Microsoft/vscode-cordova#284]
i am using these configs

global packages:
ionic/cli-utils : 1.4.0
Cordova CLI      : 7.0.1
Ionic CLI        : 3.4.0

local packages:
ionic/app-scripts : 1.3.7
ionic/cli-plugin-cordova       : 1.4.0
ionic/cli-plugin-ionic-angular : 1.3.1
Cordova Platforms               : android 6.2.3
Ionic Framework                 : ionic-angular 3.4.2

on run on android it gives me following error
  'Unable to find localabstract name of cordova app'

here is my launch.json
{
  "version": "0.2.0",
    "configurations": [
        {
            "name": "Run Android on device",
            "type": "cordova",
            "request": "launch",
            "platform": "android",
            "target": "device",
            "port": 9222,
            "sourceMaps": true,
            "cwd": "${workspaceRoot}",
            "ionicLiveReload": false
        }
    ]
}

**Comment by victorsosa** [comment]
Please check comment on issue #215

**Comment by vladimir-kotikov** [comment]
@sgadekar81 this issue has been fixed in version 1.2.8 of this extension. Closing this, but please let us know if you're still leeing this on latest version. Thanks

**Comment by Missile71** [comment]
I'm using VSCode 64bit version 1.15 with cordova-tools version 1.2.10.
launch.json:
{
            "name": "Run Android on device",
            "type": "cordova",
            "request": "launch",
            "platform": "android",
            "target": "device",
            "port": 9222,
            "sourceMaps": true,
            "cwd": "${workspaceRoot}",
            "ionicLiveReload": false
        }

this my ionic info
    ionic/cli-plugin-proxy : 1.4.6
    ionic/cli-utils        : 1.9.2
    ionic (Ionic CLI)       : 3.9.2

global packages:

    Cordova CLI : 6.5.0

local packages:

    ionic/app-scripts : 1.3.8
    Cordova Platforms  : android 6.1.2
    Ionic Framework    : ionic-angular 3.4.2

System:

    Android SDK Tools : 25.2.5
    Node              : v6.9.4
    npm               : 5.3.0
    OS                : Windows 10

When I run 'Run Android on device' the app start on device then I get: '**Unable to find localabstract name of cordova app**'

**Comment by vladimir-kotikov** [comment]
@Missile71, can you please check if you also have running simulator in addition to device connected? There is an issue with such combination (see https://github.com/Microsoft/vscode-cordova/issues/307) which has been already fixed but the fix is not yet released.

**Comment by Missile71** [comment]
No simulator running

**Comment by vladimir-kotikov** [comment]
@Missile71 I created https://github.com/Microsoft/vscode-cordova/issues/311 to track your issue further - let's move out discussion there

**Comment by sgadekar81** [comment]
@vladimir-kotikov sorry for late reply, debugging is working for me. I am using 1.2.10 Cordova Tools. Thanks

**Comment by vladimir-kotikov** [comment]
@sgadekar81, cool, great to hear! Thank you for confrmation
