### ISSUE TITLE
Launch failed: Error: Activity class does not exist

### ISSUE THREAD

**Issue by JaufretDemaries** [Microsoft/vscode-cordova#288]
Hello,

I'm trying to make the debug on an cordova app through VSC.
To my launch.json I added this:

 `{
      "type": "android",

      "request": "launch",

      "name": "Run adb device android",

      "appSrcRoot": "${workspaceRoot}/cordova/platforms/android",

      "apkFile": "${workspaceRoot}/cordova/platforms/android/build/outputs/apk/android-debug.apk",

      "adbPort": 5037
    },`

I run the app on my phone and I run the debugger wich lead me to this error:
`Checking buildSearching for devices...Found 1 deviceCurrent build already installedLaunching io.cordova.testAbFg/MainActivity on device 0123456789ABCDEF 
[API:23]Launch failed: Error: Activity class {io.cordova.testAbFg/MainActivity} does not exist.`

How can I specify the main activity for my app ? Because MainActivity isn't a thing right now... thank you.

Best regards,

**Comment by alsorokin** [comment]
Your issue doesn't seem to be related to `vscode-cordova` extension. your configuration has `"type": "android"`. `vscode-cordova` uses `"type": "cordova"`

**Comment by vladimir-kotikov** [comment]
@JaufretDemaries, the extension uses `cordova run android` command internally which doesn't have option to launch specific activity. Though in Cordova world there is an option you might want to try - `android-activityName` preference in `config.xml` (see https://github.com/apache/cordova-docs/pull/712 for docs update)
