### ISSUE TITLE
Simulate Android in browser ask for Android platform but it already exist

### ISSUE THREAD

**Issue by cocaybica** [Microsoft/vscode-cordova#294]
Hi,

When trying to launch using _Simulate Android in browser_, the console gives me:

**Couldn't find platform android in project, please install it using 'ionic platform add android'**

But making `ionic cordova platform add android` gives me:

**[INFO] Platform android already exists.**

I can launch without any problem using the option _Serve to the browser (ionic serve)_

My plugin version: 1.2.8

```
ionic info
    @ionic/cli-plugin-cordova       : 1.6.1
    @ionic/cli-plugin-ionic-angular : 1.4.1
    @ionic/cli-utils                : 1.7.0
    ionic (Ionic CLI)               : 3.7.0

global packages:

    Cordova CLI : 7.0.1

local packages:

    @ionic/app-scripts : 2.1.3
    Cordova Platforms  : android 6.2.3
    Ionic Framework    : ionic-angular 3.6.0

System:

    Android SDK Tools : 25.2.5
    Node              : v8.1.4
    OS                : Linux 4.10
    npm               : 5.0.3

```

From terminal I can launch in real device using `ionic cordova run android`
Option _Run Android on device_ launch ok too

**Comment by vladimir-kotikov** [comment]
@cocaybica thanks. Could you please also post here "Simulate Android in browser" section from  your launch config

**Comment by cocaybica** [comment]
Launch.json 

```
 {
            "name": "Simulate Android in browser",
            "type": "cordova",
            "request": "launch",
            "platform": "android",
            "target": "chrome",
            "simulatePort": 8000,
            "livereload": true,
            "sourceMaps": true,
            "cwd": "${workspaceRoot}"
        },
```

**Comment by alsorokin** [comment]
Is your `platforms/platforms.json` file in place? Does it contain Android platform?

**Comment by cocaybica** [comment]
Ok, checked that. After making `cordova platform add android` the issue is gone. 
Thanks.

**Comment by vladimir-kotikov** [comment]
That sounds odd that while `ionic cordova platform add android` yields `[INFO] Platform android already exists.`, `cordova platform add android` actually adds the platform. Anyway this is not an issue with extension so I'm going to close this.

**Comment by GLBekker** [comment]
The extension's output message is misleading asking the users to use the command "ionic cordova platform add android" when the command "cordova platform add android" solves the problem.

**Comment by KokuaDigital** [comment]
I am facing the same problem, and the solution used here doesn't work for me... any idea guys?

**Comment by svekl** [comment]
Hi @KokuaDigital,

If you have Cordova project, please, try to run
`cordova platform add android`
If you have Ionic < v3
`ionic platform add android`
If you have Ionic >=3 - try to run
`ionic cordova platform add android`

**Comment by xProgrammer-007** [comment]
If you get message platform exists even after removing it , 
Make sure you don't have the folder platforms or any file inside it open in code editor .
