### ISSUE TITLE
Cordova Error can anyone help

### ISSUE THREAD

**Issue by saurabhkawli08** [Microsoft/vscode-cordova#296]
![capture](https://user-images.githubusercontent.com/30752317/28996091-4f738958-7a16-11e7-960c-53fec66eb16b.PNG)

**Comment by vladimir-kotikov** [comment]
@saurabhkawli08 as far as I understand your problem is not related to this extension - this error looks like it comes from cordova-android. You might want to ask about your problem on [SO](https://stackoverflow.com/questions/tagged/cordova) or in official [Cordova slack](https://cordova.slack.com)

**Comment by vladimir-kotikov** [comment]
@saurabhkawli08, I'm going to close this but if you think that this is a problem, related to this extension - feel free to reopen
