### ISSUE TITLE
[cordova-debug-adapter] - Error: Unable to find iOS target device/simulator

### ISSUE THREAD

**Issue by SimpleDeveloper49** [Microsoft/vscode-cordova#30]
Hey there, 

iOS 8.1.2, el capitan. 

Tried out the tools after a clean install of cordova tools. The simulator works flawless, but I am running into some issues on debugging on a device. (iOS)

The "Run iOS on device" threw an error on "Configuring debugging proxy" step:
"[cordova-debug-adapter] Error: Unable to find iOS target device/simulator. Try specifying a different "port" parameter in launch.json"

The port is set to **9220** in the **launch.json**. I was able to get rid of the error message by restarting visual studio code and changing the port to 9221. However, I am still not able to hit a breakpoint or type anything into the debug console. (i.e. console.log('test'); -> "TypeError: Cannot read property 'runting_evaluate' of undefined). 
Visual Studio Code seems to be stuck of some sort. Or at least the loading bar in the top left corner indicates a busy state. 

https://github.com/google/ios-webkit-debug-proxy; I find only references to 9221 - 9322. 

Am I missing something, or is this a bug?

**Update:** Able to reproduce on device using iOS 9.2.1 as well.

**Comment by MSLaguana** [comment]
Thanks for reporting this, looks like you've found a bug.

**Comment by SimpleDeveloper49** [comment]
I was able to make some progress. 

1. I forgot to enable: Settings -> Safari -> Advanced -> Web Inspector -> ON
2. Terminal -> ios_webkit_debug_proxy. It shows that my device is connected on port 9222. I am able to debug the phone using ios_webkit_debug_proxy (localhost:9221 -> click on the device)

At this stage, visual studio code gives me this error: [cordova-debug-adapter] Error: Unable to find webview.

**Comment by MSLaguana** [comment]
Sorry, I should have been clear. That "unable to find webview" error is the one I have a fix for in the PR. Your initial issue on port 9221 was likely due to the port being used by another process already which confused the debugger. In particular, 9221 is often used for debugging chrome (which is why it is the default).
