### ISSUE TITLE
[windows][cordova] "Unable to find localabstract name of cordova app"

### ISSUE THREAD

**Issue by dleeq8** [Microsoft/vscode-cordova#301]
hi ..

i try to setup my vscode to work with cordova projects

my steps are:
```
cordova create %cd%
cordova platform add android
```
then from vscode "Attach to running android on device"

output:
```
Attaching to android
Unable to find localabstract name of cordova app
```

my AVD running
```
target: Android 4.2.2
API LVL: 17
CPU:  ARM (armeabi-v7a)
```

```
cordova Installed platforms:
android 6.2.3

cordova -v :
7.0.1
```

**Comment by vladimir-kotikov** [comment]
@dleeq8 could you please provide the following information to debug your case:

- ouput of the following 2 commands (where device_id is device name as shown by adb devices):

  ```
  adb -s <device_id> shell ps
  adb -s <device_id> shell "cat /proc/net/unix"
  ```
- your application id (package name)

Thanks

Please also not thath the following issue is tracked here: #215

**Comment by vladimir-kotikov** [comment]
@dleeq8 please also post your VSCode and Cordova-tools extension version

**Comment by dleeq8** [comment]
@vladimir-kotikov 
vscode: 1.15.0
Cordova-tools extension: 1.2.9

windows 7 x64

i cant use the adv -s code at windows its just start AVD window

**Comment by vladimir-kotikov** [comment]
@dleeq8 I think you mistyped a bit. Please try running `adb` specifying full path. On windows this sould look like 

%ANDROID_HOME%\platform-tools\adb -s <device_id> shell ps
%ANDROID_HOME%\platform-tools\adb -s <device_id> shell "cat /proc/net/unix"

Also don't forget about your application id

**Comment by vladimir-kotikov** [comment]
@dleeq8 any updates? Were you able to figure out how to run `adb` with required arguments?

**Comment by vladimir-kotikov** [comment]
Closing this one as it likely has been fixed by #306

**Comment by lucamorelli** [comment]
same problem here, with the latest version of the plugin installed

**Comment by iTOYS** [comment]
Hi @lucamorelli,
Please try this
```
$ brew uninstall ideviceinstaller
$ brew uninstall libimobiledevice
$ brew install --HEAD libimobiledevice
$ brew install ideviceinstaller
```

**Comment by lucamorelli** [comment]
i'm using windows

**Comment by iTOYS** [comment]
Sorry(

Could you please post your application id (package name) and output of the following commands in order to diagnose the problem:

    adb devices

in the following 2 commands `device_id` is device name as shown by `adb devices`:

```
adb -s <device_id> shell ps
adb -s <device_id> shell "cat /proc/net/unix"
```

**Comment by lucamorelli** [comment]
List of devices attached
0123456789ABCDEF
        device

**adb -s <device_id> shell ps**
[shell ps.txt](https://github.com/Microsoft/vscode-cordova/files/1427943/shell.ps.txt)

**adb -s <device_id> shell "cat /proc/net/unix"**
[shell cat.txt](https://github.com/Microsoft/vscode-cordova/files/1427946/shell.cat.txt)

**Comment by iTOYS** [comment]
What's your application id (package name)?

**Comment by lucamorelli** [comment]
Package name: it.dogapp.dogapp

**Comment by iTOYS** [comment]
Your app was run when you execute this command or app never run on device with vscode?
Could you please open new issue and paste all outputs from output channel and debugger console?
Thanks!

**Comment by lucamorelli** [comment]
cordova run android works from console

**Comment by lucamorelli** [comment]
I created this issue 
https://github.com/Microsoft/vscode-cordova/issues/333
let me know if you need more informations

**Comment by iTOYS** [comment]
Thanks!
