### ISSUE TITLE
Another "localabstract" problem when running on android device

### ISSUE THREAD

**Issue by vladimir-kotikov** [Microsoft/vscode-cordova#311]
Copied from https://github.com/Microsoft/vscode-cordova/issues/284#issuecomment-324844353

I'm using VSCode 64bit version 1.15 with cordova-tools version 1.2.10.
launch.json:
{
            "name": "Run Android on device",
            "type": "cordova",
            "request": "launch",
            "platform": "android",
            "target": "device",
            "port": 9222,
            "sourceMaps": true,
            "cwd": "${workspaceRoot}",
            "ionicLiveReload": false
        }

this my ionic info
    ionic/cli-plugin-proxy : 1.4.6
    ionic/cli-utils        : 1.9.2
    ionic (Ionic CLI)       : 3.9.2

global packages:

    Cordova CLI : 6.5.0

local packages:

    ionic/app-scripts : 1.3.8
    Cordova Platforms  : android 6.1.2
    Ionic Framework    : ionic-angular 3.4.2

System:

    Android SDK Tools : 25.2.5
    Node              : v6.9.4
    npm               : 5.3.0
    OS                : Windows 10

When I run 'Run Android on device' the app start on device then I get: '**Unable to find localabstract name of cordova app**'

**Comment by vladimir-kotikov** [comment]
This is not #307 and need to be investigated separately

**Comment by vladimir-kotikov** [comment]
@Missile71, could you please post your application id (package name) and output of the following commands in order to diagnose the problem:

    adb devices

in the following 2 commands `device_id` is device name as shown by `adb devices`:

```
adb -s <device_id> shell ps
adb -s <device_id> shell "cat /proc/net/unix"
```

**Comment by Missile71** [comment]
**adb devices**
List of devices attached
96d18aef        device

**adb -s 96d18aef shell ps**
[output.txt](https://github.com/Microsoft/vscode-cordova/files/1251442/output.txt)

**adb -s 96d18aef shell  "cat /proc/net/unix"**
[output2.txt](https://github.com/Microsoft/vscode-cordova/files/1251445/output2.txt)

**Comment by vladimir-kotikov** [comment]
@Missile71 what's your application id (package name)?

**Comment by Missile71** [comment]
sorry, forgot: it is com.rama.EBS

**Comment by vladimir-kotikov** [comment]
Hmm, odd. Looking at the logs I would say that everything should work. At least the extension is able to find proper debug port to attach to. The only remaining idea that I have is that extension somehow is not able to detect device properly and hence these commands fail when ran by extension.

@Missile71 would you mind adding some debug code to check this? You would need to find extension (on Windows it's usually located at `%userprofile%/.vscode/extensions/vsmobile.cordova-tools-<version>`) and edit `out/src/debugger/cordovaDebugAdapter.js` file - add `this.outputLogger(devicesOutput)` after line 223 and `this.outputLogger(targetDevice)` after line 253.

You might also try adding those logging statements to other places to see more details about what's happening there.

**Comment by Missile71** [comment]
the problem is here
` const fields = line.split(PS_FIELDS_SPLITTER_RE).filter(field => !!field);
                    if (fields.length < nameIdx) {
                        continue;
                    }
                    if (fields[nameIdx] === appPackageName) {
                        return fields[pidIdx];
                    }`

line = u0_a851   22742 337   1864536 155584 ffffffff 00000000 S com.rama.EBS
appPackageName = com.rama.EBS
but
fields[nameIdx] = com.rama.EB

i don't know how this line work, but work wrong only with this line

**Comment by Missile71** [comment]
> i don't know how this line work, but work wrong only with this line
 sorry, I ment that I don't know how  this line `line.split(PS_FIELDS_SPLITTER_RE).filter(field => !!field); `works
and it works worng only with this line ` u0_a851 22742 337 1864536 155584 ffffffff 00000000 S com.rama.EBS`

**Comment by vladimir-kotikov** [comment]
@Missile71 thanks for information - now I guess I know what's going wrong there - looks like the line has trailing '\r' symbol and hence regular expression just splits that line incorrectly. Could you please try one of the following:
- either add `.trim()` just before `split` like this `line.trim().split(PS_FIELDS_SPLITTER_RE)`
- or replace `PS_FIELDS_SPLITTER_RE` with this: `/\s+([RSIDZTW<NL]\s+)?/`

any of these should help

**Comment by Missile71** [comment]
Thank you Vladimir!!!
the .trim() before split worked
Thank you very much

**Comment by vladimir-kotikov** [comment]
Nice, thanks for confirmation! I'll send a fix shortly
