### ISSUE TITLE
pass arguments to process (ionic)

### ISSUE THREAD

**Issue by seveves** [Microsoft/vscode-cordova#314]
I'm using a simple cordova launch configuration to start my ionic app.

```
{
      "name": "Run android on emulator",
      "type": "cordova",
      "request": "launch",
      "platform": "android|ios",
      "target": "device|emulator",
      "sourceMaps": true,
      "ionicLiveReload": true,
      "cwd": "${workspaceRoot}"
}
```
This works so far but now I have the problem that my PC has more than one network devices and ionic prompts me to choose one and that is not possible in the vscode debugging console (no user interaction with arrow keys possible).
To solve this I could provide the network device by passing an argument to ionic. F.e. `--address 10.8.225.1` but the launch.json doesn't support args.

Is there a way to fix this?

Kind regards

**Comment by vladimir-kotikov** [comment]
@seveves you're right - there is no way to pass arbitrary arguments to `ionic run` command but you can use [`devServerAddress`](https://github.com/Microsoft/vscode-cordova/blob/master/package.json#L346-L353) option in `launch.json` to specify a concrete address to launch dev server on

**Comment by seveves** [comment]
@vladimir-kotikov ah thanks ... I gonna try this option as a workaround. 
IMHO it wouldn't be that bad to allow some arbitrary arguments.

**Comment by vladimir-kotikov** [comment]
@seveves, glad that it helped. Regarding adding support for custom arguments - I agree that would be helpful in some cases, so i'll add it to our backlog.
