### ISSUE TITLE
Allow pass custom arguments to ionic/cordova commands

### ISSUE THREAD

**Issue by vladimir-kotikov** [Microsoft/vscode-cordova#315]
Ionic and Cordova CLI support various arguments for run/build commands so I can imagine cases when one might want to run those commands (to start app fro debugging) with some additional arguments. One example of this is #314

**Comment by jwargo** [comment]
Makes sense. Nobody has asked for this?

**Comment by jwargo** [comment]
Aaaah, nevermind, I see that someone has asked for it.

**Comment by vladimir-kotikov** [comment]
Implemented in #321
