### ISSUE TITLE
`Unable to find localabstract name of cordova app` on Android Oreo device

### ISSUE THREAD

**Issue by dfarley1** [Microsoft/vscode-cordova#317]
I'm re-opening #312, v1.2.12 did not fix the issue for me.  I tried uninstalling the extension, exiting VSCode, deleting the extension folder, reinstalling the extension, and restarting VSCode.  Everything still works on my Nougat device as well.  

I have all of the changes mentioned by @LordAelfric in the other thread except the latter two are off by one, they live on lines 260 and 264 respectively.  Is there any other debug info I can provide?

**Comment by vladimir-kotikov** [comment]
@dfarley1 sorry for closing that issues one too early. Let's reopen it and continue discussion there as that thread has some context for your problem.
