### ISSUE TITLE
Failed attaching to Android Emulator: Unable to find target device

### ISSUE THREAD

**Issue by damirarh** [Microsoft/vscode-cordova#318]
With version 1.2.12 any attempt to attach to Android emulator fails with the following output in debug console:

```
Attaching to android
List of devices attached
emulator-5554	device

Unable to find target device
```

I had to revert to version 1.2.11 using [these instructions](https://tpodolak.com/blog/2017/04/09/downgrading-visual-studio-code-extension/) to get debugging working again.

**Comment by vladimir-kotikov** [comment]
@damirarh thanks for reporting. Could you please post here your Android debug config from  `launch.json`?

**Comment by damirarh** [comment]
Sure, here it is:

```
{
  "name": "Attach to Android",
  "type": "cordova",
  "request": "attach",
  "platform": "android",
  "target": "device",
  "port": 9222,
  "sourceMaps": true,
  "cwd": "${workspaceRoot}/www"
}
```

**Comment by vladimir-kotikov** [comment]
@damirarh, notice the `"target"` parameter in your attach configuration - by setting it to `"device"` you explicitly instruct the extension to look for app running on device while you have it running on emulator. To get it working you only need to change "device" -> "emulator".

I believe the behavior has changed in #310 - there was a bug when extension just ignored "target" parameter and was trying to attach to wrong target.

**Comment by damirarh** [comment]
Yes, changing `"target"` to `"emulator"` fixes the issue. Thank you.

**Comment by vladimir-kotikov** [comment]
Thanks for confirmation. Closing as resolved
