### ISSUE TITLE
Run iOS on device stuck on "Installing app on device"

### ISSUE THREAD

**Issue by ruben82** [Microsoft/vscode-cordova#319]
Hi,
I cannot start my app on iOS device by this tool.
When I try to do that the ipa is generated correctly but tool stuck on "Installing app on device" message.
Anyone got this issue?
Thank to all

**Comment by iTOYS** [comment]
Hi @ruben82. Thanks for reporting!
Could you please provide a bit more info:
1. Debug console output
2. Cordova version
3. vscode-cordova version
3. Device model and ios version
4. Xcode and MacOS versions
Thank you!

**Comment by ruben82** [comment]
Sure 
Just for information: All works If I launch from shell this command from shell
 ionic cordova run ios --device 

1) _

> Copying _'/Users/ruben/PROJECT/platforms/ios/build/device/ENICIE.ipa' to device... DONE.
> Installing 'com.package.name'
>  - CreatingStagingDirectory (5%)
> 
>  - ExtractingPackage (15%)
> 
>  - InspectingPackage (20%)
> 
>  - TakingInstallLock (20%)
> 
>  - PreflightingApplication (30%)
> 
>  - InstallingEmbeddedProfile (30%)
> 
>  - VerifyingApplication (40%)
> 
>  - CreatingContainer (50%)
> 
>  - InstallingApplication (60%)
> 
>  - PostflightingApplication (70%)
> 
>  - SandboxingApplication (80%)
> 
>  - GeneratingApplicationMap (90%)
> Error running 'ideviceinstaller -i Users/ruben/PROJECT//platforms/ios/build/device/ENICIE.ipa'_

_
 
2) 7.0.1
3) 1.2.12
4) iPhone 6 IOS 10.3.3
5) Xcode 8.3.3 Build version 8E3004b  and S.O. macOS Sierra

**Comment by iTOYS** [comment]
Looks like that issue
https://stackoverflow.com/questions/45520257/ideviceinstaller-i-returns-segmentation-fault-11

**Comment by ruben82** [comment]
To make it works i reinstalled 2 library

> brew uninstall ios-webkit-debug-proxy && brew install ios-webkit-debug-proxy

> brew uninstall libimobiledevice && brew install --HEAD libimobiledevice

All work fine now. 

I hope this helps

**Comment by iTOYS** [comment]
@ruben82 Thanks for helping!
I will update the docs.

**Comment by iTOYS** [comment]
#322
