### ISSUE TITLE
cannot run the ionic serve task

### ISSUE THREAD

**Issue by lucamorelli** [Microsoft/vscode-cordova#336]
I'm trying to run the **"Serve to the browser (ionic serve)"** task from my project.
I see that ionic serve start to work, but after a while I receive the error message Error: **Starting the Ionic dev server timed out (30000 ms)** and Ionic serve start to work

**Comment by iTOYS** [comment]
Hi @lucamorelli,
Please see [here](https://github.com/Microsoft/vscode-cordova/issues/134)

**Comment by lucamorelli** [comment]
change the value of the devServerTimeout didn't solve the problem. Ionic CLI starts, works, but after the expiration of timeout I receive this error

Launching for serve (This may take a while)...
Starting Ionic dev server (live reload: true)
[WARN] The --nobrowser option has been deprecated. Please use --no-open.
Starting server (address: localhost, port: 8100, dev server port: 53703, livereload port: 35729) - Ctrl+C to cancel
[OK] Development server running!
     Local: http://localhost:8100
     DevApp: dogapp@8100 on windows81
Starting the Ionic dev server timed out (240000 ms)
