### ISSUE TITLE
Symbolic Links ignored for livereload at simulator

### ISSUE THREAD

**Issue by lhrolim** [Microsoft/vscode-cordova#340]
At my project I have some symbolic links setup so that I´m able to share some projects between different solutions.

Visual Ex:

Project
    --www
        --Content
           --- Mobile (Non-Linked sync works!! )
           ---Shared
                      --linked1 (Linked sync fails!! )
                      --linked2 (Linked sync fails!! )

The linked files are served correctly to the simulator.

If I make a change to any files of those "linked files" though they do not trigger a livereload (nor a manual browser refresh would either). If I restart the debugger the changes are pushed.

Withouth restarting the debugger, If I change, afterwards , any "non linked files" then both the linked file and the non-linked file changes are pushed into the simulator context.

As a workaround I´ve been able to develop like this (i.e making sure to change anything on a non linked file afterwards), but it´s by far not ideal.

I´m opening it here, but I´m not sure if this is a cordova-simulate issue though.

I´m running the extension at version 1.2.0

**Comment by lhrolim** [comment]
Btw: after searching I came across this issue old issue which was marked as closed

https://github.com/Microsoft/vscode/issues/24739

**Comment by iTOYS** [comment]
@lhrolim 
Cordova observe for files directly, we can't do anything

**Comment by lhrolim** [comment]
@iTOYS 

the exact same setup works at VSCommunity though. 

Could you lead me torwards understaanding what would possibly be the difference?

**Comment by iTOYS** [comment]
Unfortunately, I don't know how VSCommunity works inside(

**Comment by lhrolim** [comment]
@iTOYS 

Thanks. I´ll try to dig a bit later.
