### ISSUE TITLE
Ionic 3 support?

### ISSUE THREAD

**Issue by hardcodet** [Microsoft/vscode-cordova#342]
Hi all

The main read-me states that the Ionic 2 Beta is not currently supported, which I hope is very obsolete given that we're way past that. Does the extension provide support for Ionic 3, or are we better off waiting at this point?

Thanks!

**Comment by jwargo** [comment]
I'm not aware of any limitations in using Ionic 3. If you find any, let us know and we'll fix them.

**Comment by hardcodet** [comment]
Oh, I wouldn't know - I've been working with Ionic for about 3 minutes now :)
I was mostly irritated by the main read-me, which probably hasn't been updated since Ionic 2 Beta (which wasn't supported at that time).

**Comment by jwargo** [comment]
We're usually pretty good at updating the docs, I apologize that we missed this one. I'll get it updated.
