### ISSUE TITLE
It is possible to debug on android without ionic?

### ISSUE THREAD

**Issue by jvitor83** [Microsoft/vscode-cordova#344]
Just a information:
It is possible to debug on android without ionic?

If it is, is there a documentation or sample of how to make it work?

**Comment by jwargo** [comment]
What exactly are you trying to do? What type of app do you want to debug? 

Using this extension, Visual Studio can only debug Cordova apps (an Ionic app is a Cordova app).

**Comment by jwargo** [comment]
Are you asking if you can debug an Android app's native code using this extension? No, you would have to use Android Studio for that.

**Comment by jvitor83** [comment]
What i am asking is:
If i can create a cordova app with only html, css, JS (or TS) and debug using this extension!?!

Visual Studio (not vs code) has a Cordova Tools that allow to create a pure cordova project (without ionic) -> https://www.visualstudio.com/vs/cordova/

**Comment by jwargo** [comment]
Yes, you can. It's the Cordova extension, so its main purpose is to code and debug Cordova applications. Ionic applications just happen to be Cordova applications under the covers, so that's why we can **also** debug Ionic applications.

**Comment by jvitor83** [comment]
Ok, but, i want to know how!
My question is: if it is possible, how can i do?
Do i need to have ionic installed (`npm i -g ionic`) to this extension allow to debug? There are some kind of requirements to allow debug? Or sample?

**Comment by jvitor83** [comment]
What i mean is:
```
{
            "name": "Run Android on device",
            "type": "cordova",
            "request": "launch",
            "platform": "android",
            "target": "device",
            "port": 9222,
            "sourceMaps": true,
            "cwd": "${workspaceRoot}",
            "ionicLiveReload": false
        }
```
this task allow to debug pure cordova app (without ionic or ionic-cli installer)?

**Comment by jwargo** [comment]
No, you do not need Ionic to debug Cordova apps. Nothing about the debug process has anything to do with Ionic. Ionic is a UI framework that sits on top of Apache Cordova. It is not involved in any way with debugging of any applications. It's a framework you would use to create graphically pleasing Cordova applications.

To debug Cordova applications, follow the instructions in the Visual Studio Code Cordova Extension readme file. You can open it directly in Visual Studio Code, just go to the extensions page and select the Cordova plugin. You can also find the instructions in the extension's Github page: https://github.com/Microsoft/vscode-cordova. It explains, with screen shots, how to debug Cordova applications using the extension.
