### ISSUE TITLE
Stop/kill ionic process on debug stop

### ISSUE THREAD

**Issue by jQrgen** [Microsoft/vscode-cordova#346]
Currently, if I run this plugin with the following conf It works fine, but if I stop the debugger with the red stop button I cannot run the task again. I think this is because an ionic process from the last session is stuck in the background and blocks the port ionic wants to use.

_launch.json_
```js
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "ionic serve chromium",
            "type": "cordova",
            "request": "launch",
            "platform": "serve",
            "target": "chromium",
            "cwd": "${workspaceRoot}",
            "devServerAddress": "localhost",
            "sourceMaps": true,
            "ionicLiveReload": true,
            "devServerTimeout": 120000
        }
    ]
}
```

Errors when i re-run the task: 
![screen shot 2017-11-19 at 15 59 19](https://user-images.githubusercontent.com/3964957/32991840-3f1ba786-cd43-11e7-8364-46401ebbfeef.png)
![screen shot 2017-11-19 at 15 59 31](https://user-images.githubusercontent.com/3964957/32991841-412ace30-cd43-11e7-9d88-4ad9f216d442.png)

When do:
`$ ps -ax | grep ionic`
We see an ionic process is still running: 
![screen shot 2017-11-19 at 16 05 37](https://user-images.githubusercontent.com/3964957/32991861-7f2e5b02-cd43-11e7-936d-50be67b13ffc.png)

$ `ionic info` returns:

cli packages: (/Users/.../.nvm/versions/node/v8.9.0/lib/node_modules)

    @ionic/cli-utils  : 1.18.0
    ionic (Ionic CLI) : 3.18.0

global packages:

    cordova (Cordova CLI) : 7.1.0 
    Gulp CLI              : CLI version 3.9.1 Local version 3.9.1

local packages:

    @ionic/app-scripts : 3.1.2
    Cordova Platforms  : ios 4.5.2
    Ionic Framework    : ionic-angular 3.9.2

System:

    Node  : v8.9.0
    npm   : 5.5.1 
    OS    : macOS High Sierra
    Xcode : Xcode 9.1 Build version 9B55 

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro

**Comment by iTOYS** [comment]
@jQrgen 

Thanks for reporting!
Please update extension to 1.3.1 and try.

**Comment by mkormendy** [comment]
This is not working anymore again.
Using extension v2.4.1
