### ISSUE TITLE
Trying to emulate/run Android on OSX fails

### ISSUE THREAD

**Issue by Gochida** [Microsoft/vscode-cordova#351]
I'm trying to take the default app created via 'Cordova create appName' and using Cordova Tools, run the android app.
Trying to emulate or run on a physical device fails.
This is what appears in the debug console when trying to run on device:

```
>Launching for android (This may take a while)...

> No scripts found for hook "before_run".
> No scripts found for hook "before_prepare".
> Checking config.xml and package.json for saved platforms that haven't been added to the project
> Config.xml and package.json platforms are the same. No pkg.json modification.
> Package.json and config.xml platforms are different. Updating config.xml with most current list of platforms.
> PlatformApi successfully found for platform android
> Checking config.xml for saved plugins that haven't been added to the project
> Checking for any plugins added to the project that have not been installed in android platform
> No differences found between plugins added to project and installed in android platform. Continuing...
> Generating platform-specific config.xml from defaults for android at /Users/cravergl/Documents/Projects/MalikApp/platforms/android/res/xml/config.xml
> Merging project's config.xml into platform-specific android config.xml
> Merging and updating files from [www, platforms/android/platform_www] to platforms/android/assets/www
> Wrote out android application name "HelloCordova" to /Users/cravergl/Documents/Projects/MalikApp/platforms/android/res/values/strings.xml
> android-versionCode not found in config.xml. Generating a code based on version in config.xml (1.0.0): 10000
> Wrote out Android package name "io.cordova.hellocordova" to /Users/cravergl/Documents/Projects/MalikApp/platforms/android/src/io/cordova/hellocordova/MainActivity.java
> This app does not have launcher icons defined
> This app does not have splash screens defined
> This app does not have additional resource files defined
> Prepared android project successfully
> No scripts found for hook "after_prepare".
> Running command: /usr/libexec/java_home 
> Command finished with error code 0: /usr/libexec/java_home 
> ANDROID_HOME=/Users/cravergl/Library/Android/sdk
> JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home
> 
> Error: spawn EACCES
> 'cordova run android --device --verbose --no-update-notifier' failed with exit code 1

```

Android Studio v.3.0.1 is installed
Cordova Tools add-on is installed
taco-cli was installed using nom

I am able to run the Cordova project as an iOS app just fine. It seems only the Android side of things is affected.

**Comment by jwargo** [comment]
Two things, are you really running on OS X?  If so, you're a couple of years behind as macOS has been the Macintosh OS platform for more than a year now. You may want to upgrade your OS.

What happens when you run `cordova run android` from a terminal window?  Confirm that it works outside of Visual Studio Code first, that way we can tell if its actually a Visual Studio Code error.

**Comment by Gochida** [comment]
Yeah sorry I don't know the actual name for the OS of this thing, it's an iOS dev laptop I'm borrowing to get a cordova app working, I'm figuring out how to use a Mac as I'm going along.

Running ```cordova run android``` in a terminal gives ```error: spawn EACCES```

**Comment by jwargo** [comment]
OK, so you're getting the same error from the command line as you're getting from Visual Studio Code, so its not a VS Code problem, there's something else wrong with your config. We use the Cordova CLI under the covers, so if the CLI's not working, then we won't work as well.

A quick internet search points to this being a permissions problem with your system - most likely a problem with the Android (or possibly Cordova) installation.
