### ISSUE TITLE
Constant errors in debug console

### ISSUE THREAD

**Issue by SpellCraft** [Microsoft/vscode-cordova#352]
Hello!

# My setup:

**Vscode:** 1.18.1
**Cordova Tools:** 1.3.1
**Cordova version:** 7.1.0
**Cordova-Android version:** 6.3.0
**Launch.json**: https://gist.github.com/SpellCraft/271e4f8e121226a091852e64d25d7317

# Issue:
Whenever I use the "Run Android on emulator" debug option the app loads up fine and there are no issues whatsoever. When I start typing into the debug console, it will instantly produce this error:
https://gist.github.com/SpellCraft/c61e369b227e35e8462c1aeae73b1ff7

Is this an issue with the vscode-cordova plugin or an issue with vscode itself?

For good measure I've tried opening a different workspace with another app project I was working on and it's producing the same error; for good measure, I'll include this secondary log as well for comparison.
https://gist.github.com/SpellCraft/566654941878e45f87f96d6ec2d1f4de

Now, while these errors are produced, they don't seem to actually interfere with the debugging process as I'm still able to query, say ```window.localStorage``` and intellisense/autocompletion starts working again seemingly after writing the first keyword. (like *window* **.** and it starts working, but will produce these errors for every character written until the period)

I really appreciate everything you guys do and hope that I can get to the bottom of this. (Makes debugging very annoying to say the least.)

Merry Christmas.

**Comment by iTOYS** [comment]
Hi @SpellCraft 
Sorry for delay!
Seems like this is typo in one of our dependence. So we should publish new version of extension to fix it. We're planning to release new version in start of next year!

Meantime you can fix it manually:
Replace `Promise.mreject` to `Promise.reject` 
Thanks!

**Comment by SpellCraft** [comment]
@iTOYS Thanks for the update. Don't worry about delay times. With holidays approaching fast and family, it's understandable. (I was away myself!)

Can't wait for the new version.

Super appreciate all you guys do. <3

**Comment by iTOYS** [comment]
@SpellCraft 
New 1.3.2 release has been [published](https://marketplace.visualstudio.com/items?itemName=vsmobile.cordova-tools)

Please try and let me know if you have any troubles
Thanks!

**Comment by SpellCraft** [comment]
@iTOYS Absolutely awesome mate.  Keep up the good job. <3 Working brilliantly so far.
