### ISSUE TITLE
AndroidManifest.xml not found using Cordova-Android 7.0.0

### ISSUE THREAD

**Issue by SpellCraft** [Microsoft/vscode-cordova#355]
# My setup:

**Vscode:** 1.19.1
**Cordova Tools:** 1.3.1
**Cordova version:** 8.0.0
**Cordova-Android version:** 7.0.0
**Launch.json**: https://gist.github.com/SpellCraft/271e4f8e121226a091852e64d25d7317

# Issue:
Running Cordova on android emulator with the latest version of everything works fine, until the debugger is attempting to attach itself to the newly launched instance. It's generating this error:

ENOENT: no such file or directory, open '...\platforms\android\AndroidManifest.xml'

As far as I'm able to deduct is that Cordova changed the folder structure on Android on the 7.0.0 launch such so that AndroidManifest.xml is no longer found in the base /Cordova Project/Platforms/Android/ folder, 

I think it was moved to platforms/android/app/src/main as that's the only place other than outside the CordovaLib folder I can find it.

**Comment by ROSteh** [comment]
My solution
 See C:\Users\Username\.vscode\extensions\vsmobile.cordova-tools-1.3.1\out\src\debugger\cordovaDebugAdapter.js

find ` let packagePromise: Q.Promise<string> = Q.nfcall(fs.readFile, path.join(attachArgs.cwd, 'platforms', 'android', 'AndroidManifest.xml'))`
do `  let packagePromise = Q.nfcall(fs.readFile, path.join(attachArgs.cwd, 'platforms', 'android','app','src','main', 'AndroidManifest.xml')) `

**Comment by jrendell** [comment]
Thanks - this change in cordovaDebugAdapters.ts is working for me.

**Comment by iTOYS** [comment]
@ROSteh Thanks a lot for helping!

Fixed in #358

**Comment by Mowzey123** [comment]
hello
vsmobile.cordova-tools-1.3.1\out\src\debugger\cordovaDebugAdapter.js this path doesn't exist on my side.
Any Help
