### ISSUE TITLE
vscode module not found

### ISSUE THREAD

**Issue by RenaldSB** [Microsoft/vscode-cordova#36]
Hi,
I had followed the guidelines and during "gulp build", the error is raised:

[12:25:45] Using gulpfile ~\.vscode\extensions\vscode-cordova\gulpfile.js
[12:25:45] Starting 'build'...
src\cordova.ts(6,25): error TS2307: Cannot find module 'vscode'.
src\utils\cordovaCommandHelper.ts(7,22): error TS2307: Cannot find module 'vscode'.
test\cordova.test.ts(10,25): error TS2307: Cannot find module 'vscode'.
[12:25:48] TypeScript: 3 semantic errors
[12:25:48] TypeScript: emit succeeded (with errors)
[12:25:48] Finished 'build' after 2.73 s

I have installed the npm module 'vscode' but I still have the  #error.

Regards
Rénald

**Comment by MSLaguana** [comment]
Did you run `npm install` in the root of the project, or did you manually install the vscode module somewhere?

**Comment by RenaldSB** [comment]
I have follow the CONTRIBUTION.me, I have done à 'npm install'.

**Comment by MSLaguana** [comment]
Do you have a `node_modules/vscode` folder at the root of your project? If you cloned the repository somewhere inside a folder that already had a node_modules then npm may have decided to install the dependency further up, which would break the path to the typings. You could try creating a node_modules folder in the root of the git repo and then running `npm install` again to make sure it installs in the expected path.

**Comment by RenaldSB** [comment]
Yes the folder is present.
I already have deleted twice 'node_modules' and run 'npm install'.
I still have the problem.

**Comment by RenaldSB** [comment]
I have added in gulp.js a require line to vscode (var vscode = require('vscode');)
On build, error is "Error: Cannot find module 'vscode'"

![2016-02-08 14_54_42-node_modules - clover](https://cloud.githubusercontent.com/assets/3973188/12887306/b24af4da-ce73-11e5-803d-de62347586d3.png)

Really don't understand where is the problem :(

**Comment by RenaldSB** [comment]
Found the problem!
It's a specific Windows problem with long path:
https://github.com/nodejs/node/issues/1990
