### ISSUE TITLE
Unable to simulate ios or android in browser

### ISSUE THREAD

**Issue by jdeanwaite** [Microsoft/vscode-cordova#361]
Hello vscode-cordova team!

I am running macOS and am attempting to run the "Simulate Android in browser" or "Simulate iOS in browser" configurations, but both of them resulted in the following error:

```
Launching for android (This may take a while)...
An error occurred while attaching to the debugger. EACCES: permission denied, open 'local-storage.json'
EACCES: permission denied, open 'local-storage.json'
```

Any subsequent attempt to run it results in the following:

```
[cordova-tools] Error processing "launch": Error: Couldn't find platform android in project, please install it using 'ionic platform add android'
```

Indeed, my platforms are both installed and work perfectly through the standard CLI commands. Any suggestions?

Here are my configurations.
```
        {
            "name": "Simulate Android in browser",
            "type": "cordova",
            "request": "launch",
            "platform": "android",
            "target": "chrome",
            "simulatePort": 8000,
            "livereload": true,
            "sourceMaps": true,
            "cwd": "${workspaceRoot}"
        },
        {
            "name": "Simulate iOS in browser",
            "type": "cordova",
            "request": "launch",
            "platform": "ios",
            "target": "chrome",
            "simulatePort": 8000,
            "ionicLiveReload": true,
            "sourceMaps": true,
            "cwd": "${workspaceRoot}"
        },
```

It is worth noting that "Serve to the browser (ionic serve)" does work.

**Comment by iTOYS** [comment]
Hi Justin! @jdeanwaite 

What kind of project do you use(Cordova/Ionic)?
How do you run VSCode? Could you please try to to open your project from terminal:
```
$ code /path/to/your/project/folder
```
Also you can try to change permissions :
```
$ chmod -R ugo+rw /path/to/your/project/folder
```

**Comment by jdeanwaite** [comment]
I am using an Ionic project. This is my first venture into VS Code, and I am coming from using WebStorm. 

I simply start VSCode from Spotlight (running macOS). 

Opening VSCode from the command line did not change the outcome. However when I changed permissions of the folder, I no longer receive the `EACCES: permission denied`, however I do still receive the next error 
```
An error occurred while attaching to the debugger. Couldn't find platform ios in project, please install it using 'ionic platform add ios'
```

The platform is most definitely installed!

**Comment by iTOYS** [comment]
@jdeanwaite 
I've fixed this issue in #362 
But also we need to publish new release to distribute changes.
Right now you can fix it by themselves, just create `platforms/platforms.json` in your project folders and fill it e.g.:
```
{
  "android": "7.0.0",
  "ios": "4.5.4"
}
```
> You can find the current version in `package.json`, though it's doesn't matter :)

**Comment by jdeanwaite** [comment]
Okay that did fix the problem (though I had to try running it twice to get it to work). Seems to be working now. However, trying to run onto the device directly only yields an error:
```
Installing app on device
Launching app
Unable to mount developer disk image.
```
```
{
            "name": "Run iOS on device",
            "type": "cordova",
            "request": "launch",
            "platform": "ios",
            "target": "device",
            "port": 9220,
            "sourceMaps": true,
            "cwd": "${workspaceRoot}",
            "ionicLiveReload": false
        },
```

This occurs on both my iPhone 7 Plus and my iPhone X. Again, running from command line works. Any thoughts?

**Comment by iTOYS** [comment]
Did you do number three from [that](https://github.com/Microsoft/vscode-cordova#install-it)?

**Comment by jdeanwaite** [comment]
@iTOYS 

Yes I did, 

```
Warning: ideviceinstaller 1.1.0_3 is already installed
Warning: ios-webkit-debug-proxy 1.8 is already installed
```

Should I open a different issue for this problem?

**Comment by iTOYS** [comment]
@jdeanwaite 
Yes please! And fill it up by template.

Thanks!

**Comment by dariocavada** [comment]
Hello I've the same problem.
- Simple Hello World Cordova project
- Debug with "Simulate Android"

- Tried with 
`$ chmod -R a+rw /path/to/your/project/folder`

Tried with `platforms/platforms.json` file,
but still have this error:

`[cordova-tools] Error processing "launch": Error: EACCES: permission denied, open 'local-storage.json'
 `

and without restarting `code` if I try to launch again it shows me this other error:
`[cordova-tools] Error processing "launch": Error: Error starting the simulation`

Any other idea to solve this?

Thank you!
