### ISSUE TITLE
Error starting the simulation after updating to VS Code 1.20.0

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode-cordova#371]
_From @avinashbhalki on February 14, 2018 5:48_

Unable to use Simulate Android to Browser after updating the Visual Studio Code to version 1.20.0.
**Error:** 
Launching for android (This may take a while)...
An error occurred while attaching to the debugger. Error starting the simulation
Error starting the simulation

- VSCode Version: 1.20.0
- OS Version: Windows 7

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

_Copied from original issue: Microsoft/vscode#43634_

**Comment by weinand** [comment]
What debugger extension are you using?

**Comment by weinand** [comment]
_From @avinashbhalki on February 14, 2018 7:45_

Debugger for Chrome

**Comment by weinand** [comment]
Please provide more detailed steps so that we can reproduce.
What exact error occurred? Screenshot?
How does your launch config look like?

**Comment by weinand** [comment]
_From @avinashbhalki on February 14, 2018 10:2_

{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
    
        {
            "name": "Run Android on device",
            "type": "cordova",
            "request": "launch",
            "platform": "android",
            "target": "device",
            "port": 9222,
            "sourceMaps": true,
            "cwd": "${workspaceRoot}",
            "ionicLiveReload": false
        },
        {
            "name": "Run iOS on device",
            "type": "cordova",
            "request": "launch",
            "platform": "ios",
            "target": "device",
            "port": 9220,
            "sourceMaps": true,
            "cwd": "${workspaceRoot}",
            "ionicLiveReload": false
        },
        {
            "name": "Attach to running android on device",
            "type": "cordova",
            "request": "attach",
            "platform": "android",
            "target": "device",
            "port": 9222,
            "sourceMaps": true,
            "cwd": "${workspaceRoot}"
        },
        {
            "name": "Attach to running iOS on device",
            "type": "cordova",
            "request": "attach",
            "platform": "ios",
            "target": "device",
            "port": 9220,
            "sourceMaps": true,
            "cwd": "${workspaceRoot}"
        },
        {
            "name": "Run Android on emulator",
            "type": "cordova",
            "request": "launch",
            "platform": "android",
            "target": "emulator",
            "port": 9222,
            "sourceMaps": true,
            "cwd": "${workspaceRoot}",
            "ionicLiveReload": false
        },
        {
            "name": "Run iOS on simulator",
            "type": "cordova",
            "request": "launch",
            "platform": "ios",
            "target": "emulator",
            "port": 9220,
            "sourceMaps": true,
            "cwd": "${workspaceRoot}",
            "ionicLiveReload": false
        },
        {
            "name": "Attach to running android on emulator",
            "type": "cordova",
            "request": "attach",
            "platform": "android",
            "target": "emulator",
            "port": 9222,
            "sourceMaps": true,
            "cwd": "${workspaceRoot}"
        },
        {
            "name": "Attach to running iOS on simulator",
            "type": "cordova",
            "request": "attach",
            "platform": "ios",
            "target": "emulator",
            "port": 9220,
            "sourceMaps": true,
            "cwd": "${workspaceRoot}"
        },
        {
            "name": "Serve to the browser (ionic serve)",
            "type": "cordova",
            "request": "launch",
            "platform": "serve",
            "cwd": "${workspaceRoot}",
            "devServerAddress": "localhost",
            "sourceMaps": true,
            "ionicLiveReload": true
        },
        {
            "name": "Simulate Android in browser",
            "type": "cordova",
            "request": "launch",
            "platform": "android",
            "target": "chrome",
            "simulatePort": 8000,
            "livereload": true,
            "sourceMaps": true,
            "cwd": "${workspaceRoot}"
        },
        {
            "name": "Simulate iOS in browser",
            "type": "cordova",
            "request": "launch",
            "platform": "ios",
            "target": "chrome",
            "simulatePort": 8000,
            "livereload": true,
            "sourceMaps": true,
            "cwd": "${workspaceRoot}"
        },
        {
            "name": "Run Browser",
            "type": "cordova",
            "request": "launch",
            "platform": "browser",
            "target": "chrome",
            "simulatePort": 8000,
            "livereload": true,
            "sourceMaps": true,
            "cwd": "${workspaceRoot}"
        }
    ]
}
![error](https://user-images.githubusercontent.com/12893320/36198293-2eed9458-119c-11e8-9292-1e310ed4828f.PNG)

**Comment by avinashbhalki** [comment]
Any Help appreciated, Many Thanks...

**Comment by sergey-akhalkov** [comment]
Hey guys @weinand, @avinashbhalki, could you please take a look at https://github.com/Microsoft/vscode-cordova/issues/368#issuecomment-364978435 and let me know if it helps?

**Comment by avinashbhalki** [comment]
@sergey-akhalkov @weinand  It's not working for me...

**Comment by lordneru** [comment]
Same happens here.

**Comment by ultimatetag** [comment]
Same issue here. For me, it looks like Cordova is putting the Android www build here:

My Ionic app scripts is putting Android platform here:

@ionic/app-scripts/dist/dev-server/serve-config.js:
exports.ANDROID_PLATFORM_PATH = path.join('platforms', 'android', 'app', 'src', 'main', 'assets', 'www');

But I think the simulator expects the folder to be here:
platforms/android/assets/www

Is there any way to pass the expected folder through the launch.json task?

**Comment by iTOYS** [comment]
Hi there,
We use `cordova-serve` under the hood to run simulation.
It has [PR](https://github.com/apache/cordova-serve/pull/6) to fix this issue.
We will update our dependency as soon as this PR will be merged and new release will be published.

As a workaround you can manually apply patch from a PR in your `node_modules` 

Thanks!

**Comment by iTOYS** [comment]
upd. Fixed there https://github.com/apache/cordova-serve/pull/7
