### ISSUE TITLE
v1.3.6 Debug adapter process has terminated unexpectedly

### ISSUE THREAD

**Issue by swindex** [Microsoft/vscode-cordova#380]
## Actual Behavior
1. When Trying to launch Debug on any configuration it fails with error: Debug adapter process has terminated unexpectedly

After rolling back to version 1.3.4 everything works

## Expected Behavior
1. Expect it to work

## Software versions
- Cordova VS Code extension version: 1.3.6
- VSCode version: 1.2.0.1
- OS platform and version: Win 10
- NodeJS version: latest
- Cordova version: latest
- Cordova-Android/iOS/Windows version: 

## Outputs (Include if relevant)
- Output of the Debug Console (View -> Toggle Debug Console):
```
2messageService.ts:126 Debug adapter process has terminated unexpectedly
e.doShow @ messageService.ts:126
e.show @ messageService.ts:105
_.onServerExit @ rawDebugSession.ts:535
(anonymous) @ rawDebugSession.ts:449
emitTwo @ events.js:111
emit @ events.js:194
__dirname.ChildProcess._handle.onexit @ internal/child_process.js:215

**Comment by max-mironov** [comment]
Hey there @swindex, thanks for feedback, could you please try new version [1.3.7](https://github.com/Microsoft/vscode-cordova/releases/tag/1.3.7) and let us know how it works?

**Comment by swindex** [comment]
Hi, Thanks for quick response. 
Don't know what to do with the link you provided (don't have time to figure out either)
I downloaded from https://marketplace.visualstudio.com/_apis/public/gallery/publishers/vsmobile/vsextensions/cordova-tools/1.3.7/vspackage

And it works.

**Comment by sergey-akhalkov** [comment]
Hi @swindex, so I'm closing this, please feel free to reopen if you have any questions or see any issues.
