### ISSUE TITLE
Option to hide "Login to App Center"

### ISSUE THREAD

**Issue by GitStorageOne** [Microsoft/vscode-cordova#381]
## Actual Behavior
1. "Login to App Center" always visible at the left bottom of vscode editor.

## Expected Behavior
1. Option to hide login button.

## Software versions
- Cordova VS Code extension version: 1.3.6
- VSCode version: 1.20.1

**Comment by max-mironov** [comment]
Hi @GitStorageOne and thanks for feedback. That really make sense to show this only when needed, so we've added logic to show appcenter statusbar only in case you have `cordova-plugin-code-push` installed. 
Here is the relative PR: https://github.com/Microsoft/vscode-cordova/pull/382
We are planning to release new update for extension soon. 

Thanks again and let is know if you see any issues or have more ideas how we can improve the product!

**Comment by max-mironov** [comment]
Released new version for vscode cordova extension, so closing the issue for now, please feel free to reach us if you have more questions.
