### ISSUE TITLE
Support building all Cordova supported platforms

### ISSUE THREAD

**Issue by rmeske** [Microsoft/vscode-cordova#388]
Currently you only have the option to build & debug a Cordova project for the iOS or Android platform.  Cordova support many other platforms including Windows Universal Apps.  To build for these other platforms you have to open a terminal window and use the CLI to build them.

At a minimum I would expect that building a Windows Universal App when running on the Windows platform would be a priority for Microsoft.

**Comment by gedw99** [comment]
i also would liek this to be better supported.
If its only at CLI level, then more docs on that woudl be great to get going.

**Comment by iTOYS** [comment]
Hi there,
Sorry for delay! Cordova tools support build for all available platforms with commands from command palette. In #407 added selection of specific target platform for commands prepare, build and run.

Unfortunately Cordova tools haven't support debug for platforms other than Android, iOS and Browser.

**Comment by iTOYS** [comment]
You can use VS2017 for debug windows platform
https://cordova.apache.org/docs/en/latest/guide/platforms/windows/
