### ISSUE TITLE
Editor Action Format Hotkey not working after using Build Hotkey

### ISSUE THREAD

**Issue by SimpleDeveloper49** [Microsoft/vscode-cordova#39]
Visual Studio Code on Mac, Shift + Alt + F for auto-format (editor.action.format) does not work after Shift + Command + B has been pressed to Cordova build the project.

To reproduce the error, open up the project, then:
1. Shift + Command + B
2. Click into a file (in my case JS), do a formatting change i.e. add spacing
3. Shift + Alt + F
4. No Change. (Unexpected)

Some further notes:
- I do exclude platforms folder using the settings.json
- Using Shift + Command + P and clicking Cordova Build will not trigger this bug
- Toggling output did not change behaviour
- Shift + Alt + F will work as expected after restart of visual studio code

**Comment by nisheetjain** [comment]
@meenakb can you please take a look

**Comment by meenakb** [comment]
@SimpleDeveloper49, Thanks for reporting this issue! What version of VS Code are you on?

**Comment by SimpleDeveloper49** [comment]
Version 0.10.8

**Comment by SimpleDeveloper49** [comment]
Created a new project and did not encounter this issue there. I wonder if it has something to do with the size of the project?

**Comment by meenakb** [comment]
@SimpleDeveloper49, Interesting. When you encounter the issue, can you please verify that your default keyboard shortcuts file (click on Code -> Preferences -> Keyboard Shortcuts) has the entry:

{ "key": "shift+alt+f",           "command": "editor.action.format",
                                     "when": "editorTextFocus" }

**Comment by SimpleDeveloper49** [comment]
Yes, the entry is still there. All other short cuts (broad statement, i know) seem to work correctly. 
I was able to reproduce it the day I posted it, as well over the weekend. 
However, today after a restart I am not able to reproduce this behaviour in the same project anymore. Not sure if the restart or resolved the issue, or if there was an update. Thanks

**Comment by meenakb** [comment]
@SimpleDeveloper49 Thanks, please let us know if you run into this issue again. I will go ahead and close this issue for now.

**Comment by vmachacek** [comment]
I have similar problem, suddenly editor.action.format command inst working. It's really frustrating. :(

**Comment by SimpleDeveloper49** [comment]
I still seem to encounter this issue on random, but can't reproduce it consistently. It's pretty odd. 

Definitely seems to occur more often on bigger solutions than it does on small adhoc ones.

**Comment by MSLaguana** [comment]
If you have this happen again, could you please try uninstalling our extension and re-opening the project and see if the problem persists?

**Comment by vmachacek** [comment]
By our extension you mean VSC? I reinstalled the whole thing, but that didn't helped. Than I restarted my Windows and that fixed the issue.

**Comment by MSLaguana** [comment]
I mean the cordova-tools extension:
![image](https://cloud.githubusercontent.com/assets/14098340/13301788/873aa166-dafb-11e5-8478-b0bf5520e9e2.png)

**Comment by SimpleDeveloper49** [comment]
For me a restart of VSC resolved the issue. However, then it might start again after using the short cut for build, in my case. Uninstalling VSC would resolve the issue, due to restart of VSC.

@vmachacek is that the similar behaviour you encounter?

**Comment by vmachacek** [comment]
Update, restarting Windows didnt fixed the issue

**Comment by vmachacek** [comment]
This is the code I'm trying to format. http://pastebin.com/G0t61pYv 

I don't have such a extension installed, I don't have any extensions installed in fact.

**Comment by SimpleDeveloper49** [comment]
@vmachacek you might be looking at the wrong github repository. Please reference https://github.com/Microsoft/vscode 

This is the repository for the cordova tools extension.

Regarding your problem:             
data: {
                stateType: Enums.StepType.Wizard,
                valid: false
            }

Is the issue I believe. Simply move the "}" a line below with enter, then try to re-format.

**Comment by vmachacek** [comment]
yeah, that helped, thank you! I'm just puzzled why do I have to care about this. Why would I have to preformat the text to make formatter work? 

I'm off to the https://github.com/Microsoft/vscode site.

**Comment by MSLaguana** [comment]
I just saw this happen myself, but in a non-cordova project which should not have triggered the extension. Uninstalling it fixed it, but I'll keep an eye out for it happening again.

It looked like the language service may have not been running, since once I restarted and auto format was working, it started showing some squigglies that I had not showed previously.

**Comment by meenakb** [comment]
When you say uninstalling it, do you mean the extension?

**Comment by MSLaguana** [comment]
Yes, I just removed the extension, but that also triggered vscode to restart so it may have just required a restart. I'm going to keep the extension uninstalled and see if it happens again.

**Comment by digeff** [comment]
I'm not sure if this is the same case, but I'm having the same issue with VS Code and I don't have any extension installed: https://github.com/Microsoft/vscode/issues/3652

**Comment by hamiltonia** [comment]
Close as this is an external issue. Please see Microsoft/vscode#3652
