### ISSUE TITLE
How to build for MaCOS or WIndows

### ISSUE THREAD

**Issue by gedw99** [Microsoft/vscode-cordova#390]
How can i build a MaxOS Cordova app ?

At the moment i am using VS2017 in order to build WIndows apps.
But to Build MacOS apps i see nothing...

Can you point me in the right direction. If MS dont support his then let me know rather than push me to some other forum please. I really need to get this working.

**Comment by iTOYS** [comment]
Hi @gedw99 
You can build osx apps only on MacOS system. Please see [requirements](https://cordova.apache.org/docs/en/latest/guide/platforms/osx/#requirements-and-support)
You cant build it on a Windows.

Thanks!
