### ISSUE TITLE
ionic serve option only works if you include cordova

### ISSUE THREAD

**Issue by MolallaComm** [Microsoft/vscode-cordova#392]
When creating ionic projects, newer versions of "ionic start" default to not including cordova (it ask you if you want to include cordova and defaults to no).  If you accept the default to not include cordova and later setup the project for debugging with this extension using the "Serve to the browser (ionic serve)" option - when you click the Debug button, vscode just hangs and never kicks off anything at least on windows.  It took me about an hour to figure this out - I did "ionic cordova prepare", restarted vscode, and everything started working fine.  Would be nice if you added a check for this to save others undoubtedly running into it in the future and scratching their heads like I did - particularly when i could tab over to Terminal and run "ionic serve" on the project with no problem.

**Comment by iTOYS** [comment]
Hi @MolallaComm, thanks for reaching us!
This issue fixed in #401
Will be available when new version of a extension will be released!
