### ISSUE TITLE
Endless loop when running on android

### ISSUE THREAD

**Issue by SpellCraft** [Microsoft/vscode-cordova#393]
## Actual Behavior
1. Press "Run Android on Emulator (AppName)" Hotkey (F5)
2. Emulator starts, and an endless loop of:
```
Command finished with error code 1: D:\Users\Nadeko\AppData\Local\Android\Sdk\platform-tools\adb.exe -s,emulator-5584,shell,getprop,dev.bootcomplete
Running adb shell command "getprop dev.bootcomplete" on target emulator-5584...
```
occurs until I run the command "adb kill-server"

## Expected Behavior
1. Press "Run Android on Emulator (AppName)" Hotkey (F5)
2. Wait for the emulator to launch and vscode to attach to the app

## Software versions
- Cordova VS Code extension version: 1.3.8
- VSCode version: 1.22.2
- OS platform and version: Windows 10 Pro Version 1709 (OS Build 16299.371)
- NodeJS version: 9.5.0
- Cordova version: 8.0.0
- Cordova-Android/iOS/Windows version: Cordova-Android 6.4.0

## Outputs (Include if relevant)
- Output of the Debug Console (View -> Toggle Debug Console):
```
https://pastebin.com/xm4vP0qD
```
- Output of the Cordova output channel (View -> Toggle Output -> Select Cordova in ListBox):
```
https://i.imgur.com/b1eZgTO.png
```
- Output of the Developer Tools console (Help -> Toggle Developer Tools -> Select Console tab):
```
console.ts:136 [Extension Host] vscode-icons is active!
console.ts:136 [Extension Host] rejected promise not handled within 1 second
t.log @ console.ts:136
log.ts:171   ERR An unknown error occurred. Please consult the log for more details.
console.ts:136 [Extension Host] (node:14364) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
t.log @ console.ts:136
console.ts:136 [Extension Host] No editors associated with document: d:\Users\Nadeko\Documents\GitHub\GoMap\.vscode\settings.json
t.log @ console.ts:136
```

## Bonus (My launch.json)
https://pastebin.com/EQ6dLWQJ

**Comment by iTOYS** [comment]
Hi @SpellCraft 
Could you please check if `cordova run android --emulator` works from command line?

**Comment by SpellCraft** [comment]
Hello!

Sorry for not replying sooner. I can run android just fine from the CLI, but this tends to happen when the emulator is already running and having been idle for a little while or the first time I start it.

What seems to work for me though if the emulator is running is to delete my app from the android emulator, then it suddenly loads the app again.

**Comment by iTOYS** [comment]
Sorry, but I can't reproduce this issue, all works wine with already run emulator. Some issue may occurs while emulator starting, we have timeout to emulator start to prevent stuck!

Thanks!
