### ISSUE TITLE
Separate output window on each Cordova:Run command

### ISSUE THREAD

**Issue by benshabatnoam** [Microsoft/vscode-cordova#396]
## Actual Behavior
Running command Cordova:Run is lunching new output window

## Expected Behavior
Running the command will overwrite the current output window if exists

## Software versions
- Cordova VS Code extension version: 1.3.9
- VSCode version: 1.22.2
- OS platform and version: Windows 10 Enterprise 2016 LTSB
- NodeJS version: v8.9.4
- Cordova version: 8.0.0
- Cordova-Android version: 7.0.0

thanks

**Comment by iTOYS** [comment]
Hi @benshabatnoam, thank you for reaching us!
Fix already in PR :)
