### ISSUE TITLE
Automatic reload of ionic changes when simulate Androind in browser

### ISSUE THREAD

**Issue by Amosss** [Microsoft/vscode-cordova#398]
Hi

My launch.json section for simulating Android in browser looks like this:
{
            "name": "Simulate Android in browser",
            "type": "cordova",
            "request": "launch",
            "platform": "android",
            "target": "chrome",
            "simulatePort": 8000,
            **"livereload": true,**
            "sourceMaps": true,            
            "cwd": "${workspaceRoot}"
        },

When making any changes in html/ts, nothing is happening on the browser side until I run ionic serve again. When doing so, a new browser/tab opens up with the changes and since then, the "play" also generates the "new" version.

When running in "run browser" mode, everything is updated as expected.
{
            "name": "Run Browser",
            "type": "cordova",
            "request": "launch",
            "platform": "browser",
            "target": "chrome",
            "simulatePort": 8000,
            "livereload": true,
            "sourceMaps": true,            
            "cwd": "${workspaceRoot}"
        }

**Comment by iTOYS** [comment]
Hi @Amosss 
Could you please fill issue by [template](https://github.com/Microsoft/vscode-cordova/blob/master/.github/ISSUE_TEMPLATE.md)

Thanks!

**Comment by iTOYS** [comment]
Closing now! Feel free to reopen and fill by [template](https://github.com/Microsoft/vscode-cordova/blob/master/.github/ISSUE_TEMPLATE.md) if you still have this issue!

Thanks!
