### ISSUE TITLE
Is it possible to use remotebuild with VS Code?

### ISSUE THREAD

**Issue by avargaskun** [Microsoft/vscode-cordova#40]
I'm currently using VS2015 Community Edition on Windows, targetting iOS using remotebuild on a remote mac server. Is it possible to achieve this same setup with VS Code? I haven't found any documentation making reference to such setup.

**Comment by MSLaguana** [comment]
Right now we don't support integration with remotebuild from vscode. You could set up a `task.json` task to invoke taco and build remotely, but you will not be able to debug from another machine using vscode.

**Comment by avargaskun** [comment]
Thank you for the quick reply. I will look into seting up the custom build task for that. Any pointers to previous efforts to set this up are appreciated :)

**Comment by MSLaguana** [comment]
Here's a rough outline of how to proceed

1. First install taco: `npm install -g taco-cli`
2. Then configure it to talk with remotebuild: `taco remote add ios`, then follow the prompts to point it at your remotebuild instance
3. Test that it works: in a Cordova project, run `taco build ios` and make sure that the project is built
4. Configure a tasks.json if you haven't already: https://code.visualstudio.com/Docs/editor/tasks

    You could also look at the .vscode/tasks.json in this repository to see how a gulp-based tasks.json can look.
5. Make sure that whatever task you set up eventually calls `taco build ios` or `taco build ios --device` or `taco run ios` etc as appropriate

**Comment by avargaskun** [comment]
Thanks for the hints! In the end I arrived to this [gulpfile.zip](https://github.com/Microsoft/vscode-cordova/files/129130/gulpfile.zip) which does just what I need.
