### ISSUE TITLE
Ripple integration

### ISSUE THREAD

**Issue by CKGrafico** [Microsoft/vscode-cordova#41]
Are you planning ripple or Microsoft Android emulator support?
At the moment are very different the experiences with Cordova Tools for Visual Studio and Cordova Tools for VS Code :/

**Comment by axemclion** [comment]
@CKGrafico We are investigating some sort of a browser based workflow for the extension. This could be Ripple, or could be something as simple as opening the browser. Given that you mentioned Ripple, how important is 

1. Device events like `ondeviceready`, `onPause`, etc for you ? if we simply open a browser without Ripple, those events will not be fired. 
2. How important is plugin simulation. While Ripple does that, a simple browser may now.

I am trying to see how many people want the above 2 features, and depending on that, we could support Ripple or browser. 

Regarding Microsoft Android emulator support, we have a [new issue](https://github.com/Microsoft/vscode-cordova/issues/47). For the minute, we plan only to add documentation that explains how to launch the Microsoft emulator. Was there something else you were looking for ?

**Comment by CKGrafico** [comment]
Perfect thanks

**Comment by hamiltonia** [comment]
Close as we're not planning to add support for Ripple. Also not planning direct support for the MSFT Android Emulator right now.
