### ISSUE TITLE
Add support for local installation of Cordova/Ionic

### ISSUE THREAD

**Issue by Takkuz** [Microsoft/vscode-cordova#416]
I'm actually  not using global version of Ionic and Cordova and it would be great if (I'm not using global packages at all), before running the command for the "launch" request it should be great adding `node_modules/.bin` as first element on local PATH, as NPM does when running `npm run something`.

## Actual Behavior
1. Not having Cordova or Ionic installed as `--global` but as a project modules
2. You could run them adding as a NPM script in `package.json`  
`"ionic": "ionic"`  
and then  
`npm run ionic cordova run android`
3. Run VSCode debug with "launch" request action with base configuration
4. Receive an error: "ionic ENOENT"

## Expected Behavior
4. Having it run!

## Software versions
- Cordova VS Code extension version: 1.3.10
- VSCode version: 1.24.0
- OS platform and version: Ubuntu 18.04
- NodeJS version: 8.11.1
- Cordova version: 8.0.0

## Outputs (Include if relevant)
- Output of the Debug Console (View -> Toggle Debug Console):
```
Launching for android (This may take a while)...
spawn ionic ENOENT
```

**Comment by iTOYS** [comment]
Hi @Takkuz 
We already have the same issue#181! I'm close this issue as a duplicated.
Thanks!
