### ISSUE TITLE
Any way to specify folder ?

### ISSUE THREAD

**Issue by ph55** [Microsoft/vscode-cordova#420]
I have mono-repository project where cordova `www` folder compiled inside nested directory.
So the project structure is something like this:

```
root
+--apps
     +--app-one-web
     +--app-one-mobile
+--cordova-builds
     +--app-one-mobile
         +--www
```

Any way to specify in `launch.json` too "look" inside `cordova-builds/app-ono-mobile` folder ?
This one doesn't work:
```
{
    ...
    "cwd": "${workspaceRoot}/cordova-builds/app-one-mobile"
}
```

**Comment by iTOYS** [comment]
Hi @ph55,
Unfortunately it's impossible for now. VSCode Cordova extension requires the workspace root to be your Cordova project's root.
