### ISSUE TITLE
Can't debug well

### ISSUE THREAD

**Issue by jmorelos96** [Microsoft/vscode-cordova#425]
Issue Type: <b>Bug</b>

When i start running in my android through the plugin of cordova tools i cant debug, but if i choose attach android it can debug just in that way, this error happens when i update my visual code version to a newest

Extension version: 1.4.0
VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4510U CPU @ 2.00GHz (4 x 2594)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|11.93GB (6.13GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by redwolf2** [comment]
See this post: https://github.com/Microsoft/vscode-cordova/issues/422
In short: It is fixed, but there is no new release.

**Comment by SounD120** [comment]
Hi @jmorelos96. Could you please describe error you facing?

**Comment by jmorelos96** [comment]
I haven't seen that issue anymore.

**Comment by SounD120** [comment]
Closing now! Feel free to reopen and fill by [template](https://github.com/Microsoft/vscode-cordova/blob/master/.github/ISSUE_TEMPLATE.md) if you still have this issue!

Thanks!
