### ISSUE TITLE
Error Debugging on Any Configurations

### ISSUE THREAD

**Issue by realivanjx** [Microsoft/vscode-cordova#427]
Hi,

When im trying to run cordova app (android device or browser), this error message comes up:

![screenshot_10](https://user-images.githubusercontent.com/12814796/45552720-109c9780-b85c-11e8-8598-f69fe7effe1c.png)

Also here is my project structure:

![screenshot_8](https://user-images.githubusercontent.com/12814796/45552777-3164ed00-b85c-11e8-82aa-45dde8fdbc21.png)

available options:

![screenshot_9](https://user-images.githubusercontent.com/12814796/45552946-ac2e0800-b85c-11e8-8086-195e509d5bf3.png)

and the `launch.json` file:

```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Run Android on device",
            "type": "cordova",
            "request": "launch",
            "platform": "android",
            "target": "device",
            "port": 9222,
            "sourceMaps": true,
            "cwd": "${workspaceFolder}/src",
            "ionicLiveReload": false
        },
        {
            "name": "Run iOS on device",
            "type": "cordova",
            "request": "launch",
            "platform": "ios",
            "target": "device",
            "port": 9220,
            "sourceMaps": true,
            "cwd": "${workspaceFolder}/src",
            "ionicLiveReload": false
        },
        {
            "name": "Attach to running android on device",
            "type": "cordova",
            "request": "attach",
            "platform": "android",
            "target": "device",
            "port": 9222,
            "sourceMaps": true,
            "cwd": "${workspaceFolder}/src"
        },
        {
            "name": "Attach to running iOS on device",
            "type": "cordova",
            "request": "attach",
            "platform": "ios",
            "target": "device",
            "port": 9220,
            "sourceMaps": true,
            "cwd": "${workspaceFolder}/src"
        },
        {
            "name": "Run Android on emulator",
            "type": "cordova",
            "request": "launch",
            "platform": "android",
            "target": "emulator",
            "port": 9222,
            "sourceMaps": true,
            "cwd": "${workspaceFolder}/src",
            "ionicLiveReload": false
        },
        {
            "name": "Run iOS on simulator",
            "type": "cordova",
            "request": "launch",
            "platform": "ios",
            "target": "emulator",
            "port": 9220,
            "sourceMaps": true,
            "cwd": "${workspaceFolder}/src",
            "ionicLiveReload": false
        },
        {
            "name": "Attach to running android on emulator",
            "type": "cordova",
            "request": "attach",
            "platform": "android",
            "target": "emulator",
            "port": 9222,
            "sourceMaps": true,
            "cwd": "${workspaceFolder}/src"
        },
        {
            "name": "Attach to running iOS on simulator",
            "type": "cordova",
            "request": "attach",
            "platform": "ios",
            "target": "emulator",
            "port": 9220,
            "sourceMaps": true,
            "cwd": "${workspaceFolder}/src"
        },
        {
            "name": "Serve to the browser (ionic serve)",
            "type": "cordova",
            "request": "launch",
            "platform": "serve",
            "cwd": "${workspaceFolder}/src",
            "devServerAddress": "localhost",
            "sourceMaps": true,
            "ionicLiveReload": true
        },
        {
            "name": "Simulate Android in browser",
            "type": "cordova",
            "request": "launch",
            "platform": "android",
            "target": "chrome",
            "simulatePort": 8000,
            "livereload": true,
            "sourceMaps": true,
            "cwd": "${workspaceFolder}/src"
        },
        {
            "name": "Simulate iOS in browser",
            "type": "cordova",
            "request": "launch",
            "platform": "ios",
            "target": "chrome",
            "simulatePort": 8000,
            "livereload": true,
            "sourceMaps": true,
            "cwd": "${workspaceFolder}/src"
        },
        {
            "name": "Run Browser",
            "type": "cordova",
            "request": "launch",
            "platform": "browser",
            "target": "chrome",
            "simulatePort": 8000,
            "livereload": true,
            "sourceMaps": true,
            "cwd": "${workspaceFolder}/src"
        }
    ]
}
```

Any suggestions?

**Comment by redwolf2** [comment]
This is a dublicate of https://github.com/Microsoft/vscode-cordova/issues/422, which is already resolved.

But sadly there is no current release (1.4.0 is the current), that has the fix.

**Comment by realivanjx** [comment]
Thanks for the quick reply but he uses ionic. In this case I don't use anything yet just plain html file.

**Comment by realivanjx** [comment]
is that matter?

**Comment by redwolf2** [comment]
Sry, I deleted my answer, because it was missleading. What happens if you try "cordova run android" from console.

Make sure you have cordova and android installed

`npm install -g cordova`
`cordova platforms add android@7.1.1`

**Comment by realivanjx** [comment]
`cordova run android` returns `LAUNCH SUCCESS` at the end but the debugger wont start. Only the app on the android that runs automatically. The error still persist when I hit `F5`.

**Comment by realivanjx** [comment]
here is my `config.xml`:

'''
<?xml version='1.0' encoding='utf-8'?>
<widget id="io.cordova.hellocordova" version="1.0.0" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">
    <name>Test</name>
    <description>
        Test
    </description>
    <author email="me@mail.com">
        Test
    </author>
    <content src="index.html" />
    <access origin="*" />
    <allow-intent href="http://*/*" />
    <allow-intent href="https://*/*" />
    <allow-intent href="tel:*" />
    <allow-intent href="sms:*" />
    <allow-intent href="mailto:*" />
    <allow-intent href="geo:*" />
    <platform name="android">
        <allow-intent href="market:*" />
        <icon src="res/icons/logo.png" />
    </platform>
    <platform name="ios">
        <allow-intent href="itms:*" />
        <allow-intent href="itms-apps:*" />
        <icon src="res/icons/logo.png" />
    </platform>
    <preference name="android-minSdkVersion" value="21" />
    <preference name="android-targetSdkVersion" value="25" />
    <preference name="SplashScreen" value="none" />
    <plugin name="cordova-plugin-whitelist" spec="1" />
    <plugin name="cordova-plugin-splashscreen" spec="^5.0.2" />
    <plugin name="cordova-plugin-qrscanner" spec="^2.6.0" />
    <plugin name="cordova-plugin-x-toast" spec="^2.7.0" />
    <engine name="android" spec="^7.0.0" />
</widget>

'''

**Comment by realivanjx** [comment]
but is there any way to automate cordova run android and the attachement process?

**Comment by redwolf2** [comment]
Yes, "Run Android on device" is the way to do it and it should've worked. So this issue is fine with me.

If nothing goes, another option is to use Chrome. Open it, go into the Developer Tools. Press "More Tools", "Remote Devices". Look for your device (Developer Mode and ADB Debugging must be enabled on the device and it must be attached to the PC via USB and `adb devices` must list the device as attached). Press "Inspect" to debug the remote chrome webview.

**Comment by realivanjx** [comment]
well `Run Android on device` still throwing the same error

**Comment by realivanjx** [comment]
only the attaching that works

**Comment by redwolf2** [comment]
Also check out if this helps:

https://github.com/Microsoft/vscode-cordova/issues/368#issuecomment-385862862
https://github.com/Microsoft/vscode-cordova/issues/368#issuecomment-392140576

**Comment by realivanjx** [comment]
all fixed. I just moved all `src` folder content into the folder's root folder.
