### ISSUE TITLE
ionic 4

### ISSUE THREAD

**Issue by shahramSo** [Microsoft/vscode-cordova#429]
## Actual Behavior
1.
2.

## Expected Behavior
1.
2.

## Software versions
- Cordova VS Code extension version:
- VSCode version:
- OS platform and version:
- NodeJS version:
- Cordova version:
- Cordova-Android/iOS/Windows version:

## Outputs (Include if relevant)
- Output of the Debug Console (View -> Toggle Debug Console):
```
PASTE OUTPUT HERE
```
- Output of the Cordova output channel (View -> Toggle Output -> Select Cordova in ListBox):
```
PASTE OUTPUT HERE
```
- Output of the Developer Tools console (Help -> Toggle Developer Tools -> Select Console tab):
```
PASTE OUTPUT HERE
```

**Comment by SounD120** [comment]
Hi @shahramSo and thanks for reaching us. I'm closing this issue for now, but you free to reopen it and adding some details about your question using our [issue template](https://github.com/Microsoft/vscode-cordova/blob/master/.github/ISSUE_TEMPLATE.md).
