### ISSUE TITLE
Breakpoints are not hit when debugging in iOS simulator

### ISSUE THREAD

**Issue by sdurandeu** [Microsoft/vscode-cordova#43]
Hi. When launching the app from Visual Studio Code, using the `Run iOS simulator` option, the breakpoints are not hit. I'm using the Cordova Hello World app and `ios-webkit-debug-proxy` is installed and running in `http://localhost:9220/`. 
More data:

- I´ve tested using the Android emulator and breakpoints work.
- I´ve also tested using Web Inspector from Safari into the simulator and the debugging works there.

Output from the `http://localhost:9223/` URL as listed in `http://localhost:9220/`:
```
Inspectable pages for SIMULATOR:

    * file:///Users/sdurandeu/Library/Developer/CoreSimulator/Devices/10790EE6-1B12-42D3-A7B8-6C2BD536C06B/data/Containers/Bundle/Application/978974A6-1777-41F7-A994-C503AF1D1BC8/HelloCordova.app/www/index.html
```
I'm using OSX El Capitan and iOS 9.1 device. Any ideas?

**Comment by MSLaguana** [comment]
What kind of project are you trying to debug? Is it a plain javascript cordova project, or is it something that involves sourcemaps? And where are you attempting to set breakpoints? Is it on an event that you trigger later on, or something that happens shortly after the application starts?

**Comment by sdurandeu** [comment]
All good questions. It was indeed an issue with the location of the breakpoints. We were placing the breakpoints in locations where the application was being initialized. When we placed a breakpoint in a new onclick handler, then it worked.

We were using the plain cordova app obtained out-of-the-box when running `cordova create MyApp`.

Thanks!!
