### ISSUE TITLE
Error: Project does not include the specified platform: android occurs during Android simulation scenario

### ISSUE THREAD

**Issue by ruslan-bikkinin** [Microsoft/vscode-cordova#438]
## Steps to reproduce
1. Use machine with case-sensitive file system like ext4 (Ubuntu 16.04 uses it by default)
2. Start "Simulate Android in browser" on working project

## Actual Behavior
1. `Error: Project does not include the specified platform: android` appears in Debug Console

## Expected Behavior
1. No error appeared

## Explanation
Error caused by bug in [cordova-serve](https://github.com/apache/cordova-serve/) and [a fix](https://github.com/apache/cordova-serve/pull/10) for it has already been merged into master. As soon as new version of cordova-serve will be released, we should use it in extension.
Those who want to make android simulation work now can manually apply fix inside `~/.vscode/extensions/vsmobile.cordova-tools-*/node_modules/cordova-serve` and restart VS Code.

**Comment by ruslan-bikkinin** [comment]
Hi @chuanner, we are waiting for cordova team to release a patch for this, so we could update it in our package.json. Unless they release a new version we can't propose a fix, unfortunately. We will get in touch with cordova folks to ask them to get hurry.

**Comment by ajck** [comment]
@ruslan-bikkinin Was there ever a solution to this that I could apply manually? I am running the latest version of VSCode 1.63.2 with the latest version of Cordova Tools extension 2.4.1 on Windows 10, and have it set to "Simulate Android in the browser" but when clicking the Start Debugging icon, I still get the "Error: Project does not include the specified platform: android" in the Debug Console.

**Comment by RedMickey** [comment]
Hi @ajck, [this issue](https://github.com/microsoft/vscode-cordova/issues/737) could be related the `"Error: Project does not include the specified platform: android"`. [Here](https://github.com/microsoft/vscode-cordova/issues/737#issuecomment-921894375) you can find steps to fix this problem manually.
