### ISSUE TITLE
Problem with cordova plugin in VS CODE

### ISSUE THREAD

**Issue by MarekWaw** [Microsoft/vscode-cordova#45]
I run VS CODE and I am trying to install extention in our intranet environment (proxy). I have got error:
**getaddrinfo ENOTFOUND proxy.coig.com:3128 proxy.coig.com:3128:3128** without success.
What can I do?

**Comment by MSLaguana** [comment]
When does this happen? when you try to `ext install` the extension? And did you manually configure the proxy in vscode or is it a systemwide setting?

From the error message it looks like it including the proxy port in the hostname which may be causing the error.

**Comment by digeff** [comment]
@MarekWaw Are you still having this issue? If not we'll close this.

**Comment by hamiltonia** [comment]
Please reopen if you're still having issues.
