### ISSUE TITLE
[cordova-tools] Error processing "launch" error... prevents from debugging Android app

### ISSUE THREAD

**Issue by angel1st** [Microsoft/vscode-cordova#458]
Hi there, I am using the plugin quite a while and recently, I have received the issue, described below. There are two environmental changes made, which might cause the bug - I have updated VS Code and cordova. The current versions are described below.

## Actual Behavior
While trying to debug Android app, I see nothing in debug console during the build process. At the end, I have the following error:

![vsc-cordova](https://user-images.githubusercontent.com/8547131/49210515-ef146c00-f3c5-11e8-83d4-c11e5121b459.png)

## Expected Behavior
To have the app build, installed in the device / emulator and get it debugged.

## Software versions
- Cordova VS Code extension version: 1.5.1
- VSCode version: 1.29.1
- OS platform and version: Windows 10 Home / x64
- NodeJS version: 10.5.0
- Cordova version: 8.1.2
- Cordova-Android version: 7.1.0

## Outputs (Include if relevant)
- Output of the Debug Console (View -> Toggle Debug Console):
```
Empty
```
- Output of the Cordova output channel (View -> Toggle Output -> Select Cordova in ListBox):
```
NA
```
- Output of the Developer Tools console (Help -> Toggle Developer Tools -> Select Console tab):
```
Nothing is reported there
```

**Comment by angel1st** [comment]
Thanks for the answer, @ruslan-bikkinin. Yes indeed, once 
> `cordova.cmd run android --device --verbose --no-update-notifier` 

command is executed, I can see the log. Here  it is:
````
Running command: adb.exe devices
Command finished with error code 0: adb.exe devices
Running adb shell command "cat /proc/cpuinfo" on target localhost:5555...
Running command: adb.exe -s localhost:5555 shell cat /proc/cpuinfo
adb timed out while detecting device/emulator architecture. Killing adb and trying again.
Running command: cmd "/s /c "killall adb""
Command finished with error code 1: cmd /s /c "killall adb"
Device communication timed out. Try unplugging & replugging the device.
CordovaError: Device communication timed out. Try unplugging & replugging the device.
    at Object.module.exports.detectArchitecture (project\platforms\android\cordova\lib\build.js:183:35)
    at project\platforms\android\cordova\lib\device.js:65:22
    at _fulfilled (project\platforms\android\cordova\node_modules\q\q.js:854:54)
    at project\platforms\android\cordova\node_modules\q\q.js:883:30
    at Promise.promise.promiseDispatch (project\platforms\android\cordova\node_modules\q\q.js:816:13)
    at project\platforms\android\cordova\node_modules\q\q.js:624:44
    at runSingle (project\platforms\android\cordova\node_modules\q\q.js:137:13)
    at flush (project\platforms\android\cordova\node_modules\q\q.js:125:13)
    at process._tickCallback (internal/process/next_tick.js:61:11)
Command finished with error code 0: adb.exe -s,localhost:5555,shell,cat,/proc/cpuinfo
````

So it seems, the issue is related to `adb.exe -s localhost:5555 shell cat /proc/cpuinfo` command. In addition - I can see following warning, reported into emulator log:
````
WARNING: AsyncSocketServer.cpp:99: Error when accepting host connectionError message: Unknown error
````

However, when I try `adb.exe -s localhost:5555 shell cat /proc/cpuinfo` into a terminal, I can see its output w/o any problem. 

Also - I have no issue to connect & debug my app via Chrome Development console, so basically VS Code from dev environment, turned out to a simple text editor, which is quite sad. And cordova-tools are useless ATM.

Please let me know shall you need any further feedback.

**Comment by angel1st** [comment]
@ruslan-bikkinin, yes, I am facing this when running on emulator, however, I was able to face this, when running on actual device, connected via USB cable. 
Here is the debug config:
```
{
            "name": "Run Android on device",
            "type": "cordova",
            "request": "launch",
            "platform": "android",
            "target": "device",
            "port": 9222,
            "sourceMaps": true,
            "cwd": "${workspaceRoot}",
            "ionicLiveReload": false
}
```
since, I am using **Run Android on device** config, this is what I am sharing with you, Let me know, shall you need the entire config file.

**Comment by ruslan-bikkinin** [comment]
@angel1st seems to be that your problem relates to known cordova emulate issue. We are using `cordova emulate` command under the hood to build and run app on Android emulator. In some cases, this command works unstable and error like yours is appeared. The origin of the error is coming from `cordova-lib`: https://github.com/apache/cordova-lib/blob/da4b4b371203777d1f951ee9580c1348ddb36659/spec/plugman/projects/android/cordova/lib/build.js#L177

Please, try to reset state of your emulator, make sure that you have migrated to new cordova version correctly and try again.

**Comment by angel1st** [comment]
@ruslan-bikkinin - thanks for the feedback. Unfortunately none of the above fixed the issue. In fact I even created a completely new project and added debug configuration for it and yet the error persists.

I can confirm however `cordova` is installed correctly and I have no issue to compile the project using it as well as to debug it via Chrome dev. console. 
Hence my understanding is the issue is buried somewhere between VS Code and your plugin.

**Comment by ruslan-bikkinin** [comment]
@angel1st just in case, are you trying to run it on emulator from the Android Studio, not on the external emulator like Genymotion? If so, then you should use `Run Android on emulator` debug configuration:
```js
        {
            "name": "Run Android on emulator",
            "type": "cordova",
            "request": "launch",
            "platform": "android",
            "target": "emulator",
            "port": 9222,
            "sourceMaps": true,
            "cwd": "${workspaceFolder}",
            "ionicLiveReload": false
        },
```

**Comment by angel1st** [comment]
@ruslan-bikkinin - I am running the emulator from the command prompt, by executing:
> emulator -avd Nexus_5_API_26

**Comment by ruslan-bikkinin** [comment]
@angel1st thanks for clarification, you should use `Run Android on emulator` instead of `Run Android on device` then. Please try it and let us know if it works for you.

**Comment by angel1st** [comment]
@ruslan-bikkinin - thanks, mate, the last suggestion did the trick! I can recall when I started using cordova-tools, `run Android on emulator` didn't work. Now it seems it works.
The only minor issue left is - during the compile, I am not able to see the output into the debug console - instead I see it, once the debug starts.
I don't consider this as a critical by any means, hence you can close the issue.

Thanks again!

**Comment by ruslan-bikkinin** [comment]
@angel1st glad to hear your issue is resolved. As for logging issue - it seems to be a VS Code one since they started to add multi output for Debug Console in 1.29. We checked the latest Insiders build and we saw no problem with Debug Console there, so I assume in 1.30 the issue will be resolved automatically.

Don't hesitate to turn to us the next time if you have any questions.

**Comment by chibisuke** [comment]
I'm having nearly the same issue, but with a real device, so swiching to "Run on Emulator" does not work. 

And hints on how to troubleshoot this?
```

Command finished with error code 0: c:\Users\rh\AppData\Local\Android\Sdk\platform-tools\adb.exe devices
Running adb shell command "cat /proc/cpuinfo" on target 192.168.3.35:5678...
adb timed out while detecting device/emulator architecture. Killing adb and trying again.
Command finished with error code 1: cmd /s /c "killall adb"
(node:18240) UnhandledPromiseRejectionWarning: CordovaError: Device communication timed out. Try unplugging & replugging the device.
    at Object.module.exports.detectArchitecture (C:\data\Source\Workspaces\eApps 2\eApps2Aktu\platforms\android\cordova\lib\build.js:175:35)
    at C:\data\Source\Workspaces\eApps 2\eApps2Aktu\platforms\android\cordova\lib\device.js:65:22
    at _fulfilled (C:\data\Source\Workspaces\eApps 2\eApps2Aktu\platforms\android\cordova\node_modules\q\q.js:854:54)
    at C:\data\Source\Workspaces\eApps 2\eApps2Aktu\platforms\android\cordova\node_modules\q\q.js:883:30
    at Promise.promise.promiseDispatch (C:\data\Source\Workspaces\eApps 2\eApps2Aktu\platforms\android\cordova\node_modules\q\q.js:816:13)
    at C:\data\Source\Workspaces\eApps 2\eApps2Aktu\platforms\android\cordova\node_modules\q\q.js:624:44
    at runSingle (C:\data\Source\Workspaces\eApps 2\eApps2Aktu\platforms\android\cordova\node_modules\q\q.js:137:13)
    at flush (C:\data\Source\Workspaces\eApps 2\eApps2Aktu\platforms\android\cordova\node_modules\q\q.js:125:13)
    at process._tickCallback (internal/process/next_tick.js:61:11)
(node:18240) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:18240) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Command finished with error code 0: c:\Users\rh\AppData\Local\Android\Sdk\platform-tools\adb.exe -s,192.168.3.35:5678,shell,cat,/proc/cpuinfo
```

**Comment by chibisuke** [comment]
after digging into the code, this seams to be a cordova issue. Increasing in the timeout in platforms/android/cordova/lib/build.js:175 resolves the issue.

**Comment by Lertis** [comment]
Try to allow developer mode on your device. Find the point smth like "USB setup" and toggle the button to add permission for your PC. After that, I saw the notification on the PC display and success connection.

**Comment by GimpArm** [comment]
I ran into the same problem. What I can tell the timeout is 1000 ms before throwing the error. Sometimes the device can take 2 or 3 seconds to completely finish the adb shell command call. Changing the timeout to 10000 ms makes everything work. I suggest you increase this timeout to allow for devices on networks and slower connections.

`return helper().timeout(1000, new CordovaError('Device communication timed out. Try unplugging & replugging the device.')).then(null, function (err) {`
