### ISSUE TITLE
Ionic 4 debug not working with version 1.6.0

### ISSUE THREAD

**Issue by srishmawi** [Microsoft/vscode-cordova#459]
## Actual Behavior
1. Click on debug "Serve to browser"
2. After couple of seconds a popup message appears "The ionic live reload server existed unexpectedly"
 
## Expected Behavior
1. Browser should start and open the app

## Software versions
- Cordova VS Code extension version: 1.6.0
- VSCode version: 1.29.1
- OS platform and version: Windows 10
- NodeJS version: v10.13.0
- Cordova version: 6.4.0
- Cordova-Android/iOS/Windows version:

I had no issues to previous version ( 1.5.1 ) 
I can run the app using "ionic serve" from command line.

## Outputs (Include if relevant)
Related config
        {
            "name": "Serve to the browser (ionic serve)",
            "type": "cordova",
            "request": "launch",
            "platform": "serve",
            "cwd": "${workspaceFolder}",
            "devServerAddress": "localhost",
            "sourceMaps": false,
            "ionicLiveReload": false
        }
- Output of the Developer Tools console (Help -> Toggle Developer Tools -> Select Console tab):
console.ts:134 [Extension Host] rejected promise not handled within 1 second
t.log @ console.ts:134
t._logExtensionHostMessage @ extensionHost.ts:437
(anonymous) @ extensionHost.ts:244
emitTwo @ events.js:126
emit @ events.js:214
emit @ internal/child_process.js:772
_combinedTickCallback @ internal/process/next_tick.js:141
_tickCallback @ internal/process/next_tick.js:180
log.ts:169   ERR An unknown error occurred. Please consult the log for more details.
console.ts:134 [Extension Host] (node:16568) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.

**Comment by srishmawi** [comment]
I did these steps and now it works again

1. npm update -g

2. Got error 
    npm ERR! 404 Not found : vs-tac
    npm ERR! 404
     npm ERR! 404  'vs-tac' is not in the npm registry.

3. npm uninstall -g vs-tac
4. npm update -g

**Comment by mingdong88** [comment]
How to previous version ( 1.5.1 )

**Comment by mingdong88** [comment]
Please give me previous version ( 1.5.1 ) vsix. Thanks!
Email:mingdong88@163.com

Best Regards
Ming dong

**Comment by SounD120** [comment]
Hi @srishmawi . Thanks for reaching us, I'm glad to hear that you found a core of the problem, but I want to clarify, is the issue were solved completely? Maybe you have some questions to ask?

Hi @mingdong88. Thanks for contacting us. Looks like you already created an issue connected to [your request](https://github.com/Microsoft/vscode-cordova/issues/461) so we can move our conversation there.

**Comment by srishmawi** [comment]
It might be a separate, but in version 1.5.1 and 1.6.0 I have an issue where starting debug once works and the next fails and so on, with same error as in this ticket.

thanks

**Comment by srishmawi** [comment]
@SounD120 Ok thanks
See screenshot as requested

<img width="489" alt="debug-issue" src="https://user-images.githubusercontent.com/45515895/49366921-39ae2500-f6f3-11e8-85cc-0e9b0bc9d0fd.PNG">

**Comment by SounD120** [comment]
Thanks @srishmawi . Could you please try to increase Ionic dev server timeout and let us know does it works for you?

**Comment by srishmawi** [comment]
I already did that..
I will keep you updated.

**Comment by srishmawi** [comment]
@SounD120 I'm unable to reproduce anymore.
thanks for help.

**Comment by SounD120** [comment]
@srishmawi , glad to hear it. I'm closing this issue now. If you still have some questions, feel free to reopen it.
