### ISSUE TITLE
I want an old version 1.5.1

### ISSUE THREAD

**Issue by mingdong88** [Microsoft/vscode-cordova#461]
I want an old version 1.5.1

My Email: mingdong88@163.com

Best Regards
Ming dong

## Actual Behavior
1.
2.

## Expected Behavior
1.
2.

## Software versions
- Cordova VS Code extension version:
- VSCode version:
- OS platform and version:
- NodeJS version:
- Cordova version:
- Cordova-Android/iOS/Windows version:

## Outputs (Include if relevant)
- Output of the Debug Console (View -> Toggle Debug Console):
```
PASTE OUTPUT HERE
```
- Output of the Cordova output channel (View -> Toggle Output -> Select Cordova in ListBox):
```
PASTE OUTPUT HERE
```
- Output of the Developer Tools console (Help -> Toggle Developer Tools -> Select Console tab):
```
PASTE OUTPUT HERE
```

**Comment by SounD120** [comment]
Hi @mingdong88 . You can download Cordova Tools 1.5.1 using [this link](https://ms-vscode.gallery.vsassets.io/_apis/public/gallery/publisher/vsmobile/extension/cordova-tools/1.5.1/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage). Add `.vsix` extension to the file just downloaded, then toggle extensions tab in VS Code, delete installed Cordova Tools version and reload VS Code. After that open the extensions, click on `Install from VSIX` and choose your downloaded file.
Also you can disable auto updating for the extension if you want.
![image](https://user-images.githubusercontent.com/32372875/49363497-e045f600-f6f2-11e8-87ba-d61add524879.png)
