### ISSUE TITLE
Unable to mount developer disk image

### ISSUE THREAD

**Issue by Sampath-Lokuge** [Microsoft/vscode-cordova#465]
Hi,

> ** ARCHIVE SUCCEEDED **
> 2018-12-16 19:45:29.323 xcodebuild[39355:223755] [MT] IDEDistribution: -[IDEDistributionLogging _createLoggingBundleAtPath:]: Created bundle at path '/var/folders/tb/wy9k374s55bgwx_5pzwdl7z00000gn/T/My_2018-12-16_19-45-29.316.xcdistributionlogs'.
> Exported to: /Users/sampath/Desktop/my/Mobile-APP/platforms/ios/build/device
> ** EXPORT SUCCEEDED **
> Installing app on device
> Launching app
> Unable to mount developer disk image.

config

> {
> "name": "Run ios on device",
> "type": "cordova",
> "request": "launch",
> "platform": "ios",
> "target": "device",
> "sourceMaps": true,
> "cwd": "${workspaceFolder}",
> "port":9222,
> },

**Software versions**

Cordova VS Code extension version: 1.6.0
VSCode version: 1.30
OS platform and version: MacOS High Sierra 10.13.6
NodeJS version: v10.14.2 
Cordova version: 8.0.0
Cordova-iOS version: 4.5.5

Ionic:

  

>  ionic (Ionic CLI)  : 4.5.0 (/usr/local/lib/node_modules/ionic)
>    Ionic Framework    : ionic-angular 3.9.2
>    @ionic/app-scripts : 3.2.1
> 
> Cordova:
> 
>    cordova (Cordova CLI) : 8.0.0
>    Cordova Platforms     : ios 4.5.5
>    Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 1.2.1, (and 9 other plugins)
> 
> System:
> 
>    ios-deploy : 2.0.0
>    NodeJS     : v10.14.2 (/usr/local/bin/node)
>    npm        : 6.4.1
>    OS         : macOS High Sierra
>    Xcode      : Xcode 10.1 Build version 10B61

Iphone `6` with `iOS 12.1.1`

**Comment by ruslan-bikkinin** [comment]
Also, please try to update libimobiledevice: `brew update && brew upgrade libimobiledevice --HEAD && brew upgrade ideviceinstaller ios-webkit-debug-proxy`

**Comment by Sampath-Lokuge** [comment]
Hi @ruslan-bikkinin 

Yes, I did that. But no luck. I have followed this too. But the same error.  https://github.com/Microsoft/vscode-cordova/issues/192#issuecomment-250055677

So what else I can do that? I use `Ionic 3` app on `iPhone 6 12.1.1 device`.

**Comment by SounD120** [comment]
Hi @Sampath-Lokuge . I just tested this config and it works without any problems. In your configuration I found `ios-deploy 2.0.0`, I think it may cause some problems. Try to install `ios-deploy@1.9.4` via command `npm i -g ios-deploy@1.9.4`

```

Ionic:

   ionic (Ionic CLI)  : 4.4.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.0

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.4, browser 5.0.4, ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.2.5, (and 4 other plugins)

System:

   Android SDK Tools : 26.1.1 (/Users/admin/Library/Android/sdk/)
   ios-deploy        : 1.9.4
   NodeJS            : v8.12.0 (/usr/local/Cellar/node@8/8.12.0/bin/node)
   npm               : 6.4.1
   OS                : macOS Mojave 10.14.2
   Xcode             : Xcode 10.1 Build version 10B61
```

**Comment by Sampath-Lokuge** [comment]
Hi @SounD120 

I have done that. But now it shows this error:

> Installing app on device
> Launching app
> Unable to get device OS version. Details: Command failed: ideviceinfo -s -k ProductVersion
> /bin/sh: ideviceinfo: command not found

Ionic:

  

>  ionic (Ionic CLI)  : 4.5.0 (/usr/local/lib/node_modules/ionic)
>    Ionic Framework    : ionic-angular 3.9.2
>    @ionic/app-scripts : 3.2.1
> 
> Cordova:
> 
>    cordova (Cordova CLI) : 8.0.0
>    Cordova Platforms     : ios 4.5.5
>    Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 1.1.1, (and 9 other plugins)
> 
> System:
> 
>    ios-deploy : 1.9.4
>    NodeJS     : v10.14.2 (/usr/local/bin/node)
>    npm        : 6.5.0
>    OS         : macOS High Sierra
>    Xcode      : Xcode 10.1 Build version 10B61

I have another question too. Can you tell me how can I find out the port number? I have typed this on bash and it gives this error. Any clue?

> Mac-Users-MacBook-6:~ sampath$ ios-webkit-debug-proxy
> -bash: ios-webkit-debug-proxy: command not found

**Comment by SounD120** [comment]
@Sampath-Lokuge Looks like ios-webkit-debug-proxy is broken or not installed. Could you please try commands from [IWDP troubleshooting](https://github.com/google/ios-webkit-debug-proxy#troubleshooting)?

**Comment by Sampath-Lokuge** [comment]
@SounD120 I tried this

> brew update
> brew reinstall --HEAD usbmuxd
> brew reinstall --HEAD libimobiledevice
> brew reinstall -s ios-webkit-debug-proxy

But it asked to remove `--HEAD`. I did on both above occasions. Then it installed. But same error for this:

> Mac-Users-MacBook-6:~ sampath$ ios-webkit-debug-proxy
> -bash: ios-webkit-debug-proxy: command not found
>

I have restarted the MAC too. But still the same error above. Any clue?

**Comment by Sampath-Lokuge** [comment]
@SounD120  This is the exact error there:

> Mac-Users-MacBook-6:~ sampath$ brew reinstall --HEAD usbmuxd
> Error: invalid option: --HEAD

**Comment by SounD120** [comment]
Hi @Sampath-Lokuge . I have fully reinstalled the Homebrew and all it's packages and and, eventually, I was able to reproduce the problem. Now we are invesgatng what might caused this, cause it worked just before the reinstallation. This may be due to updates/changes in any of the components in this bundle : `ios-webkit-debug-proxy`, `libimobiledevice`, or the `Homebrew` itself. We'll let you know when we find a stable solution for your issue as soon as possible.

**Comment by Sampath-Lokuge** [comment]
Hi @SounD120 
Thanks a lot. This is a great extension for Ionic developers. I have successfully configured it for Android device on Win 10 Pro PC and working fine there. I really need this to work on MAC/iPhone too. If you need any help from my side please let me know. Good Luck!

**Comment by SounD120** [comment]
Hi @Sampath-Lokuge . We found the core of the problem, looks like `--HEAD` argument for `reinstall` command [is not supported by Homebrew anymore](https://github.com/Homebrew/brew/issues/4793#issuecomment-417915766). So this is the solution: at first, you need to uninstall `ios-webkit-debug-proxy` and `ideviceinstaller`.
```
brew uninstall ios-webkit-debug-proxy
brew uninstall ideviceinstaller
```
Then run these commands that uninstall your current `usbmuxd` and `libimobiledevice` versions and  install the latest ones from the GitHub `HEAD`, cause these versions have some fixes we need but they are still not released:
```
brew update
brew uninstall --ignore-dependencies libimobiledevice
brew uninstall --ignore-dependencies usbmuxd
brew install --HEAD usbmuxd
brew unlink usbmuxd
brew link usbmuxd
brew install --HEAD libimobiledevice
```
After that you can install `ideviceinstaller` and `ios-webkit-debug-proxy`:
```
brew install ideviceinstaller
brew install ios-webkit-debug-proxy
```
After that you can try to run `Run iOS on Device` debug scenario. Please let us know if it helps.

**Comment by Sampath-Lokuge** [comment]
Hi @SounD120

**Comment by Sampath-Lokuge** [comment]
Hi @SounD120 

This is working like a charm. Thanks a lot for the great support. I hope this extension will rock the Ionic developers' world in the future. Thank you again and have a great day ahead!

**Comment by SounD120** [comment]
@Sampath-Lokuge Glad to hear it. Feel free to create new issues if you have any questions and thanks for feedback.
