### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by ozzyjr** [Microsoft/vscode-cordova#469]
- Issue Type: `Performance`
- Extension Name: `cordova-tools`
- Extension Version: `1.6.0`
- OS Version: `Darwin x64 17.7.0`
- VSCode version: `1.30.1`

:warning: Make sure to **attach** this file from your *home*-directory: `/Users/$user/vsmobile.cordova-tools-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by ruslan-bikkinin** [comment]
Hi @ozzyjr and thanks for reaching us. Could you please attach `vsmobile.cordova-tools-unresponsive.cpuprofile.txt` as it said in [VS Code documentation](https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load#dealing-with-high-cpu-load-issues) and in your issue description? We can't do much about it without this info.

**Comment by ruslan-bikkinin** [comment]
@ozzyjr just a friendly ping on this

**Comment by ruslan-bikkinin** [comment]
I am closing this for now due to inactivity and lack of needed information. Please feel free to reopen when you are ready to give us cpuprofile.txt file.

**Comment by ruslan-bikkinin** [comment]
Related issue #517
