### ISSUE TITLE
Support for the capacitor apps

### ISSUE THREAD

**Issue by Sampath-Lokuge** [microsoft/vscode-cordova#471]
Hi,

I'm a big fan of your this extension. But now Ionic has Ionic 4 with a capacitor. One of capacitor dev told this `vscode-cordova is for Cordova apps, it won't work on Capacitor apps.` So do you have any plan to support capacitor apps? Thanks in advance.

**Comment by Sampath-Lokuge** [comment]
It would be great if you'll put this as an `open issue` under the tag `enhancement`. Otherwise, how will others see this to `vote` ? @dhanvikapila

**Comment by kstro21** [comment]
Is this in progress or is waiting for someone to start it? I would like to help.

**Comment by SounD120** [comment]
Hi @kstro21 , there is no progress so far, but it would be great if you contribute to the project. Here is the [contribuiting guide](https://github.com/microsoft/vscode-cordova/blob/master/CONTRIBUTING.md). I think the good starting point could be adding the support of the Capacitor CLI as described [here](https://github.com/microsoft/vscode-cordova/blob/aad28299970af88f9c7040f1d663e3630bf0d3f6/src/utils/cordovaProjectHelper.ts#L356). 
Also, [this article](https://code.visualstudio.com/api/extension-guides/debugger-extension) could be helpful for understanding of debugger extensions architecture.
Please let us know if you have questions.

**Comment by EzioLi01** [comment]
Close this issue since it's no longer updating.

**Comment by Sampath-Lokuge** [comment]
Yes, now we have official solution from Ionic team: https://marketplace.visualstudio.com/items?itemName=ionic.ionic
