### ISSUE TITLE
Extension Host Crash

### ISSUE THREAD

**Issue by qkdreyer** [Microsoft/vscode-cordova#472]
## Actual Behavior
1. Extension Host Crash

## Expected Behavior
1. Prevent Extension Host Crash

## Software versions
- Cordova VS Code extension version: 1.6.1 from Marketplace
- VSCode version: 1.31.0-insider
- OS platform and version: macOS 10.14.1 (18B45d)
- NodeJS version: v10.13
- Cordova version: 8.1.2 (cordova-lib@8.1.1)
- Cordova-Android/iOS/Windows version: Irrelevant

## Outputs (Include if relevant)
- Output of the Debug Console (View -> Toggle Debug Console):
`Empty`

- Output of the Cordova output channel (View -> Toggle Output -> Select Cordova in ListBox):
![image](https://user-images.githubusercontent.com/717869/50888188-64c41c80-13f5-11e9-996f-1dbed27d80ea.png)

- Output of the Developer Tools console (Help -> Toggle Developer Tools -> Select Console tab):
![image](https://user-images.githubusercontent.com/717869/50888099-2a5a7f80-13f5-11e9-99a3-d89d661abfaf.png)
```
Extension Host
extensionHost.ts:235 dyld: lazy symbol binding failed: Symbol not found: __ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEiNS_19ConstructorBehaviorENS_14SideEffectTypeE
  Referenced from: /Users/qkdreyer/.vscode-insiders/extensions/vsmobile.cordova-tools-1.6.1/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node
  Expected in: flat namespace

dyld: Symbol not found: __ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEiNS_19ConstructorBehaviorENS_14SideEffectTypeE
  Referenced from: /Users/qkdreyer/.vscode-insiders/extensions/vsmobile.cordova-tools-1.6.1/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node
  Expected in: flat namespace
```

**Comment by SounD120** [comment]
Hi @qkdreyer . I faced the same error just now on Insiders build `1.31.0-insider` with 1.6.1, but on `1.30.2` VS Code version extension works stable. We'll investigate the situation on Insiders build and let you know what might cause this.

**Comment by qkdreyer** [comment]
The bug has been introduced somewhere here then : https://github.com/Microsoft/vscode/compare/1.30.2...e44801f2b3ab00c26c742aa0ef473824469fad02

**Comment by qkdreyer** [comment]
Looks like node version has been upgraded from 8.9.3 to 10.2.0

**Comment by SounD120** [comment]
Hi @qkdreyer . We found the problem core, it's connected to our `cordova-simulate` `chokidar@2.0.4` dependency. You can find more information in [this issue](https://github.com/Microsoft/vscode/issues/64981#issuecomment-447880936). We’ll update you as soon as release new version with fix on this.

**Comment by qkdreyer** [comment]
Are you planning to release v1.6.2 soon ?

**Comment by SounD120** [comment]
@qkdreyer We are performing prerelease testing right now, so as soon as we finish it a new version will be released.

**Comment by SounD120** [comment]
@qkdreyer , version 1.6.2 that includes fix for this just have been released.

**Comment by qkdreyer** [comment]
Thanks @SounD120 !
