### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by sclMAX** [Microsoft/vscode-cordova#488]
- Issue Type: `Performance`
- Extension Name: `cordova-tools`
- Extension Version: `1.7.0`
- OS Version: `Linux x64 4.18.0-13-generic`
- VSCode version: `1.30.2`

:warning: Make sure to **attach** this file from your *home*-directory: `/home/max/vsmobile.cordova-tools-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by ruslan-bikkinin** [comment]
Hi @sclMAX and thanks for reaching us. Could you please attach `vsmobile.cordova-tools-unresponsive.cpuprofile.txt` as it said in [VS Code documentation](https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load#dealing-with-high-cpu-load-issues) and in your issue description? We can't do much about it without this info.

**Comment by ruslan-bikkinin** [comment]
@sclMAX just a friendly ping on this

**Comment by ruslan-bikkinin** [comment]
I am closing this due to lack of additional information. Please feel free to re-open when you are ready to provide `vsmobile.cordova-tools-unresponsive.cpuprofile.txt` file.

**Comment by ruslan-bikkinin** [comment]
Related issue #517
