### ISSUE TITLE
Error processing "launch": Unable to find target 

### ISSUE THREAD

**Issue by sertal70** [Microsoft/vscode-cordova#489]
## Actual Behavior
When running the following configuration:
```
      "name": "Run android on emulator (Pixel_XL_API_25)",
      "type": "cordova",
      "request": "launch",
      "platform": "android",
      "target": "Pixel_XL_API_25",
      "sourceMaps": true,
      "cwd": "${workspaceFolder}/src"
```
All tasks execute successfully, Android emulator named `Pixel_XL_API_25` starts and the app is loaded and run into, but in the debug console I have the following error:
```
LAUNCH SUCCESS
App successfully launched
Attaching to android
List of devices attached
emulator-5584	device
Unable to find target Pixel_XL_API_25
```
Also VSC shows a dialog with the following error message:

`[cordova-tools] Error processing "launch": Unable to find target Pixel_XL_API_25`

and the debug session ends.

## Expected Behavior
I would expect to have the VSC debugger active and no error message because the emulator is actually started.

## Software versions
- Cordova VS Code extension version: 1.7.0
- VSCode version: 1.30.2
- OS platform and version: macOS Mojave 10.14.2
- NodeJS version: v8.9.3
- Cordova version: 8.1.1
- Cordova-Android/iOS/Windows version: android 6.4.0, ios 4.5.5

## Outputs (Include if relevant)
- Output of the Debug Console (View -> Toggle Debug Console):
```
LAUNCH SUCCESS
App successfully launched
Attaching to android
List of devices attached
emulator-5584	device
Unable to find target Pixel_XL_API_25
```
- Output of the Cordova output channel (View -> Toggle Output -> Select Cordova in ListBox):
```
N/A
```
- Output of the Developer Tools console (Help -> Toggle Developer Tools -> Select Console tab):
```
N/A
```

**Comment by ruslan-bikkinin** [comment]
Hi @sertal70 and thanks for reaching us. You should use `emulator-5584` instead of `Pixel_XL_API_25` as it's a device id in your case.

**Comment by sertal70** [comment]
Thanks @ruslan-bikkinin, actually I did it but I forgot to mention in the issue description. I tried both `emulator-5584` and `emulator` but none of them worked.

**Comment by ruslan-bikkinin** [comment]
@sertal70 did you try to debug your app using Chrome inspector? To do so you need to follow these steps:
* Run `cordova run android`
* Open `chrome://inspect/#devices` url in Chrome and click `inspect`.

Please, try it and let us know if it works for you.

**Comment by sertal70** [comment]
@ruslan-bikkinin yes, that has been the way I debugged my apps up to now, when I started trying to use this extension. The complete command line I used to execute is:

`ionic cordova run android -lcs --target=Pixel_XL_API_25`

Note that I use more that one Android emulator, so the option to specify its name is a requirement for me.

**Comment by ruslan-bikkinin** [comment]
@sertal70 you are facing multiple issues:

* Extension interprets target value as device id taken from `adb devices --list` output, so for now you need to manually run needed emulator before running debug in VSC and use it's id (`emulator-5584` in your case) as `target` value in debug configuration. Then you can use `Run android on emulator` configuration and it should work. I think we should provide additional parameter for this specific emulator usage case when user run debug on particular avd emulator device (like `Pixel_XL_API_25`) while emulator process itself is not ran yet.

* Seems to be that Debug console produced by previous runs of debug configuration isn't cleared in case of error. I don't know yet if it's VS Code issue or extension one but I guess we should create an issue in our repo and investigate it as well. As for now to see actual `Debug console` output in case of error appeared during debug you may need to click on `Clear Console` button:
![image](https://user-images.githubusercontent.com/30265843/51978783-35f11180-249c-11e9-9315-8c7c1d53035f.png)

Please let me know if it helps you.

**Comment by sertal70** [comment]
@ruslan-bikkinin I confirm that starting manually the emulator and then running the launch configuration works, it is a workaround for now.

I confirm also that the debug console doesn't get cleared on subsequent launch after the first, I have to clear it manually to see what's going on.

Doing these test I run into another issue: using the emulator launch configuration, if I set `ionicLiveReload: true` the followin error occur at launch: 

`[cordova-tools] Error processing "launch": The Ionic live reload server exited unexpectedly`

let me know if you prefer I open a separate issue for this.

**Comment by ruslan-bikkinin** [comment]
@sertal70 :+1: yes, let's move it to another discussion, so I could close this one.
