### ISSUE TITLE
Debug Console output is not cleared in some cases

### ISSUE THREAD

**Issue by ruslan-bikkinin** [microsoft/vscode-cordova#491]
In some cases Debug Console output isn't cleared after running debug:
* Run debug once, stop it, then run debug configuration which is intentionally should succeed. Between starting debug configuration and attaching to app debug console won't be cleared.
* Run debug once, stop it, then run debug configuration which is intentionally should fail. No new output will be shown in Debug Console.

#489

**Comment by SounD120** [comment]
Issue to track: https://github.com/microsoft/vscode/issues/74551

**Comment by SounD120** [comment]
Bug has been fixed by VS Code team. Fix will be released as a part of new VS Code versions.
