### ISSUE TITLE
Ionic live reload not working.

### ISSUE THREAD

**Issue by CodeDoctor34** [Microsoft/vscode-cordova#495]
## Actual Behavior
1. Live reload is not working when enabled in the config, using the "livereload": true configuration.
2. Live reload fails when trying to override configuration arguments with: 
{
            "name": "Run Android on device",
            "type": "cordova",
            "request": "launch",
            "platform": "android",
            "target": "device",
            "port": 9222,
            "sourceMaps": true,
            "livereload": true,
            "devServerTimeout": 200000,
            "runArguments": [
                "--livereload",
                "--address 192.168.0.10"                
            ],
            "cwd": "${workspaceFolder}"            
},

## Expected Behavior
1. Ionic live reload should run when using the "livereload": true configuration.
2. Ionic live reload should run when setting custom configuration run arguments.

## Software versions
- Cordova VS Code extension version: 1.7.0
- VSCode version: 1.30.2
- OS platform and version: Windows 10 - 1803
- NodeJS version: 10.15.1
- Cordova version: 8.1.2
- Cordova-Android/iOS/Windows version: android 7.1.4

## Outputs (Include if relevant)
- Output of the Debug Console (View -> Toggle Debug Console):
```
Package name: io.ionic.starter
LAUNCH SUCCESS
The Ionic live reload server exited unexpectedly
```
- Output of the Cordova output channel (View -> Toggle Output -> Select Cordova in ListBox):
```
PASTE OUTPUT HERE
```
- Output of the Developer Tools console (Help -> Toggle Developer Tools -> Select Console tab):
```
PASTE OUTPUT HERE
```

**Comment by ruslan-bikkinin** [comment]
Hi @CodeDoctor34 and thanks for creating separate issue. To make it work you need to wait until new version of Cordova Tools is released with changes from this PR: #494 and then update your configuration like this:
 ``
```js
{
    "name": "Run Android on device",
    "type": "cordova",
    "request": "launch",
    "platform": "android",
    "target": "device",
    "port": 9222,
    "sourceMaps": true,
    "livereload": true,
    "devServerTimeout": 200000,
    "devServerAddress": "192.168.0.10",
    "cwd": "${workspaceFolder}"
}
```
Please, be aware that by using `runArguments` you completely overrides all predefined run arguments for ionic dev server run command via extension code like `--verbose`, `--livereload`.

**Comment by CodeDoctor34** [comment]
@ruslan-bikkinin Okay, thanks for the update. I did originally try it by doing without the run arguments, but I found that for some reason it wouldn't start with live reloading, it almost seemed like it was ignoring the configuration properties I had set. Looking forward to the new release.

**Comment by ruslan-bikkinin** [comment]
Guys, v1.8.0 with fixes for livereload cases has just been released, so I'm closing this. Please feel free to create a new one if needed.
