### ISSUE TITLE
Simulate inside panel column

### ISSUE THREAD

**Issue by ozzyjr** [Microsoft/vscode-cordova#496]
I have a doubt.
When I debug, the simulator would open in a window / panel inside the VS Code and is now opening in a new Chrome window. That is, it's opening two Chrome windows, one with the simulator and another with the app project.
I would like to know how to reopen the simulator in VS Code and not in a browser.

![image](https://user-images.githubusercontent.com/12512993/52275596-2740a980-2937-11e9-99d1-f4ed18fdcfd5.png)
I want this.

Does anyone know how to help me?
I'm on a Mac, VS Code 1.30.2 (1.30.2), Cordova Tools 1.7.0

Launch.json

{
    // Use IntelliSense to learn about possible attributes.
    // Passe o mouse para ver as descrições dos atributos existentes.
    // Para obter mais informações, visite: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Run Android on device",
            "type": "cordova",
            "request": "launch",
            "platform": "android",
            "target": "device",
            "port": 9222,
            "sourceMaps": true,
            "cwd": "${workspaceFolder}",
            "ionicLiveReload": false
        },
        {
            "name": "Run iOS on device",
            "type": "cordova",
            "request": "launch",
            "platform": "ios",
            "target": "device",
            "port": 9220,
            "sourceMaps": true,
            "cwd": "${workspaceFolder}",
            "ionicLiveReload": false
        },
        {
            "name": "Attach to running android on device",
            "type": "cordova",
            "request": "attach",
            "platform": "android",
            "target": "device",
            "port": 9222,
            "sourceMaps": true,
            "cwd": "${workspaceFolder}"
        },
        {
            "name": "Attach to running iOS on device",
            "type": "cordova",
            "request": "attach",
            "platform": "ios",
            "target": "device",
            "port": 9220,
            "sourceMaps": true,
            "cwd": "${workspaceFolder}"
        },
        {
            "name": "Run Android on emulator",
            "type": "cordova",
            "request": "launch",
            "platform": "android",
            "target": "emulator",
            "port": 9222,
            "sourceMaps": true,
            "cwd": "${workspaceFolder}",
            "ionicLiveReload": false
        },
        {
            "name": "Run iOS on simulator",
            "type": "cordova",
            "request": "launch",
            "platform": "ios",
            "target": "emulator",
            "port": 9220,
            "sourceMaps": true,
            "cwd": "${workspaceFolder}",
            "ionicLiveReload": false
        },
        {
            "name": "Attach to running android on emulator",
            "type": "cordova",
            "request": "attach",
            "platform": "android",
            "target": "emulator",
            "port": 9222,
            "sourceMaps": true,
            "cwd": "${workspaceFolder}"
        },
        {
            "name": "Attach to running iOS on simulator",
            "type": "cordova",
            "request": "attach",
            "platform": "ios",
            "target": "emulator",
            "port": 9220,
            "sourceMaps": true,
            "cwd": "${workspaceFolder}"
        },
        {
            "name": "Serve to the browser (ionic serve)",
            "type": "cordova",
            "request": "launch",
            "platform": "serve",
            "cwd": "${workspaceFolder}",
            "devServerAddress": "localhost",
            "sourceMaps": true,
            "ionicLiveReload": true
        },
        {
            "name": "Simulate Android in browser",
            "type": "cordova",
            "request": "launch",
            "platform": "android",
            "target": "chrome",
            "simulatePort": 8000,
            "livereload": true,
            "sourceMaps": true,
            "cwd": "${workspaceFolder}"
        },
        {
            "name": "Simulate iOS in browser",
            "type": "cordova",
            "request": "launch",
            "platform": "ios",
            "target": "chrome",
            "simulatePort": 8000,
            "livereload": true,
            "sourceMaps": true,
            "cwd": "${workspaceFolder}"
        },
        {
            "name": "Run Browser",
            "type": "cordova",
            "request": "launch",
            "platform": "browser",
            "target": "chrome",
            "simulatePort": 8000,
            "livereload": true,
            "sourceMaps": true,
            "cwd": "${workspaceFolder}"
        }
    ]
}

**Comment by ruslan-bikkinin** [comment]
Hi @ozzyjr and thanks for questioning. To render web pages such as simulator page inside VS Code window `vscode.previewHtml` API method had been used, but due to [upcoming deprecation](https://github.com/Microsoft/vscode/issues/62630) of this method starting with Cordova Tools [v1.6.0](https://github.com/Microsoft/vscode-cordova/releases/tag/1.6.0) this method usage has been dropped. VS Code team [suggested](https://github.com/Microsoft/vscode-cordova/issues/447) an alternative as Webview Api, but its functionality are very limited and it couldn't render simulator page. That's why we had to turn to opening simulator page in browser instead. May be in the future we would see another options to bring back rendering simulator page in VS Code window (may be with recent updates of Webview API), but as for now we see none. I think, that only thing that we could try to do in terms of improving user experience is to find a way to open both simulator and app pages in one browser window.
