### ISSUE TITLE
Rename parameter runtimeArgs to chromeArgs and expose it to public

### ISSUE THREAD

**Issue by MaximeLimone** [microsoft/vscode-cordova#500]
Hello,

This is not an issue but a fix or feature

I need a way to add parameter to chrome when run Serve to the browser. To handle CORS expection for example.

I make a fix : 
I add this line 1373 in cordovaDebugAdapter.ts : chromeArgs.push(...args.chromeArgs); 
just after the chromeArgs object initialization.

And in my launch.json i'm now able to push some arguments to chrome.

"chromeArgs": ["--disable-web-security", "--ignore-certificate-errors 'http://127.0.0.1:8100'", "--remote-debugging-port=9222"],

**Comment by ruslan-bikkinin** [comment]
Hi @MaximeLimone and thanks for reaching us. Extension have an undocumented way to pass arguments to Chrome via `runtimeArgs` parameter in `launch.json`, but I'd agree with you that It should be made more transparently to end user like providing `chromeArgs` parameter. We've added it to our backlog and pick it up in order of priorities. As for now you can use `runtimeArgs` parameter as workaround.

**Comment by EzioLi01** [comment]
Close this inactive issue, follow the comment, we can use runtimeAtgs to setup chrome parameter. Please let me know if you still need this update.
