### ISSUE TITLE
[loc][Query][vscode_extensions ] Localizability of 0; "./src/extension/android/androidPlatform.DeviceSupportsOnlyAPILevel"

### ISSUE THREAD

**Issue by PDostalek** [Microsoft/vscode-cordova#513]
Hi,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question to Core team.
Please re-assign back to use in case you are not the right contact person or you can´t assign to a proper person.
Can you help please?
Thanks!

Source:
Device {0} supports only API Level {1}. \r\n Level {2} is needed to support port forwarding via adb reverse. \r\n For debugging to work you'll need &lt;Shake or press menu button&gt; for the dev menu, \r\n go into &lt;Dev Settings&gt; and configure &lt;Debug Server host &amp; port for Device&gt; to be \r\n an IP address of your computer that the Device can reach. More info at: \r\n https://facebook.github.io/react-native/docs/debugging.html#debugging-react-native-apps

File Name:
Src\vscode-extensions\vscode-cordova.xlf

Resource ID:
0; "./src/extension/android/androidPlatform.DeviceSupportsOnlyAPILevel"

Query:
<Debug Server host & port for Device> are segments in brackets localizable ?

**Comment by ruslan-bikkinin** [comment]
Hi @PDostalek, our team haven't started any work on adding translations to Cordova extension. The string you are asking for help with is from React Native extension.

**Comment by ruslan-bikkinin** [comment]
@PDostalek with the respect to your question: answer is no.
