### ISSUE TITLE
[loc][Query][vscode_extensions ] Localizability of :0; "./src/common/error/errorStrings.CouldntImportScriptAt"

### ISSUE THREAD

**Issue by PDostalek** [Microsoft/vscode-cordova#514]
Hi,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question to Core team.
Please re-assign back to use in case you are not the right contact person or you can´t assign to a proper person.
Can you help please?
Thanks!

Source:
Couldn't import script at &lt;{0}&gt;

File Name:
Src\vscode-extensions\vscode-cordova.xlf

Resource ID:
0; "./src/common/error/errorStrings.CouldntImportScriptAt"

Query:
What does {0} represent?

**Comment by SounD120** [comment]
Hi @PDostalek . Cordova Tools extension is not yet supports i18n. The string you are asking for help with is from [React Native extension](https://github.com/Microsoft/vscode-react-native).
With respect to your question {0} is an URL from which we trying to import some script.
