### ISSUE TITLE
Extension fails to work at all

### ISSUE THREAD

**Issue by TaylorDale** [Microsoft/vscode-cordova#523]
This involves a project where the directory open in VSCode is parent of the Cordova folder, rather than the Cordova folder itself.

## Actual Behavior
1. Install ext, add Cordova config to debugger
2. Run any of the options

## Expected Behavior
1. Something to happen (launch browser, launch app, connect to app)

## Software versions
- Cordova VS Code extension version: 1.8
- VSCode version: 1.33
- OS platform and version: Windows 10
- NodeJS version: Latest
- Cordova version: Latest

## Outputs (Include if relevant)
There are no outputs for the extension anywhere, in any of the output sections

**Comment by ruslan-bikkinin** [comment]
Hi @TaylorDale and thanks for reaching us. Could you please give an example of what directory you are trying to open?

**Comment by TaylorDale** [comment]
> Hi @TaylorDale and thanks for reaching us. Could you please give an example of what directory you are trying to open?

Thanks for the quick response Ruslan, the extension does not seem to be able to work if the folder I have open in VSCode is not the direct parent of the Cordova ext. There does not seem to be a way to configure this either.

My setup is
|_Project <- This is open in VSCode
  |_Source
  |_Cordova

**Comment by ruslan-bikkinin** [comment]
@TaylorDale what's in _Cordova and in _Source directories? Do you have any application demo that we could take a look at?

**Comment by TaylorDale** [comment]
Cordova is the Cordova project and source is the source code for said
project which is compiled into the Cordova www directory

**Comment by ruslan-bikkinin** [comment]
@TaylorDale thanks for clarifications, to make it work you need to open not just `_Project` directory, but open `_Source` and then add `_Cordova` by `File->Add Folder to workspace`. After that debugging should work. Also, be aware that you need to manually update `_Cordova/www` directory before running debug configuration, but you can make it even simpler by [adding task](https://code.visualstudio.com/docs/editor/tasks) to `_Cordova` which compiles `_Source` and copy it to `_Cordova/www` and adding this task to your debug configuration as `prelaunchTask` config value. Examples:
* `_Cordova/.vscode/tasks.json`:
```js
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "compile and copy sources",
            "type": "shell",
            // delete www content and then copy new ones from _Source
            "command": "rm -rf www/* && cp -R ../_Source/* www",
        }
    ]
}
```

* `_Cordova/.vscode/launch.json`:
```js
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Run Android on device",
            "type": "cordova",
            "request": "launch",
            "platform": "android",
            "target": "device",
            "port": 9222,
            "sourceMaps": true,
            "cwd": "${workspaceFolder}",
            "ionicLiveReload": false,
            "preLaunchTask": "compile and copy sources"
        },
       // ... some other configs
}
```

Please let me know if it works or you have questions.

**Comment by TaylorDale** [comment]
Hi there, thanks for you response and advice. That sounds good to me - I
just wanted to clarify that you can't just simply open the parent directory
of my Cordova and Project source and find some way to make it work. I've
already got the rest of the configuration sorted out in regards to updating
the correct folders etc. - it was just running it through VSCode that was
an issue.

Cheers

**Comment by ruslan-bikkinin** [comment]
@TaylorDale glad to hear that your issue is resolved, then I am closing it. Please feel free to reopen if needed.
