### ISSUE TITLE
In debug, too many compatibility-related exceptions were thrown

### ISSUE THREAD

**Issue by coloz** [Microsoft/vscode-cordova#526]
I use angular 7 and ionic 4 for development, probably because in some newer ways, debuger throws a lot of exceptions.But it's normal to use ionic cli.

## Actual Behavior
1. core-js constantly throws exceptions

## Expected Behavior
1. do not throw insignificant exceptions

## Software versions
```
Ionic:

   ionic (Ionic CLI)             : 4.12.0 (C:\Users\clz\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.2.0
   @angular-devkit/build-angular : 0.12.4
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.2.4
   @ionic/angular-toolkit        : 1.3.0

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.4
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 3.1.1, (and 30 other plugins)

System:

   NodeJS : v10.15.1 (D:\Program Files\nodejs\node.exe)
   npm    : 6.4.1
   OS     : Windows 10
```

## Outputs (Include if relevant)
![image](https://github.com/coloz/images/blob/master/cordova-debug.jpg?raw=true)

**Comment by ruslan-bikkinin** [comment]
Hi @coloz and thanks for reaching us. I believe, your question should be addressed to [vscode-chrome-debug-core](https://github.com/Microsoft/vscode-chrome-debug-core) repo, because we don't control this behaviour on extension side.
