### ISSUE TITLE
reg error to boot with  chrome

### ISSUE THREAD

**Issue by julientype** [microsoft/vscode-cordova#530]
## Actual Behavior
An error occurred while attaching to the debugger. Error: Command failed: reg QUERY "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\chrome.EXE" /v ""
'reg' is not recognized as an internal or external command,

## Expected Behavior
bad registry call.............. i'm on windows 8.1

cordova simulate android in browser......

HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\chrome.EXE" /v ""

please fix..... typo error........ HKLM ..... it may work on win 10 i'm not sure i have no win 10
but it will not work on  8 you need..... HKEY_LOCAL_MACHINE

**Comment by SounD120** [comment]
Hi @julientype . This behaviour is connected with external package [cordova-serve](https://github.com/apache/cordova-serve). You can propose a fix for that in [that line](https://github.com/apache/cordova-serve/blob/18ace76f16667ebf2ec5bc2125c100a199fb8f44/src/browser.js#L213), or at least fix it locally in the extension folder:
```
%USERPROFILE%\.vscode\extensions\vscode-cordova-1.8.1\node_modules\cordova-serve\src\browser.js
```
The exact change for line 213 is:
```
var regQPre = 'reg QUERY "HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\App Paths\\';
```

**Comment by SounD120** [comment]
@julientype I checked both variants of registry queries:
```
reg QUERY "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\chrome.EXE" /v ""
```
and 
```
reg QUERY "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\chrome.EXE" /v ""
```
They are both works on Windows 8.1. 
Error `'reg' is not recognized as an internal or external command,` is looks like `reg` executable is absent in your PATH variable. 
To add it you need:
* Open 
```
Control Panel -> System and Security -> System -> Advanced system settings  -> Edit the system environment variables -> Environment variables... -> Find 'Path' in System variables
```
* Double click on Path variable
* In the window that appears add `%SystemRoot%\System32;` at the start of the `Variable value` string, then reload VS Code if opened. 

Please let us know if it helps.

**Comment by julientype** [comment]
Yes it worked... it now boots....
how do you flag cordova to compile with no debug option for the app....
or if i wanted to just grant an iframe  to debug....
like let say im a user and want add an insert to the app yet you need to debug its page insert...
currently it wide open ........chrome:// inspect will dig into cordova.js and my app files and plugins....
their must be a way to flag android to isolate file reads from from its debug connection.....

**Comment by julientype** [comment]
here is what i mean by your app turns into an activeX type app....
like one could build yet the user cant access the system files or code mush like an activeX component so when you use chrome:// inspect on pak file you flag before compiling  what you wish and not wish to grant to isolate the app features.....
now you can fully inspect or part inspect your app that feature do not destroy the app or gain access to private information.... 
activeX app   then users can add to it without braking the app.... 
part of config.json

**Comment by SounD120** [comment]
@julientype Could you please describe in more detailed and structured way what you want to implement?

**Comment by julientype** [comment]
a plugin  iframe component ..... i create a button and insert logic to the user ..... as the developer of the app
it could pop-into a new div tag window..... in design view ..... save 
in JavaScript   it supports events  ..... onload on change for the user..... 
this iframe is debug-able...... like you can expose your objects this way..... 
iframe.name.setproperties = "foo"
your app is the  store<----you get to load up a simple script view......
like my sql   create an input form this table .....
a plugin  iframe component ......   iframe.data.move,nextRec
my plugin would fire events to it.... yet never let debuger pass the wall......
ondataChange(e)
the user needs to debug it ..... chrome://inspect    
but it needs to be isolated where you cant go into the app.... only what i grant as a com object.....
iframes are grate they disbach thier own memory threads .....
so in your cordova app   you call inject iframe by the plugin ..... i could inject 5 frames 
ftp   iframe component in an iframe hide or show.....   as the user i now have an activeX control i can manipulate ....... its just one plug-in with many reusable types ........ 
add jar files    in an iframe    you now get play with it in an html form..... but only what i grant as an object to it.......
your index.html and index.js    is the back bone your boot files 

this how the original visual basic worked .... create a form and add a component on it..... or buy one....or make one..... iframeGrid<----you pop it in and your ready to load your data with events that fire

**Comment by julientype** [comment]
cordova will create it self in run time as dom object... wrong way
you use an object tag to create cordova....   
like java runs in a web page.... can chromoe// intersep load it... no
you add a base tag...... and run cordova as object load event.....
you need cordova to fix this.... you dont load cordova as dom like you do you let dom load cordova as an isolated object.....  its how java works in html page..... it will cut off chrome debugger this way.....  you did not load it the object tag did...
you dont src a script in you let object scr it self in....
right now all thing are exposed to dom.....
object tags are in objects not a script to dom to load..... that debugger own
cordove is an object not a script  it must be load this way

**Comment by julientype** [comment]
i dont load cordova as a script i load as cordova java object in html page that page let me pay with cordova object and is isolated form dom like regular java app in web page

**Comment by julientype** [comment]
when don index it self from file reads  over to the debuger its object its not something chrome can debug its in app object
you load cordova this way... its not a link its an object..... cordove inject it self as a script into dom and the debugger pick up all

**Comment by julientype** [comment]
no joke you make a plugin an i insert its object tag in html  and i now play with camera... its that simple...
its not you creating a dom object for me its me creating a dom object of you in html 
your the store im the client in html ....  you dont control dom i do your an object java i call up in dom from an iframe

**Comment by julientype** [comment]
here is what i mean when i load cordova as an object  not a script... it stays constant.. 
ifrme1 and to 2 are both the same in the app  .. the store is the store as a store as its object regrades of treads i the user  operas off....

**Comment by dhanvikapila** [comment]
@julientype  Thank you for the details. Maybe I'm misunderstanding your "plugin iframe component" so maybe you could help me by clarifying few things - 

1. Why you would want to restrict access to dom, objects in your app when debugging? 
1. Who will be consumers for your component (and view) and how would they use it? 
1. What problem are you trying to solve with this component and view? 

Thanks.

**Comment by julientype** [comment]
dom digs into everything.... so the best thing is to just do it in as a  java plug in
the debug console lets you execute what ever you want....
 .....really it digs in deep into the app....  you don want people knowing private stuff or the the ability to retrieve info  or hack in to it as a co worker on software you use to damage it....

**Comment by dhanvikapila** [comment]
@julientype if you are looking to prevent others from looking into your code, you are not going to be able to use JavaScript for achieving that. 

Closing this thread as this is not something that can be done in the Cordova extension.
