### ISSUE TITLE
[cordova-tools] nothing happens after installing extension

### ISSUE THREAD

**Issue by 1housand** [microsoft/vscode-cordova#531]
## Actual Behavior
1. In the VS Code Extensions: Marketplace, click install
2. Reload required
3. Cordova tools is nowhere to be found
4. the files exist in ~/.vscode/extensions though
5. When I force quit VS Code, Cordova tools shows up, but says reload required and nothing happens after reload

## Expected Behavior
1. Install the extension
2. extension appears in the extensions section functioning properly

## Software versions
- Cordova VS Code extension version: 1.8.1
- VSCode version: 1.33.1
- OS platform and version: MacOS Mojava 10.14.4
- NodeJS version: 11.13.0
- Cordova version: 9.0.0

## Outputs (Include if relevant)
- Output of the Developer Tools console (Help -> Toggle Developer Tools -> Select Console tab):
```
console.ts:134 [Extension Host] rejected promise not handled within 1 second: true
t.log @ console.ts:134
$logExtensionHostMessage @ mainThreadConsole.ts:39
_doInvokeHandler @ rpcProtocol.ts:399
_invokeHandler @ rpcProtocol.ts:384
_receiveRequest @ rpcProtocol.ts:304
_receiveOneMessage @ rpcProtocol.ts:226
_protocol.onMessage.e @ rpcProtocol.ts:101
fire @ event.ts:584
a @ ipc.net.ts:392
e @ ipc.net.ts:399
fire @ event.ts:584
_receiveMessage @ ipc.net.ts:678
_socketDisposables.push._socketReader.onMessage.e @ ipc.net.ts:549
fire @ event.ts:584
acceptChunk @ ipc.net.ts:212
_register._socket.onData.e @ ipc.net.ts:173
t @ ipc.net.ts:24
emit @ events.js:182
addChunk @ _stream_readable.js:279
readableAddChunk @ _stream_readable.js:264
Readable.push @ _stream_readable.js:219
onread @ net.js:636

log.ts:173   ERR An unknown error occurred. Please consult the log for more details.

[Extension Host] (node:15719) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
t.log @ console.ts:134
$logExtensionHostMessage @ mainThreadConsole.ts:39
_doInvokeHandler @ rpcProtocol.ts:399
_invokeHandler @ rpcProtocol.ts:384
_receiveRequest @ rpcProtocol.ts:304
_receiveOneMessage @ rpcProtocol.ts:226
_protocol.onMessage.e @ rpcProtocol.ts:101
fire @ event.ts:584
a @ ipc.net.ts:392
e @ ipc.net.ts:399
fire @ event.ts:584
_receiveMessage @ ipc.net.ts:678
_socketDisposables.push._socketReader.onMessage.e @ ipc.net.ts:549
fire @ event.ts:584
acceptChunk @ ipc.net.ts:212
_register._socket.onData.e @ ipc.net.ts:173
t @ ipc.net.ts:24
emit @ events.js:182
addChunk @ _stream_readable.js:279
readableAddChunk @ _stream_readable.js:264
Readable.push @ _stream_readable.js:219
onread @ net.js:636
```

**Comment by SounD120** [comment]
Hi @1housand . It might be connected with recent extension publisher change. Could you please try to change publisher from `vsmobile` to `msjsdiag` in extension's `package.json` file? To do that please do the following:
* Run `code ~/.vscode/extensions/msjsdiag.cordova-tools-1.8.1/package.json` command in your terminal to open extension's `package.json` file. 
* Find `publisher` field and replace its value by `msjsdiag`
* Reload VS Code

Please let us know if this helps.

**Comment by 1housand** [comment]
thank you @SounD120! it worked!
now i can start coding away!
