### ISSUE TITLE
Cordova Tool fails to activate after VSCode Reload

### ISSUE THREAD

**Issue by rustedwizard** [microsoft/vscode-cordova#535]
## Actual Behavior
When VSCode reload (when an extension update and require me to reload), Cordova Tool fails to activate (Look at the following screen capture): and I have to close VSCode and reopen again. (seems that only reload cause this extension fails to reload)
![Capture](https://user-images.githubusercontent.com/6314177/58290740-910e8300-7d6f-11e9-8aa0-388e6fcf15ce.PNG)

## Expected Behavior
1. Cordova Tool would activate normally after reload

## Software versions
- Cordova VS Code extension version: 1.8.1
- VSCode version: 1.34.0 (user setup)
- OS platform and version: Windows 10 pro 1809
- NodeJS version: 10.15.3
- Cordova version: 9.0.0

Also I copied following information directly from VSCode Help/About:
Version: 1.34.0 (user setup)
Commit: a622c65b2c713c890fcf4fbf07cf34049d5fe758
Date: 2019-05-15T21:59:37.030Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763

**Comment by SounD120** [comment]
Hi @rustedwizard . It might be connected with recent extension's publisher change. Could you please try to change publisher from `vsmobile` to `msjsdiag` in extension's `package.json` file? To do that please do the following:
* Delete the extension and reload VS Code
* Install the extension
* Run `code %USERPROFILE%\.vscode\extensions\msjsdiag.cordova-tools-1.8.1\package.json` command in your terminal to open extension's `package.json` file. 
* Find `publisher` field and replace its value by `msjsdiag`
* Reload VS Code

Please let us know if this helps.

**Comment by rustedwizard** [comment]
> Hi @rustedwizard . It might be connected with recent extension's publisher change. Could you please try to change publisher from `vsmobile` to `msjsdiag` in extension's `package.json` file? To do that please do the following:
> 
> * Delete the extension and reload VS Code
> * Install the extension
> * Run `code %USERPROFILE%\.vscode\extensions\msjsdiag.cordova-tools-1.8.1\package.json` command in your terminal to open extension's `package.json` file.
> * Find `publisher` field and replace its value by `msjsdiag`
> * Reload VS Code
> 
> Please let us know if this helps.

It works now, thanks!

**Comment by SounD120** [comment]
@rustedwizard Glad to hear it. Then I'll close this issue, feel free to reopen if you have any questions. Happy coding!
Related issue: #531
