### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by brunohonda-outcenter** [microsoft/vscode-cordova#539]
- Issue Type: `Performance`
- Extension Name: `cordova-tools`
- Extension Version: `1.8.2`
- OS Version: `Linux x64 5.1.6-300.fc30.x86_64`
- VSCode version: `1.34.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/home/brunoah/msjsdiag.cordova-tools-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by ruslan-bikkinin** [comment]
Hi @brunohonda-outcenter and thanks for reaching us. Please attach `/home/brunoah/msjsdiag.cordova-tools-unresponsive.cpuprofile.txt` so we could analyze it and get more information about your case.

**Comment by SounD120** [comment]
Hi @brunohonda-outcenter do you have a chance to look at this? CPU profiling file `/home/brunoah/msjsdiag.cordova-tools-unresponsive.cpuprofile.txt` is needed to analyze your case, so could you please attach it?

**Comment by brunohonda-outcenter** [comment]
Sorry, I did not know what this file was and delete it before I got your message.

**Comment by ruslan-bikkinin** [comment]
@brunohonda-outcenter unfortunately, we can't do much about it then, because the information from this file is crucial for understanding what is slowing extension down. If you face this issue again, please, submit the file.
