### ISSUE TITLE
Android: device not found when debugging through emulator

### ISSUE THREAD

**Issue by Iar0** [microsoft/vscode-cordova#558]
## Actual Behavior
1. Do a fresh installation of the plugin in a ionic project
2. Open the android emulator
3. run configuration "Run Android on device" (as described in the README for android emulator)
4. Process fails to deploy

## Expected Behavior
1. "Run android on device" should run the app on the android emulator

## Software versions
- Cordova VS Code extension version: 1.8.5
- VSCode version: 1.36.1
- OS platform and version: Mac
- NodeJS version: v10.10.0
- Cordova version: 9.0.0 (cordova-lib@9.0.1)
- Cordova-Android/iOS/Windows version:

## Outputs (Include if relevant)
- Output of the Debug Console (View -> Toggle Debug Console):
```
``` 
CordovaError: Failed to deploy to device, no devices found.
    at /Users/michele/dev/frontend/platforms/android/cordova/lib/device.js:55:35
    at _fulfilled (/Users/michele/dev/tmi/frontend/node_modules/q/q.js:834:54)
    at /Users/michele/dev/frontend/node_modules/q/q.js:863:30
    at Promise.promise.promiseDispatch (/Users/michele/dev/frontend/node_modules/q/q.js:796:13)
    at /Users/michele/dev/frontend/node_modules/q/q.js:604:44
    at runSingle (/Users/michele/dev/frontend/node_modules/q/q.js:137:13)
    at flush (/Users/michele/dev/frontend/node_modules/q/q.js:125:13)
    at process._tickCallback (internal/process/next_tick.js:61:11)
```
```
- Output of the Cordova output channel (View -> Toggle Output -> Select Cordova in ListBox): Cannot find it
- Output of the Developer Tools console (Help -> Toggle Developer Tools -> Select Console tab):
```
console.ts:134 [Extension Host] No editors associated with document: /Users/michele/dev/frontend/package.json
t.log @ console.ts:134
log.ts:173   ERR Invalid guestInstanceId: null: Error: Invalid guestInstanceId: null
    at Object.getGuestForWebContents (/Applications/Visual Studio Code.app/Contents/Resources/electron.asar/browser/guest-view-manager.js:430:11)
    at /Applications/Visual Studio Code.app/Contents/Resources/electron.asar/browser/rpc-server.js:449:34
    at EventEmitter.ipcMain.on.args (/Applications/Visual Studio Code.app/Contents/Resources/electron.asar/browser/rpc-server.js:278:21)
    at EventEmitter.emit (events.js:182:13)
    at WebContents.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/electron.asar/browser/api/web-contents.js:370:21)
    at WebContents.emit (events.js:182:13)
```

- run configuration code
```
        {
            "name": "Run Android on device",
            "type": "cordova",
            "request": "launch",
            "platform": "android",
            "target": "device",
            "port": 9222,
            "sourceMaps": true,
            "cwd": "${workspaceFolder}",
            "ionicLiveReload": false
        },
```

Following the README, it says that in this case I should follow these instructions https://github.com/microsoft/vscode-cordova#debug-your-cordova-based-project to connect the device. The problem that I have is that I cannot find any double arrow icon in the android emulator
![image](https://user-images.githubusercontent.com/8393332/61725117-76588a80-ad6f-11e9-8678-aed4a03cc61e.png)

I managed to have it working by running `adb devices`, getting the name of the emulator device from the list and then replacing the value of `target` with the found device (e.g. emulator-5584). I would like to have the same behaviour with the default config that I shared

**Comment by ruslan-bikkinin** [comment]
Hi @Iar0 and thanks for questioning. If you are targeting Android Studio emulator please use `Run Android on emulator` debug scenario instead. The documentation page you are referring to is for Visual Studio Emulator for Android users.

Please let me know if it works for you.

**Comment by Iar0** [comment]
hey @ruslan-bikkinin thanks for the clarification! I managed to have it working by running the `Run Android on emulator` command ✌️
