### ISSUE TITLE
'Debugger' domain was not foundError processing "attach"

### ISSUE THREAD

**Issue by lqrz** [microsoft/vscode-cordova#559]
## Actual Behavior
1. I'm trying to debug an ionic app via VSCode by attaching to a running app on my iphone, and I get the following error:
```
'Debugger' domain was not foundError processing "attach": 'Debugger' domain was not found: [object Object]
```

I'm running ios_webkit_debug_proxy:
```
Listing devices on :9221
Connected :9222 to user’s iPhone (dd28c4ac342c4947938c0ebe89bdaec33201489f)
```

Here is my launch.json config:
```
        ...
        {
            "name": "Attach to running ios on device",
            "type": "cordova",
            "request": "attach",
            "platform": "ios",
            "target": "device",
            "port": 9221,
            "sourceMaps": true,
            "cwd": "${cwd}"
        }
       ...
```

I've found [this issue](https://github.com/ionic-team/ionic/issues/18733). Does it mean there is no way to go about this? It used to work in the past, what has changed? Is there any workaround?

Thanks!

### Ionic info
```
cli packages:
    @ionic/cli-utils  : 1.19.3
    ionic (Ionic CLI) : 3.20.1

global packages:
    cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1) 

local packages:
    @ionic/app-scripts : 3.2.1
    Cordova Platforms  : android 7.1.4 browser 5.0.4 ios 4.5.5
    Ionic Framework    : ionic-angular 3.9.2

System:
    Android SDK Tools : 26.1.1
    ios-deploy        : 1.9.4 
    ios-sim           : 8.0.1 
    Node              : v10.15.1
    npm               : 6.4.1 
    OS                : macOS
    Xcode             : Xcode 10.3 Build version 10G8 
```

### Others
- Cordova VS Code extension version: 1.8.5
- VSCode version: 1.36.1
- OS platform and version: iOS 12.4

## Outputs (Include if relevant)

- Output of the Debug Console:
```
Attaching to ios
Configuring debugging proxy
Unable to find target app webview, trying to fallback to the only running webview
Attaching to app.
'Debugger' domain was not foundError processing "attach": 'Debugger' domain was not found: [object Object]
```

**Comment by francescodoffizi** [comment]
I think this is related to https://github.com/microsoft/vscode-cordova/issues/546 that has been closed after this comment and as far as I can see nothing happened on cordova-plugin-ionic-webview

> 

I would recommend posting a feature request in the Ionic WebView Plugin repo. The code required to make this happen probably needs to come from there: https://github.com/ionic-team/cordova-plugin-ionic-webview.I am going to close this as this is a webview issue, not an issue with the framework. Thanks!
--

**Comment by ruslan-bikkinin** [comment]
Hi guys, yes, this is Ionic Web View issue, here is the related feature request for bringing back support for inspecting on iOS 12.3+ devices: https://github.com/ionic-team/cordova-plugin-ionic-webview/issues/417. 

Closing this as duplicate: https://github.com/microsoft/vscode-cordova/issues/546
