### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by michaelleepow90** [microsoft/vscode-cordova#560]
- Issue Type: `Performance`
- Extension Name: `cordova-tools`
- Extension Version: `1.8.5`
- OS Version: `Windows_NT x64 10.0.18362`
- VSCode version: `1.37.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\micha\msjsdiag.cordova-tools-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by SounD120** [comment]
Hi @michaelleepow90 and thanks for reaching us. Could you please attach `vsmobile.cordova-tools-unresponsive.cpuprofile.txt` as it said in [VS Code documentation](https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load#dealing-with-high-cpu-load-issues) and in your issue description? We can't do much about it without this info.

**Comment by SounD120** [comment]
Hi @michaelleepow90 . Unfortunately, we can't do much without CPU profiling file, because the information from this file is crucial for understanding what is slowing extension down. If you face this issue again, please, submit the file.
