### ISSUE TITLE
Node version mismatch

### ISSUE THREAD

**Issue by superandrew** [microsoft/vscode-cordova#565]
## Actual Behavior
1. When launched, ionic-app-scripts halts with an error because the selected node version isn't the same as the ionic project requirements (8.9.4)
2. I have a .nvmrc file with `v8.9.4` in it, and vs code terminal switches to that version.
 (the same command executed `node_modules/.bin/ionic-app-scripts build --target cordova --platform android` works in vs code's terminal)

## Expected Behavior
1. Cordova debugging configuration chooses the proper node version for the project, and the script works

## Software versions
- Cordova VS Code extension version:
1.8.5
- VSCode version:
1.37.1
- OS platform and version:
Mac OsX 10.14
- NodeJS version:
using `nvm`, in the current project should be 8.9.4
- Cordova version:
8
- Cordova-Android/iOS/Windows version:
?
## Outputs (Include if relevant)
- Output of the Debug Console (View -> Toggle Debug Console):

```
[2m[12:37:42][22m  lint finished [2min 2.28 s[22m 
2019-09-03T10:37:42.678Z ionic:lib:hooks Looking for ionic:build:after npm script.
> [32mcordova run android --device --verbose[39m
[ERROR] Command error.
'node_modules/.bin/ionic cordova run android --device --verbose --no-interactive' failed with exit code 1
```
- Output of the Cordova output channel (View -> Toggle Output -> Select Cordova in ListBox):
```
<empty>
```
- Output of the Developer Tools console (Help -> Toggle Developer Tools -> Select Console tab):
```
?
```

Probably I need to understand, if there is a way, how to switch the node version that get chosen when starting a debug session.

**Comment by RedMickey** [comment]
Hi @superandrew and thanks for reaching us.
```
nvm alias default 8.9.4
```
After that debug sessions inside VS Code should use the default version.
Please let us know if this works for you.

**Comment by RedMickey** [comment]
Hi @superandrew. Do you have a chance to look at this?

**Comment by superandrew** [comment]
@RedMickey yes, it seems to be working, however I find difficult to understand that I need to change a system wide setting such as the default version of node specified in nvm to use that particular version in a debugging configuration. Is this the only way?

**Comment by RedMickey** [comment]
Hi @superandrew. NVM uses a shell function (instead of an environment variable) to configure the path to the Node.js. Unfortunately this is not supported in VS Code on macOS, according to official [VS Code issue](https://github.com/Microsoft/vscode/issues/19951).

**Comment by superandrew** [comment]
I see. To your knowledge the `runtimeVersion` attribute is appliable to workspace? That would be a nice workaround instead of a VS Code-wide setting.

**Comment by RedMickey** [comment]
Hi @superandrew. At the moment this parameter is not supported by the extension. But we [added this enhancement](https://github.com/microsoft/vscode-cordova/issues/571) to our backlog and consider it in order of priorities.
