### ISSUE TITLE
Please add support for electron

### ISSUE THREAD

**Issue by lubo08** [microsoft/vscode-cordova#568]
## Actual Behavior
No electron support.

## Expected Behavior
Please add support for electron

## Software versions
latest

**Comment by SounD120** [comment]
Hi @lubo08 and thanks for reaching us. Cordova Tools extension was developed for debugging Cordova applications. For debugging Electron applications I recommend to try [VS Code Debugger for Chrome](https://marketplace.visualstudio.com/items?itemName=msjsdiag.debugger-for-chrome).
