### ISSUE TITLE
Add NVM Node.js version support

### ISSUE THREAD

**Issue by SounD120** [microsoft/vscode-cordova#571]
As for now VS Code [doesn't support debugging with NVM on macOS](https://github.com/Microsoft/vscode/issues/19951#issuecomment-422077768). But there is a [`runtimeVersion`](https://github.com/microsoft/vscode-node-debug/blob/fc36cb94a3a556803f5284a0e86a1e1564059076/package.nls.json#L48) debug configuration variable exists in [`vscode-node-debug`](https://github.com/microsoft/vscode-node-debug) to switch Node.js versions via nvm for debug sessions inside VS Code. We can investigate if we can implement it the [same way as in Node debugger](https://github.com/microsoft/vscode-node-debug/blob/fc36cb94a3a556803f5284a0e86a1e1564059076/src/node/extension/configurationProvider.ts#L204-L273).

**Comment by superandrew** [comment]
I think this is a really nice enhancement for developers that have more than 1 project/node/cordova version.
