### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by starlleytk** [microsoft/vscode-cordova#577]
- Issue Type: `Performance`
- Extension Name: `cordova-tools`
- Extension Version: `1.8.6`
- OS Version: `Linux x64 4.15.0-65-generic`
- VSCode version: `1.38.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/home/starlley/msjsdiag.cordova-tools-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by SounD120** [comment]
Hi @starlleytk . Unfortunately, we can't do much without CPU profiling file, because the information from this file is crucial for understanding what is slowing extension down. If you face this issue again, please, submit the file.
