### ISSUE TITLE
Cannot serve to browse ionic4

### ISSUE THREAD

**Issue by lqrz** [microsoft/vscode-cordova#580]
## Actual Behavior
1. Im trying to debug my ionic4 app using vscode cordovatools, but when i launch the `Serve to browser (ionic serve)`  option, I get an error back:

```Cannot perform Ionic serve/watch for project type: angular```

Comment aside: my project runs OK if I run `ionic serve` from a terminal.

## Software versions
- Cordova VS Code extension version: 1.8.6
- VSCode version: 1.37.0
- OS platform and version: osx / centos7
- NodeJS version: v10.16.3
- Cordova version: 9.0.0 

## Outputs
This is my `laucn.json` config entry:
```
{
    "name": "Serve to the browser (ionic serve)",
    "type": "cordova",
    "request": "launch",
    "platform": "serve",
    "cwd": "${workspaceFolder}",
    "devServerAddress": "http://localhost",
    "sourceMaps": true,
    "ionicLiveReload": true,
    "devServerTimeout": 300000,
    "runArguments": ["--no-open"]
}
```

My `ionic.config.json` indicates it's an angular type ionic app (this is done by default by the ionic CLI):
```
{
  "name": "mobileapp",
  "integrations": {
    "cordova": {}
  },
  "type": "angular",
  "app_id": ""
}
```

And this is the output error:
```
Parameter target is not set - emulator will be used
Launching for serve (This may take a while)...
Starting Ionic dev server (live reload: true)
[ERROR] Cannot perform Ionic serve/watch for project type: angular.

If you'd like the CLI to try to detect your project type, you can unset the type attribute in ionic.config.json.
        

The Ionic live reload server exited unexpectedly
```

**Comment by SounD120** [comment]
Hi @lqrz and thanks for reaching us. Which version of Ionic is installed globally on your machine?
You can try the following command to get the version:
```
ionic -v
```
Also Ionic 4 has the `angular` type instead of `ionic-angular` which is for Ionic 3. 
Could you please also try to run serve scenario on a freshly created Ionic 4 app and let us know how it works for you?
You can use the following command to do that:
```
ionic start ionic4_app tabs --cordova --type=angular --no-link
```

**Comment by lqrz** [comment]
Hi, @SounD120 !

I'm using Ionic version `5.4.2`.

Wrt serving the fresh app, I created the project using the command you mentioned (i.e. `ionic start ionic4_app tabs --cordova --type=angular --no-link`). And when using VScode's Cordova tools to serve it, I get the same error:

```
Parameter target is not set - emulator will be used
Launching for serve (This may take a while)...
Starting Ionic dev server (live reload: true)
[WARN] The --nobrowser option has been deprecated. Please use --no-open.
[ERROR] Cannot perform Ionic serve/watch for project type: angular.

        If you'd like the CLI to try to detect your project type, you can unset the type attribute in ionic.config.json.
        

The Ionic live reload server exited unexpectedly
``` 

That is, using the following entry on my `launch.json`:
```
        {
            "name": "Serve to the browser (ionic serve)",
            "type": "cordova",
            "request": "launch",
            "platform": "serve",
            "cwd": "${workspaceFolder}",
            "devServerAddress": "localhost",
            "sourceMaps": true,
            "ionicLiveReload": true
        }
```

**Comment by SounD120** [comment]
Hi @lqrz . Could you please try to remove `type` attribute from the `ionic.config.json` file and try to run  `Serve to the browser` scenario?

**Comment by lqrz** [comment]
This is what i get if  i remove the `type` property from the `ionic.config.json`:

```
[ERROR] Could not determine project type (project config: ./ionic.config.json).

        For Ionic Angular projects, make sure ionic-angular is listed as a dependency in package.json.
        For Ionic 1 projects, make sure ionic is listed as a dependency in bower.json.
        
        Alternatively, set type attribute in ionic.config.json to one of: ionic-angular, ionic1, custom.
        
        If the Ionic CLI does not know what type of project this is, ionic build, ionic serve, and other commands may not work. You can use the custom project type if that's okay.
```

**Comment by SounD120** [comment]
@lqrz In my case it worked with `angular` project. Do you use nvm? It seems that Ionic versions in terminal and in VS Code debug session are not the same.

**Comment by lqrz** [comment]
@SounD120 Oh, I see! I do use NVM. Is there a way in which I can specify which runtime to use in the VSCode scenario? I would usually use the property `runtimeExecutable`, but I cannot use it here.

**Comment by SounD120** [comment]
@lqrz Then this problem looks like https://github.com/microsoft/vscode-cordova/issues/565 . There is no `runtimeExecutable` debug parameter yet, but we [have it in our backlog](https://github.com/microsoft/vscode-cordova/issues/571).
For now I'd recommend to set a default Node.js version with a command:
```
nvm alias default <version>
```
Please let us know if it works for you.

**Comment by lqrz** [comment]
Like a charm, @SounD120 ! After adding the nvm alias and restarting the VSCode, I can serve and debug my app. Thanks so much for your help!

**Comment by SounD120** [comment]
That's great, @lqrz ! I am closing that issue. Please feel free to open new ones if needed.
