### ISSUE TITLE
Unable to deploy to ios device

### ISSUE THREAD

**Issue by ryanhalley** [microsoft/vscode-cordova#585]
Hi. I've got a VM running MacOS, with my iphone device connected via lightning cable. I had many issues due to the build I inherited needing a) the legacy build mode and b) use manual signing, however, I'm now at the point where I can deploy to my device, providing I use a manual build command (ionic cordova build ios -- --buildFlag="-UseModernBuildSystem=0"), then click the Run button in the XCode Workspace after selecting my connected device. I have not managed to deploy to my device (ionic cordova run ios -cl -- --device --buildConfig=build.json) from the command line at all though, nor through VS Code.
When I try to use VS Code to debug, I notice that the command line mentioned the legacy build switch, but I'm not sure how it knows I need that - I'm guessing it checked the XCode workspace file:
```
ionic-app-scripts build --target cordova --platform ios --buildFlag=-UseModernBuildSystem=0 --buildConfig=build.json --no-interactive
```
I have tried adding each of the delay switches in the launch.json file, but no joy.
I feel I'm really close, perhaps just one setting missing.

Please let me know if I've left anything out. Thanks for your help.

## Actual Behavior
** EXPORT SUCCEEDED **
Installing app on device
Launching app
Unable to mount developer disk image.

## Expected Behavior
1. Deploys to device.

## Software versions
- Cordova VS Code extension version: 1.8.6
- VSCode version: 1.39.0
- OS platform and version: MacOS 10.14.6
- NodeJS version: 10.11.0 as shown in VS About. Node is v10.16.3
- Cordova version: 8.1.2
- Cordova-Android/iOS/Windows version: cordova-ios ^5.0.1

## Outputs (Include if relevant)
- Output of the Debug Console (View -> Toggle Debug Console):
```
** EXPORT SUCCEEDED **
Installing app on device
Launching app
Unable to mount developer disk image.
```

```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [


        {
            "name": "Run iOS on device",
            "type": "cordova",
            "request": "launch",
            "platform": "ios",
            "target": "device",
            "sourceMaps": true,
            "cwd": "${workspaceFolder}",
            "ionicLiveReload": true,
            "port": 9222,
            "runArguments": [
                "--buildConfig=build.json"
            ],
        },
        {
            "type": "chrome",
            "request": "launch",
            "name": "Launch Chrome against localhost",
            "url": "http://localhost:8080",
            "webRoot": "${workspaceFolder}"
        }
    ]
}
```

```
{
    "ios": {
        "debug": {
            "codeSignIdentity": "iPhone Developer",
            "provisioningProfile": "our UUID",
            "developmentTeam": "team id",
            "packageType": "development"
        },
        "release": {
            "codeSignIdentity": "iPhone Developer",
            "provisioningProfile": "our UUID",
            "developmentTeam": "team id",
            "packageType": "app-store"
        }
    }
}
```

**Comment by RedMickey** [comment]
Hi @ryanhalley and thanks for reaching us. Could you please try to do the following steps according to this [comment](https://github.com/microsoft/vscode-cordova/issues/465#issuecomment-448156409) and tell us the results?
Could you please also send us the iOS version on your device?

**Comment by ryanhalley** [comment]
Thanks for getting back to me so quick.
That certainly made a difference, the IPA is being deployed to the phone and is attempting to start, but then hanging at the splashscreen.

```
** EXPORT SUCCEEDED **
Installing app on device
Launching app
Unable to launch application.
```

An additional problem though, is I am now not able to deploy to my phone from within XCode anymore - I get 'process launch failed: timed out waiting for app to launch'. Unlike in VC, my phone stays on the home screen, I see the deployed app icon appear, but the app doesn't change to splashscreen, but if I look at the task list, I do see the app splash there, just in the background. In XCode, the 'details' screen, after the launch error popup shows
```
Could not launch “MyApp”
Domain: IDEDebugSessionErrorDomain
Code: 3
Failure Reason: Ryan's iPhone has denied the launch request.
Internal launch error: process launch failed: timed out waiting for app to launch
--
process launch failed: timed out waiting for app to launch
Domain: IDEDebugSessionErrorDomain
Code: 3
--
```

I've tried rebooting MacOS, after the brew commands, in case that affected the driver change but no difference.

My iOS version is 13.1.2, running on an iPhone 7 Plus.
MacOS is 10.14.4

**Comment by RedMickey** [comment]
@ryanhalley, could you please try to launch your application from system terminal by using the following command?
```
cordova run ios --device
```
Cordova uses [ios-deploy lib](https://github.com/ios-control/ios-deploy) for deploying and launching applications on iOS devices. As for now there are some incompatibilities with iOS 13 and Xcode 11. You can find more information about that issue [here](https://github.com/ios-control/ios-deploy/issues/399#issuecomment-535001966).
You can use the workaround for this issue until the problem mentioned above is fixed. Please try to do the following steps to attach to debugger:
1. Install your app on a device, by launching `Run iOS on device` scenario or using the command above.
1. Open installed app manually on your device.
1. Launch `Attach to running iOS on device` scenario in VS Code Cordova extension. Attach should work correctly.

Please let us know about the results.

**Comment by ryanhalley** [comment]
Hmm, yes, exactly the same issue as in the thread you linked.
```
cordova run ios --device

------ Debug phase ------
Starting debug of dcd5656a0dbae60dec58d917c02173b5e6441f1c (D111AP, iPhone 7 Plus, iphoneos, arm64) a.k.a. 'Ryan's iPhone' connected through USB...
[  0%] Looking up developer disk image
[ 90%] Mounting developer disk image
[ 95%] Developer disk image already mounted
2019-10-16 12:35:08.149 ios-deploy[13396:58411] [ !! ] Error 0xe800007f: Device doesn't support wireless sync. AMDeviceStartService(device, CFSTR("com.apple.debugserver"), &gdbfd, NULL)
ios-deploy: Command failed with exit code 253
```

I also tried to use the attach method, but the app moves to the fore on my phone and stays on splash screen:
```
Attaching to ios
Configuring debugging proxy
Unable to communicate with target
Unable to communicate with target
Unable to communicate with target
Unable to communicate with target
```

I see the final update in that thread was "I ended up rebuilding the binary with version 1.10.0 and now Cordova can launch it." - I'm not sure how to do that.

**Comment by RedMickey** [comment]
@ryanhalley, could you please try to reinstall `ios-webkit-debug-proxy` by using the following commands? The latest `ios-webkit-debug-proxy` version contains some work compatibility fixes for iOS 13.
```
brew uninstall ios-webkit-debug-proxy
brew install ios-webkit-debug-proxy --HEAD
```

**Comment by ryanhalley** [comment]
VC deploy gave me 'Unable to launch application.'
Trying to attach to running app, it stayed like this without any unable to communicate messages:
```
Attaching to ios
Configuring debugging proxy
```
I made a massive mistake and tapped the deployed application icon on my device to see if it was running - once it switched to the app, showing the stalled plashscreen, I then found that the Home button no longer responds to double-tap to kill tasks, or single tap to return to home screen, and also holding the power off button no longer allows me to reboot the device - I'm stuck in this app. Not sure what I can do now to kill it, I can only lock and unlock my device :/ Sadly, Siri, which did trigger once, doesn't let you reboot your device. Is there a magic terminal command I can use to kill the app?
I tried repeating the debug deploy from VC and from terminal, in case it could undo the issue, but no success.

**Comment by RedMickey** [comment]
The reason of such a behavior may be in disabled `Safari Web Inspector` on iOS device.
> Trying to attach to running app, it stayed like this without any unable to communicate messages:
> ```
> Attaching to ios
> Configuring debugging proxy
> ```
Could you please check if `Safari Web Inspector` option is enabled on your device?
To reach the Web Inspector option you can do the following:
```
Tap Settings > Safari > Advanced
```
If it is disabled, please turn it on and try to execute attach scenario again.

**Comment by ryanhalley** [comment]
Almost there! Some updates:
1. 'cordova run ios --device' gave me the 'Device doesn't support wireless sync'
2. Debugging from VC, I did see app launch, but the VC showed a popup with a launch error. I tried to attach and got:
```
Attaching to ios
Configuring debugging proxy
Attaching to app.
'Debugger' domain was not foundError processing "attach": 'Debugger' domain was not found: [object Object]
```
I then tried some of the ionic commands:
3. 'ionic cordova run ios --device' launched app correctly.
4. 'ionic cordova run ios -c --device' did launch the app, no logging though.
5. 'ionic cordova run ios -l --device' hung at splash screen, but I was able to kill the app. 

Finally, I returned to VC debugging, and I have not been able to see the app launch since then. It now hangs at the splashscreen, and much later on I eventually see this:
```
** EXPORT SUCCEEDED **

Installing app on device
Launching app
Unable to launch application.
```

**Comment by RedMickey** [comment]
@ryanhalley, now I see your problem. We already have [an issue](https://github.com/microsoft/vscode-cordova/issues/564) related to such behavior. Unfortunately this is an external bug, and for now the extension can't provide Ionic debugging for devices with iOS version over 12.3.0. You can find more info [here](https://github.com/microsoft/vscode-cordova/issues/561#issuecomment-534990180).

**Comment by ryanhalley** [comment]
Thanks for all your help! It may not work, but at least I know why. What I find odd, is that I can't seem to get consistent results - it's as if a state is cached somewhere. I'd be happy if I could at least run 'ionic cordova run ios --device', and have it work each time.

**Comment by RedMickey** [comment]
@ryanhalley, I was glad to help you. Since this behavior is connected to ios-webkit-debug-proxy issues I am closing this issue. Please feel free to open new ones if needed.
