### ISSUE TITLE
'Unable to find adb'. Adb is in the path of my Mac OS Catalina

### ISSUE THREAD

**Issue by MInesGomes** [microsoft/vscode-cordova#586]
## Actual Behavior
When I try to debug on device or emulator it gives me this error.

> Attaching to android Unable to find adb. Please ensure it is in your
> PATH and re-open Visual Studio Code

## Expected Behavior
Debug Message appearing in debug tab.

## Software versions
Version: 1.39.2
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 19.0.0
MacOS: Catalina 10.15

```
cat ~/.zshrc 
export ANDROID_HOME=/Users/$USER/Library/Android/sdk
export PATH=${PATH}:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools
```

## adb is in Mac path

If I do on terminal inside or outside vscode 

`$adb devices`

I get:
    
    List of devices attached
    42003f1d9610c50b	device

So **adb is in the path.**

I even tried to launch VSCode from terminal

    code <myFolder>

 
after doing this:
[shell command install code][1]

  [1]: https://code.visualstudio.com/docs/setup/mac

But I still get the same error.

After upgrading to Mac Catalina I can't debug my ionic app anymore ...
How can I tell VSCode the path to adb?

## Outputs (Include if relevant)
- Output of the Debug Console (View -> Toggle Debug Console):
```
PASTE OUTPUT HERE
```
- Output problems 
```
Could not run phased build action using Gradle distribution 'https://services.gradle.org/distributions/gradle-5.6.1-bin.zip'.
Build completed with 2 failures.
Script '/Users/mirg/Workspace/ioNms/platforms/android/CordovaLib/cordova.gradle' line: 121
A problem occurred evaluating project ':app'.
Unable to determine Android SDK directory.
```
- Output of the Developer Tools console (Help -> Toggle Developer Tools -> Select Console tab):
```
[native-run]   'install',
[native-run]   '-r',
[native-run]   '-t',
[native-run]   'platforms/android/app/build/outputs/apk/debug/app-debug.apk' ]
[native-run] Starting application activity io.ionic.starter/io.ionic.starter.MainActivity...
[native-run] 2019-10-16T19:55:12.867Z native-run:android:utils:adb:startActivity Invoking adb: '/Users/mirg/Library/Android/sdk/platform-tools/adb' [ '-s',
[native-run]   '42003f1d9610c50b',
[native-run]   'shell',
[native-run]   'am',
[native-run]   'start',
[native-run]   '-W',
[native-run]   '-n',
[native-run]   'io.ionic.starter/io.ionic.starter.MainActivity' ]
[native-run] Run Successful
App successfully launched
Attaching to android
Unable to find adb. Please ensure it is in your PATH and re-open Visual Studio Code
```

**Comment by SounD120** [comment]
Hi @MInesGomes and thanks for reaching us. I am using such `.zshrc` config on macOS 10.15 and Ionic applications debugging works without any problems with the extension:
```
export ANDROID_HOME=/Users/$USER/Library/Android/sdk
export ANDROID_SDK_ROOT=$ANDROID_HOME
PATH="$PATH:$ANDROID_HOME/emulator:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools"
```
Could you please try this config and let us know how it works for you?

**Comment by MInesGomes** [comment]
Thank you @SounD120.

I set your lines in .zshrc and did `code <MyDirectory>`
 I still get the  error 

> Attaching to android Unable to find adb. Please ensure it is in your
> PATH and re-open Visual Studio Code

I also did:
clean  .zshrc   
`code <MyDirectory>` 
in VSCode Terminal adb devices
>cmd: no adb found

then set again your .zshrc  content 
and in VSCode Terminal adb devices
>List of devices attached ...

But If I try to attach debug gives the error ...

Is your launch.json like this?
 ```
   {
            "name": "Attach to running android on device",
            "type": "cordova",
            "request": "attach",
            "platform": "android",
            "target": "device",
            "port": 9222,
            "sourceMaps": true,
            "cwd": "${workspaceFolder}"
        },
```

I am able to run to android and to emulator 
But to run I had to install with the flag `--unsafe-perm`
`sudo npm i -g --unsafe-perm native-run`

because it was giving write permissions error ...

**Comment by SounD120** [comment]
@MInesGomes Do you use NVM?

**Comment by MInesGomes** [comment]
@SounD120 I used in Monjave. Now says:

`zsh: command not found:`

how do you suggest I install it?

**Comment by SounD120** [comment]
>   {
           "name": "Attach to running android on device",
           "type": "cordova",
           "request": "attach",
           "platform": "android",
           "target": "device",
           "port": 9222,
           "sourceMaps": true,
           "cwd": "${workspaceFolder}"
       },

@MInesGomes  Hmm, ok. Yes, I use the same debug scenario. 

Could you please copy the whole content of your `.zshrc` file and attach it here?
Also it will be helpful if you run VS Code, and do the following:
```
open Help -> Toggle Developer Tools -> open Console -> run console.log(process.env.PATH) command
```
This command will show PATH environment variable for VS Code Node.js process context.
Could you please send it to us either?

**Comment by MInesGomes** [comment]
@SounD120 I didn't have any ~/.zshrc . I created
cat ~/.zshrc 
```
export ANDROID_HOME=/Users/$USER/Library/Android/sdk
export ANDROID_SDK_ROOT=$ANDROID_HOME
PATH="$PATH:$ANDROID_HOME/emulator:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools"
```

**Comment by MInesGomes** [comment]
Sorry @SounD120 and thank you very much for your help. :-)
I updated Catalina last night and today I tried and is working

**Comment by SounD120** [comment]
@MInesGomes Glad to hear that. Feel free to reach out to us if you have any questions about the extension.

**Comment by guhyeon** [comment]
I've succeeded. 

1. Setting Environment preferences.
1.1. Start Terminal
 command + spacebar, enter terminal and click terminal app

1.2. edit bash profile on terminal
vi ~/.bash_profile

copy and paste bellow lines.
```
export ANDROID_HOME=$HOME/Library/Android/sdk
export ANDROID_SDK_ROOT=$HOME/Library/Android/sdk
export PATH=$PATH:$ANDROID_HOME/emulator
export PATH=$PATH:$ANDROID_HOME/tools
export PATH=$PATH:$ANDROID_HOME/tools/bin
export PATH=$PATH:$ANDROID_HOME/platform-tools
```
type 
:wq enter


1.3. edit zsh profile
vi ~/.zprofile

copy and paste
```
source ~/.bash_profile
source ~/.bashrc
```
type 
:wq enter


2. Setting visual studio code with shell script available.
2.1. open visual studio code
2.2. command + shift + p
2.3. type "shell command" and select install code command in path

3. terminate visual studio code
4. open terminal and open project with code command
code {Your Project Path}

**Comment by nikkhilchauhan** [comment]
Thanks worked for me hurrrr

**Comment by fabianoneumann** [comment]
> Hi @MInesGomes and thanks for reaching us. I am using such `.zshrc` config on macOS 10.15 and Ionic applications debugging works without any problems with the extension:
> 
> ```
> export ANDROID_HOME=/Users/$USER/Library/Android/sdk
> export ANDROID_SDK_ROOT=$ANDROID_HOME
> PATH="$PATH:$ANDROID_HOME/emulator:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools"
> ```
> 
> Could you please try this config and let us know how it works for you?

Nice, it worked for me! Thanks!

**Comment by iulian0512** [comment]
worked for me on
 ProductName:	Mac OS X
ProductVersion:	10.15.7
BuildVersion:	19H2
AND
Android Studio 4.1.1
Build #AI-201.8743.12.41.6953283, built on November 5, 2020
Runtime version: 1.8.0_242-release-1644-b3-6915495 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

**Comment by fisforfaheem** [comment]
pleas help me also tell how to enter PATH and username?? and give an example as well I am using mac

**Comment by Ehtisham-gillani** [comment]
Love U Bro

**Comment by Ehtisham-gillani** [comment]
Really helpfull
