### ISSUE TITLE
Custom workspace path not working.

### ISSUE THREAD

**Issue by Hadatko** [microsoft/vscode-cordova#591]
## Actual Behavior
When cwd is extended to e.g.: "cwd": "${workspaceRoot}/gui/android",
1. When no vscode workspace settings are placed in ${workspaceRoot}/gui/android then running debug is executing no code (no output in debug console). But Visual Studio Code is prettending doing something due to some blue bar moving.
2. When some default vscode workspace settings are placed in ${workspaceRoot}/gui/android then running debug is showing An error occurred while handling message: GET_RUN_ARGUMENTSError: connect ENOENT /tmp/vscodecordova-490dc40a8f4854b79769e091c01008a9.sock

## Expected Behavior
1. Working some way as cwd would be "cwd": "${workspaceRoot}" -> do something, do not stuck before beginning.

## Software versions
- Cordova VS Code extension version: 1.9.0
- VSCode version:1.40.2
- OS platform and version: Kubuntu 19.10
- NodeJS version: 11.15.0
- Cordova version: 9.0.0
- Cordova-Android/iOS/Windows version: android@8

**Comment by RedMickey** [comment]
Hi @Hadatko and thanks for reaching us. You can use [VS Code multi-root approach](https://code.visualstudio.com/docs/editor/multi-root-workspaces) to work with subdirectories. For now the extension supports only that approach.
You can do the following to add a folder to your workspace:
1. Open VS Code
1. Click `File` from the top menu, then select `Add Folder to Workspace`
1. Choose your project folder and add it

We will add error notification about wrong `cwd` value.

**Comment by Hadatko** [comment]
Ok thanks. I was able to do it this way, but it is not nice because i have opened two folders in workspace and one is like root and second root/gui/android.

**Comment by RedMickey** [comment]
Hi @Hadatko, the fix has been merged with master branch. It will be available in the next extension version, so I'm closing this issue. Feel free to open new ones if needed.

**Comment by Hadatko** [comment]
Thank you very much. Do you know when the new extension version will be released?

**Comment by Hadatko** [comment]
Oh you just added alert that cwd need be set to root directory. So still no support for custom paths. Pitty. But better than nothing. Are you considering to support custom cwd?

**Comment by RedMickey** [comment]
@Hadatko, with respect to the custom workspace feature support we don't have plans to implement that in the nearest future, but feel free to send your feature request. We'll consider it in order of priorities. 
Unfortunately I don’t have the exact date of a new release, but hopefully it will be done in the nearest weeks. We’ll update you as soon as new version will be released.

**Comment by Hadatko** [comment]
Where i can send feature request? E.g chrome debbuger works with custom path:
"configurations": [{
        "type": "chrome",
        "request": "launch",
        "name": "Launch Chrome against localhost",
        "url": "http://localhost:8100",
        **"webRoot": "${workspaceFolder}/gui/html",**
        "disableNetworkCache": true
    }]

**Comment by RedMickey** [comment]
@Hadatko, you can open a new issue containing desired enhancement.

**Comment by Hadatko** [comment]
Thanks. I am going to do it.

**Comment by huangfeihong1860** [comment]
I used the cordova tools in vscode to debug web project,  I run the comand (run android on emulator )
but get a message,can you help me!
An error occurred while handling message: GET_RUN_ARGUMENTSError: connect ENOENT \\?\pipe\vscodecordova

 {
            "name": "Simulate Android in browser",
            "type": "cordova",
            "request": "launch",
            "platform": "android",
            "target": "chrome",
            "simulatePort": 8000,
            "livereload": true,
            "sourceMaps": true,
            "cwd": "${workspaceFolder}"
        },
