### ISSUE TITLE
Support custom cwd paths

### ISSUE THREAD

**Issue by Hadatko** [microsoft/vscode-cordova#594]
Hi i would like to see this feature in your great extension. I want to reduce amount of redundant directories in my workspace. 

## Actual Behavior
1. Not supported. CWD need be workspace root dir.

## Expected Behavior
1. CWD could be customed.

E.g. Google chrome debbuger support this:
"configurations": [{
"type": "chrome",
"request": "launch",
"name": "Launch Chrome against localhost",
"url": "http://localhost:8100",
**"webRoot": "${workspaceFolder}/gui/html"**,
"disableNetworkCache": true
}]

Thanks 

Reference: #591

**Comment by haris44** [comment]
It can be really usefull, to use this vscode plugin with vue-cli cordova extensions for example :  https://github.com/m0dch3n/vue-cli-plugin-cordova

Path hierarchy with different folders (./ and ./src-cordova/) allow seperation between project node-modules and cordova plugin node-modules. I think it's a best practice with cordova project.  

Thanks

**Comment by michaelsogos** [comment]
Hi @haris44 

I have same scenario, did you find a solution in the meantime?

**Comment by haris44** [comment]
Hi @michaelsogos. yes, finally I used an other plugin : "Android Webview Debugging". It works really well ! (even with Chrome Webview)

**Comment by JiglioNero** [comment]
The problem was solved in this [PR](https://github.com/microsoft/vscode-cordova/pull/667) and the fix will be released in the next version of the extension.
