### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by abderrahmen13** [microsoft/vscode-cordova#615]
- Issue Type: `Performance`
- Extension Name: `cordova-tools`
- Extension Version: `1.9.3`
- OS Version: `Windows_NT x64 6.3.9600`
- VSCode version: `1.43.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\info-03\msjsdiag.cordova-tools-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by SounD120** [comment]
Hi @abderrahmen13 thanks for the report. Could you please attach `msjsdiag.cordova-tools-unresponsive.cpuprofile.txt` file as pointed in your issue because we need this file to analyze the reason of high CPU load.

**Comment by abderrahmen13** [comment]
[msjsdiag.cordova-tools-unresponsive.cpuprofile.txt](https://github.com/microsoft/vscode-cordova/files/4528052/msjsdiag.cordova-tools-unresponsive.cpuprofile.txt)

**Comment by SounD120** [comment]
Hi @abderrahmen13 . Thanks for the CPU profile file. I analyzed the CPU profile and it seems that high CPU has happened during the extension activation. Do you remember what did you do on your machine and in particular in VS Code when the high CPU load report has appeared? This information will help us to analyze the scenario that caused this in a more detailed way.
