### ISSUE TITLE
Extension installs several files/folders into my project--is it safe to exclude all of them from version control?

### ISSUE THREAD

**Issue by cagross** [microsoft/vscode-cordova#617]
Hello.  I have a Node project on my computer.  I opened the project in VSCode, and via the VSCode interface, installed the [Cordova Tools](https://marketplace.visualstudio.com/items?itemName=msjsdiag.cordova-tools) extension.  When I did so, the following files/folders were automatically created and added to the root of my project:

    .vscode/
    jsconfig.json
    typings/

I assume these are files/folders necessary to use the Cordova Tools extension with this project--correct?

Let's say I don't want any of the Cordova tools extension files version controlled in my Git repo, I realize I can probably modify my `.gitignore` file in [this manner](https://github.com/github/gitignore/blob/master/Global/VisualStudioCode.gitignore) to handle the `.vscode` directory (and its files).  But what about the other two--is it safe to add `jsconfig.json` and `typings` to my `.gitignore` file?  

I guess the essential question is:  are `jsconfig.json` and `typings` specific to only this extension?  Or could other extensions, packages, etc possibly try to install a file named `jsconfig.json`, or a folder named `typings`?  If, in the future, I want to install another extension--an extension I want to version control--and it also adds `jsconfig.json` or `typings`, then I probably should not .gitignore these right now.

Thanks.

## Software versions
- Cordova VS Code extension version: 1.9.3
- VSCode version:  1.44.2
- OS platform and version: Windows 10 x64
- NodeJS version:  13.13.0 is what is returned if I execute `node -v` from the command line.  But VSCode-->About indicates v12.8.1.  I'm not sure why.
- Cordova version:  9.0.0
- Cordova-Android/iOS/Windows version:  not sure how to check this

**Comment by SounD120** [comment]
Hi @cagross and thanks for the question. `.vscode` folder is a folder for VS Code extensions internal files such as `settings.json`, `launch.json`, `tasks.json` and others. VS Code shares this folder for all the extensions installed. With respect to `jsconfig.json` file and `.vscode/typings`: these files are intended to add VS Code Intellisense support for Cordova-based projects. If you delete them - they will be recreated by Cordova Tools when VS Code is reloaded, so they can be safely ignored in git. 
Please let us know if you have any questions.

**Comment by cagross** [comment]
Hi, thanks for the reply. 

> .vscode folder is a folder for VS Code extensions internal files such as settings.json, launch.json, tasks.json and others. VS Code shares this folder for all the extensions installed. 

Right, I understand all that about the `.vscode` folder.

> With respect to jsconfig.json file and .vscode/typings: these files are intended to add VS Code Intellisense support for Cordova-based projects. If you delete them - they will be recreated by Cordova Tools when VS Code is reloaded, so they can be safely ignored by git.

So to be clear, `jsconfig.json` is specific only to the Cordova Tools extension?  And the entire `typings` folder is specific to only the Cordova Tools extension?  Or are both of those more general files/folders, that are used by the Cordova Tools extension *and* perhaps many more extensions/ Node packages/etc?  If the former, I can .gitignore them without fear of any future issues.  But if the latter, then I might not want to simply .gitignore both right now--doing so might cause issues in the future.  Would you agree?

**Comment by SounD120** [comment]
@cagross `jsconfig.json` file marks that the folder contains JS based project and improves VS Code Intellisense for the workspace. You can find more information about this file here: https://code.visualstudio.com/docs/languages/jsconfig . 
With respect to `typings` folder I am not sure that this folder is specific for the Cordova Tools only and the typings might be configured on the different levels of the project according to the position of the `jsconfig.json` file in the folder hierarchy. This exact `.vscode/typings` folder is needed for Cordova Tools only, I think other extensions can create such folders in other places of the project for Intellisense support, it will depend of the extensions you use.

**Comment by cagross** [comment]
OK thanks for all that.  Along those lines, I have a separate, but related question.  As I mentioned, to install the extension, i first opened my project's folder in VSCode, then installed the extension via the VSCode GUI.  When I did so, the three new files in-question were added to the root of my project.  Is there any way to install the extension in another manner, one that creates those three new files in _another_ folder--a folder outside my project--and still retain all of the functionality provided by the plugin (e.g. in VSCode, start the 'Simulate Android in Chrome' debugging option)?

Or can I move `.vscode/`, `jsconfig.json`, `typings/` to a folder outside my project, and have the plugin retain its existing functionality?

**Comment by SounD120** [comment]
@cagross I think it makes no sense to move these files. You can move these files, but if you open your Cordova project for the next time `jsconfig.json` and `typings` will be generated by Cordova Tools again. 

You can add them to `.gitignore` list if it is needed since they are recreated, but keep in mind that `launch.json`, `settings.json` and `tasks.json` are shared between the extensions, so they can store some custom VS Code configurations for your needs so in this case it is better to store these files in Git.

With respect to your question - Cordova Tools doesn't support creation of the specific configuration files somewhere outside of the opened project since VS Code will not work correctly this way.

**Comment by cagross** [comment]
> but if you open your Cordova project for the next time jsconfig.json and typings will be generated by Cordova Tools again.

Well that's what I was asking--is there a way to have Cordova Tools save those files in an outside folder, even when opening the Cordova project the next time.  I guess the answer is 'no,' which is fine--was just wondering.

> You can add them to .gitignore list if it is needed since they are recreated, but keep in mind that launch.json, settings.json and tasks.json are shared between the extensions, so they can store some custom VS Code configurations for your needs so in this case it is better to store these files in Git.

Right, I understand that.  My issue is this.  Right now, I don't want to version control any of the code associated with Cordova Tools.  But, at the same time, I want to keep open the possibility of installing a different VSCode extension, and version controlling the code associated with that extension (should I decide to do that).  Is there a way to do that?  It looks like 'no.'  As you mentioned, files like `.vscode/launch.json` are written to by different VSCode extensions.  I'd need a way to version control only certain lines in a file, which I'm not sure exists.

**Comment by RedMickey** [comment]
Hi @cagross, `.vscode/launch.json` file is shared between all the extensions that are used in a particular workspace. This file is created only once, when you add the first debug configuration. After that, when this file already exists, you can open it and add additional debug configurations manually or using [`Add Configuration...`](https://code.visualstudio.com/docs/editor/debugging#_add-a-new-configuration) button. 
You can add `.vscode/launch.json` file, containing some configurations to version control system, and then, for example, when you clone a repository from Github and start debugging, VS Code editor won't create new `launch.json` file. You can also modify this file to use other exteninsions, but it will already be under control of version control system. So if you don't want to store configurations for all used extensions in version control system, you can remove unnecessary ones and leave only the necessary ones in the `launch.json` file before committing the changes.

**Comment by cagross** [comment]
> So if you don't want to store configurations for all used extensions in version control system, you can remove unnecessary ones and leave only the necessary ones in the launch.json file before committing the changes.

Right. But what if extension-a and extension-b each contribute their own code to `launch.json``. 
 I want to continue using both extension-a and extension-b when developing on my local computer. 
 But I want to commit the `launch.json` code for only extension-b to version control.  How can I do that?  It doesn't seem possible.  

For example, extension-a is simply an extension I prefer to use during development, and not an extension required for the project--members of my team can choose to use this extension or not.  But extension-b is one I want my entire team to use, with the exact same settings.

**Comment by RedMickey** [comment]
@cagross, do I understand you correctly, that you don't want to add (exclude from adding) some strings from `launch.json` file to version control system?

**Comment by cagross** [comment]
> you don't want to add (exclude from adding) some strings from launch.json file to version control system?

That's correct.  Specifically, let's say to my local VSCode, I install extension-a and extension-b.  Both extensions add their own configuration to `launch.json`.  I then want to add only extension-b to version control, i.e. I want to ensure nothing about extension-a is added to my Git repo.  Is there any way to do that?  It sounds like 'no,' i.e. if I want to version control the `launch.json` configuration  for extension-b, that I also have to version control the `launch.json` configuration for extension-a.  There is no way around that, since configuration for all extensions is added to the same file.

**Comment by SounD120** [comment]
@cagross Currently VS Code provides no way to implement such division and to store debug configurations for only one group of extensions excluding the others. You can try to open a discussion about this feature in [VS Code repository](https://github.com/microsoft/vscode). 
I am closing this issue for now, feel free to reopen if needed.

**Comment by cagross** [comment]
OK.  Thanks very much for all the info--I appreciate it.
