### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by tfhgzeo** [microsoft/vscode-cordova#626]
- Issue Type: `Performance`
- Extension Name: `cordova-tools`
- Extension Version: `1.9.4`
- OS Version: `Linux x64 5.4.0-31-generic`
- VSCode version: `1.45.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/home/gmoreira/msjsdiag.cordova-tools-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by SounD120** [comment]
Duplicate #517
