### ISSUE TITLE
Cordova RunAndroid on device finishes immediately 

### ISSUE THREAD

**Issue by wimZ** [microsoft/vscode-cordova#629]
When I start debug in both my Cordova projects, using vscode-insiders "run android on device"  starts but after 1 second it finishes.

The same project opened with the regular version of vscode works as expected.

Version: 1.46.0-insider (user setup)
Commit: e88b8d3
Date: 2020-05-13T08:04:48.706Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

No Outputs at all in debug window
```
- Output of the Developer Tools console (Help -> Toggle Developer Tools -> Select Console tab):
```
  ERR timeout after 1000 ms: Error: timeout after 1000 ms
    at t.RawDebugSession.handleErrorResponse (file:///C:/Users/wimz/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:3079:643)
    at file:///C:/Users/wimz/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:3078:933
    at async t.RawDebugSession.shutdown (file:///C:/Users/wimz/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:3077:1)
​```

**Comment by SounD120** [comment]
Hi @wimZ , thanks for the report. We tried to reproduce this on the latest version of VS Code Insiders, and we had no problems. Could you please try update your insider build to the latest and start debugging again? It seems that there could be a regression that has already been fixed.
```
Version: 1.46.0-insider (user setup)
Commit: 876f2e70f9a2e1988887f8ca82294418afac15a2
Date: 2020-05-27T05:43:41.115Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363
```

**Comment by wimZ** [comment]
Thanks for your fast response.  
. 
I updated to the latest version, but the problem still exists

**I noticed this after startup in the developer console**:

abstractExtensionService.ts:396 Activating extension 'msjsdiag.cordova-tools' failed: Cannot find module 'q'
Require stack:
- c:\Users\wimz\.vscode-insiders\extensions\msjsdiag.cordova-tools-1.9.4\out\src\utils\cordovaProjectHelper.js
- c:\Users\wimz\.vscode-insiders\extensions\msjsdiag.cordova-tools-1.9.4\out\src\cordova.js
- c:\Users\wimz\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\loader.js
- c:\Users\wimz\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\bootstrap-amd.js
- c:\Users\wimz\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\bootstrap-fork.js.


**Current version:**
Version: 1.46.0-insider (user setup)
Commit: 876f2e70f9a2e1988887f8ca82294418afac15a2
Date: 2020-05-27T05:43:41.115Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by RedMickey** [comment]
Hi @wimZ, it could be that some errors occurred during the extension installation. Could you please try to reinstall the extension? Please, don't forget to close and reopen VS Code after the extension installation.
Please let us know about your results.

**Comment by wimZ** [comment]
Reinstalled of Cordova tools.
Works!

Thanks for your support
