### ISSUE TITLE
[Run Browser] How to prevent localhost:8000/simulator/index.html window from opening?

### ISSUE THREAD

**Issue by cagross** [microsoft/vscode-cordova#631]
Hello.  I have been using your extension, and everything works great so far--thank you very much.  I have one question though.  In the VSCode 'Run' dropdown list, I've selected 'Run Browser' ([screenshot](https://i.imgur.com/awzqgt4.jpg)).  When I then run, a browser window (Chrome in my case) opens to `http://localhost:8000/index.html` and runs my app inside, as desired and expected.  But additionally, a second browser window opens to `http://localhost:8000/simulator/index.html`, which seems to give additional diagnostic info, geolocation info, allows me to test events (e.g. back button) etc ([screenshot](https://i.imgur.com/ZxBFWLc.jpg)).  Is there any way to ensure this second window does not open? For now I don't need it, and I have to manually close it every time.

Sorry if this is listed in the documentation anywhere, or in a previous issue.  I had a quick look, but couldn't see anything.

Thanks.

## Actual Behavior
1.  
2.

## Expected Behavior
1.
2.

## Software versions
- Cordova VS Code extension version:  1.9.4
- VSCode version: 1.45
- OS platform and version: Windows 10
- NodeJS version:  13.13
- Cordova version:  9.0.0
- Cordova-Android/iOS/Windows version:  Unsure

## Outputs (Include if relevant)
- Output of the Debug Console (View -> Toggle Debug Console):
```
PASTE OUTPUT HERE
```
- Output of the Cordova output channel (View -> Toggle Output -> Select Cordova in ListBox):
```
PASTE OUTPUT HERE
```
- Output of the Developer Tools console (Help -> Toggle Developer Tools -> Select Console tab):
```
PASTE OUTPUT HERE
```

**Comment by JiglioNero** [comment]
Hello @cagross , thank you for contacting us. This page simulates the native calls of Cordova, if it doesn’t opened, they don't fire some events in the simulated app and this may lead to errors, therefore it is not recommended to close it.

**Comment by cagross** [comment]
OK, that makes sense then.  I'll live with it for now.  Thanks!

We can consider this resolved.
