### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by ehmd96** [microsoft/vscode-cordova#632]
- Issue Type: `Performance`
- Extension Name: `cordova-tools`
- Extension Version: `1.9.4`
- OS Version: `Windows_NT x64 10.0.18362`
- VSCode version: `1.46.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\papso\msjsdiag.cordova-tools-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by SounD120** [comment]
@ehmd96 Duplicate #517
