### ISSUE TITLE
"Internal Server Error" reloading "index.html"

### ISSUE THREAD

**Issue by f4b10goncalves** [microsoft/vscode-cordova#652]
## Actual Behavior
I'm running my Cordova app on Chrome using "Simulate Android in browser" successfully. When I make any change in the "index.html" file and save it, browser shows "Internal Server Error" instead of running the app. 

This happens very often (~90% of the times), but not always. In order to run my app again, I have to close VS Code and start it again. 

When I make changes to other files like CSS or JS only (but not to "index.html"), the app usually reloads successfully.

I have noticed that ".\platforms\android\app\src\main\assets\www\index.html" file is locked when this error happens. Its impossible to delete this file. Even with admin privileges, I get "access denied". When I close VS Code, this file is automatically deleted.

### launch.json
```
{
            "name": "Simulate Android in browser",
            "type": "cordova",
            "request": "launch",
            "platform": "android",
            "target": "chrome",
            "simulatePort": 8000,
            "livereload": true,
            "sourceMaps": true,
            "cwd": "${workspaceFolder}"
        },
```

## Expected Behavior
I expect my app to reload successfully after I save "index.html".

## Software versions
- Cordova VS Code extension version: 1.9.5
- VSCode version: 1.48.0
- OS platform and version: Windows 10 Pro - 10.0.18363
- NodeJS version: 10.16.0
- Cordova version: 9.0.0
- Cordova-Android version: 8.1.0

VS Code info:

> Version: 1.48.0 (system setup)
> Commit: db40434f562994116e5b21c24015a2e40b2504e6
> Date: 2020-08-13T07:50:42.600Z
> Electron: 7.3.2
> Chrome: 78.0.3904.130
> Node.js: 12.8.1
> V8: 7.8.279.23-electron.0
> OS: Windows_NT x64 10.0.18363
> 

## Outputs
- Output of the Debug Console:
```
Failed to load resource: the server responded with a status of 500 (Internal Server Error) [http://localhost:8000/index.html]
```
- Output of the Developer Tools console (Help -> Toggle Developer Tools -> Select Console tab):
```
console.ts:137 [Extension Host] SIM: Creating app-host.js: Existing file found and is up-to-date.
console.ts:137 [Extension Host] SIM: Injecting app-host into c:\Projetos\Agenda\Agenda\platforms\android\app\src\main\assets\www\index.html
console.ts:137 [Extension Host] 500 /index.html
console.ts:137 [Extension Host] SIM: APP_HOST disconnected from the server
```

**Comment by SounD120** [comment]
Hi @f4b10goncalves , thanks for reaching us. I just tried to reproduce this on a freshly created Cordova 9 application. I started `Simulate Android in browser` scenario and then changed `index.html` file about 50 times and I never faced such an error. Could you please provide us a minimal demo application on which this error is reproduces for you?

**Comment by f4b10goncalves** [comment]
Hello @SounD120 ... Thank you for the reply.

I have made a lot of tests today trying to isolate the problem. Finally I've got the minimal demo that reproduces this error.

It looks like the problem is related to the **"index.html" file size**. When this file gets too big, I start getting the "internal server error". If I cut out some code, the error disapears.

Please download the mininal demo project:
[hello.zip](https://tabadigital.com/download/hello.zip)

This project is Cordova's "Hello World", in which I have just replaced "index.html" and "index.js".

On "index.js" there is only a `console.log('deviceready')`. I have noticed that "deviceready" event is fired twice. I don't understand why, and I don't know whether its relevant or not.

The steps to reproduce the error are:

- Run the app with "Simulate Android in browser".
- Make any change in "index.html".
- Save "index.html".

Please let me know if you manage to reproduce the "internal server error" running my demo project.

**Comment by SounD120** [comment]
@f4b10goncalves I was able to reproduce that behavior. At first I tried to do changes and look for the results but that didn't led me to the error, but when I started to do live reloads very fast it might cause a breakage. We'll investigate that problem and let you know when it will be fixed.

**Comment by f4b10goncalves** [comment]
Hello! Any news here? 
If you have a workaround, please let me know. Meanwhile I need to close and open VS Code every time I change "index.html".
If a hotfix is available, you may send me to test it.
Thank you.

**Comment by RedMickey** [comment]
Hi @f4b10goncalves, we are sorry for the delay. We found out [the probable place and functions](https://github.com/microsoft/cordova-simulate/blob/master/src/server/live-reload/live-reload.js#L96-L102) that cause the bug. Now we are investigating how we can fix this problem.

**Comment by f4b10goncalves** [comment]
The branch published by @RedMickey on GitHub fixes this issue. Great, thank you!
I have notice that when I save "index.html", the app doesn't reload automatically, as it used to. But when I reload the app manually, I don't get "Internal Server Error" anymore.
Thank you @SounD120 and @RedMickey!
