### ISSUE TITLE
Breakpoints don't work while debugging Ionic 5 apps with livereloads on iOS 14

### ISSUE THREAD

**Issue by SounD120** [microsoft/vscode-cordova#677]
## Actual Behavior
1. Breakpoint don't work on iOS Ionic 5 apps with `ionicLiveReload` option enabled.

## Expected Behavior
1. Breakpoints work on iOS Ionic 5 apps with `ionicLiveReload`.

## Software versions
- Cordova VS Code extension version: 2.0.0
- VSCode version: 1.50.0
- OS platform and version: macOS 10.15.7
- NodeJS version: 12
- Cordova version: 10
- Cordova-Android/iOS/Windows version: iOS 6.0.0

**Comment by RedMickey** [comment]
Fixed in https://github.com/microsoft/vscode-cordova/pull/679
