### ISSUE TITLE
Android Debug not attaching

### ISSUE THREAD

**Issue by MKHSKY** [microsoft/vscode-cordova#680]
## Actual Behavior
1. App compiles
2. App starts on android Device (via Wi-Fi)
3. Attaching to app..
4. Timeout while connecting

## Expected Behavior
Obviously attach to the app (Like in Version 1.9.5, works there)

## Software versions
- Cordova VS Code extension version: 2.0.0
- VSCode version: 1.50.1
- OS platform and version: Linux / Docker Container https://github.com/Fluxter/docker-vscode-cordova
- NodeJS version: v10.19.0
- Cordova version: 8.1.1 (cordova-lib@8.1.0)
- Cordova-Android/iOS/Windows version:

## Outputs (Include if relevant)
- Output of the Debug Console (View -> Toggle Debug Console):
```
PASTE OUTPUT HERE
```
- Output of the Cordova output channel (View -> Toggle Output -> Select Cordova in ListBox):
```
PASTE OUTPUT HERE
```
- Output of the Developer Tools console (Help -> Toggle Developer Tools -> Select Console tab):
```
PASTE OUTPUT HERE
```

If the outputs are needed, i can add them later.
There is a message like "GET CANCELLED http://localhost:<Random Port>/json/version

**Comment by RedMickey** [comment]
Hi @MKHSKY and thanks for reaching us. We investigated the issue and found out the problem. [This PR](https://github.com/microsoft/vscode-cordova/pull/682) is intended to fix the issue. Could you please try to install patched extension VSIX with a fix and let us know how it works for you? To try it please do the following:
* Download and unzip compiled extension VSIX : [cordova-tools-2.0.0.vsix.zip](https://github.com/microsoft/vscode-cordova/files/5401832/cordova-tools-2.0.0.vsix.zip)
* Uninstall the extension in a dev container
* Close VS Code and reopen VS Code
* Open the dev container and install from VSIX:
    * Click `Extensions`
    * Click `...`
    * Click `Install from VSIX...`
    * Click `Show Local` 
    * Select the VSIX file
* Reload VS Code

**Comment by RedMickey** [comment]
Hi @MKHSKY, the problem was fixed in the https://github.com/microsoft/vscode-cordova/pull/682 PR. The fix will be available in the next version of the extension.
