### ISSUE TITLE
Support of Windows platform

### ISSUE THREAD

**Issue by FabriceFR** [microsoft/vscode-cordova#692]
## Actual Behavior
In the tip and specifications for the launch.json plaform attribute completion is indicated : "Only 'iOS' and 'Android', other platforms are currently not supported"

## Expected Behavior
Is it planned / possible to get back 'windows' platform support to ensure the cross platform support?

## Software versions
- Cordova VS Code extension version:
- VSCode version: 1.51.1
- OS platform and version: Windows 10 19042.630
- NodeJS version: 12.14.1
- Cordova version: 10.0.0
- Cordova-Android/iOS/Windows version: 9.0.0/ ? /4.4.2

Thanks for your feedback
Fabrice.

**Comment by SounD120** [comment]
Hi @FabriceFR and thanks for your question. Right now Cordova for Windows apps can be debugged by only the VS 2017, and under the hood they use the deprecated EdgeHTML engine backend. EdgeHTML Edge [support will end on March 9 2021](https://techcommunity.microsoft.com/t5/microsoft-365-blog/microsoft-365-apps-say-farewell-to-internet-explorer-11-and/ba-p/1591666). Currently the VS 2019 and the most recent versions of JS debuggers in VS Code doesn't support [EdgeHTML debugging](https://github.com/apache/cordova-windows/issues/327) as they tuned to debug webview working on [Chrome DevTools Protocol](https://chromedevtools.github.io/devtools-protocol/). So we may add such support when Cordova for Windows will start to use Chrome-based webview as rendering backend.
