### ISSUE TITLE
GET_RUN_ARGUMENTSError

### ISSUE THREAD

**Issue by huangfeihong1860** [microsoft/vscode-cordova#694]
## Actual Behavior
I used the cordova tools in vscode to debug web project, I run the comand (run android on emulator )
but get a message,can you help me!
An error occurred while handling message: `GET_RUN_ARGUMENTSError: connect ENOENT \?\pipe\vscodecordova`
```json
{
"name": "Simulate Android in browser",
"type": "cordova",
"request": "launch",
"platform": "android",
"target": "chrome",
"simulatePort": 8000,
"livereload": true,
"sourceMaps": true,
"cwd": "${workspaceFolder}"
}
```
## Expected Behavior
1. the web page is run  in chrome by Android in browser mode

## Software versions
- Cordova tools:1.8.6
- VSCode version:1.19.3
- OS platform and version: win10
- NodeJS version:6.5.0
- Cordova version: 9.0.1

## Outputs (Include if relevant)

An error occurred while handling message: `GET_RUN_ARGUMENTSError: connect ENOENT \?\pipe\vscodecordova`

**Comment by SounD120** [comment]
Hi @huangfeihong1860 and thanks for reaching us. Could you please describe your problem in a way pointed in our [issue template](https://github.com/microsoft/vscode-cordova/blob/master/.github/ISSUE_TEMPLATE.md)? This will help us to find out what is happening in your specific case much faster. Thank you.

**Comment by SounD120** [comment]
@huangfeihong1860 Your software configuration looks deprecated and not supported at the moment. Could you please update Node.js up to version 10, Cordova Tools and VS Code up to latest versions and let us know if this resolved problems for you?

**Comment by huangfeihong1860** [comment]
Hi sound120，
I resolved the problems，because of  only  up VS Code to latest version1.51.1，thank you very much

**Comment by SounD120** [comment]
@huangfeihong1860 Glad to hear that. Can I close the issue?

**Comment by SounD120** [comment]
@huangfeihong1860 It seems that the issue has been resolved, so I am closing this issue.
