### ISSUE TITLE
Cordova Client + Node Server debugging ->Debugger is mixed up

### ISSUE THREAD

**Issue by bonjourjoel** [microsoft/vscode-cordova#706]
Hi,

I am reporting a very anoying bug in vscode's debugger while using "Cordova Tools" extension, which makes it difficult to debug a server/client configuration.

I run/debug a node.js server opening a server websocket. Then i run/debug a cordova client connecting to the server with a websocket of its own. When i close Chrome's window, the server process crashes with exit(1) and no other explanation, while the client process hangs forever untill I kill it.

I have searched what was happening because I'm new to these technologies and I have found out it was a bug in vscode's debugger/Cordova Tools and not in my code. I attach with this bug report a minimal reproducer project which contains all the code needed to fix. I have added a detailed step-by-step procedure to create the project and reproduce the bug, as well as a screenshot showcasing the reproducable issues.
Because I have tried to fix it myself in my code, I have found a few hints that I send you with the bug report in case you could use them to make a fix.

One more thing: I have previously submited this bug report to https://github.com/microsoft/vscode-js-debug/issues/935 and connor4312 told me that it was a cordova issue that I should submit here. I have made a second test with a normal html page and javascript, and the issue isn't reproduced (even if cordova extension is still enabled). So i guess connor4312 is right and this is indeed a cordova extension "Cordova Tools" issue.

Best regards.

===============================================================

$> cordova create hello com.example.hello HelloWorld
$> cd hello
$> cordova platform add browser
$> npm init
- type enter, enter, enter, enter

$> code .
- Menu File > New File with the following content:
    setInterval(()=>{console.log(new Date().toLocaleTimeString() + " server is alive")}, 2000);  
- Then save this new file as "server.ts" in the worskspace directory "hello"
- Install vscode extension "Cordova Tools"
- Open the RUN AND DEBUG panel; create 2 launch configurations like this:
    {
        // Use IntelliSense to learn about possible attributes.
        // Hover to view descriptions of existing attributes.
        // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
        "version": "0.2.0",
        "configurations": [
            {
                "name": "SERVER - Launch Program",
                "type": "pwa-node",
                "request": "launch",
                "skipFiles": [
                    "<node_internals>/**"
                ],
                "program": "${workspaceFolder}//server.ts",
                "outFiles": [
                    "${workspaceFolder}/**/*.js"
                ]
            },
            {
                "name": "CLIENT - Run Browser",
                "type": "cordova",
                "request": "launch",
                "platform": "browser",
                "target": "chrome",
                "simulatePort": 8000,
                "livereload": true,
                "cwd": "${workspaceFolder}",
                "sourceMaps": true
            },
        ]
    }
- Run "SERVER - Launch Program" by clicking the green arrow
- Run "CLIENT - Run Browser" by clicking the green arrow
- When both are running, close the window of Chrome

Result of this procedure:
===> SERVER process stops with exit code 1 (and nothing else is explained)
===> CLIENT process hangs until force-closed

What I would expect instead:
===> SERVER process hangs until force-closed
===> CLIENT process stops with exit code 0

Before I found out it was a vscode bug, I searched what was wrong, so there are a few fixing hints I can give you:
- If I close the server process first, the client process doesn't hang.
- If I open a new Tab on chrome, and I close the first one opened by codova ext, the server doesn't exit(1)
- If I run the server in the console, and the client using the debug view, i get the expected result: server process stays alive, client process is ended

===============================================================

[hello.zip](https://github.com/microsoft/vscode-cordova/files/6093974/hello.zip)
[reproduce-me.txt](https://github.com/microsoft/vscode-cordova/files/6093977/reproduce-me.txt)
![reproduce-me](https://user-images.githubusercontent.com/78134277/110182732-abfb9b80-7e0d-11eb-8a06-7eea7f06a6d4.png)

**Comment by etatanova** [comment]
Hi @bonjourjoel, thanks for reaching us. We've investigated this issue and opened the [PR](https://github.com/microsoft/vscode-cordova/pull/709) with a fix. Could you please check if this fix works for you?

You can install the extension with this fix by following these steps:
1. Download and unzip compiled extension [VSIX](https://github.com/microsoft/vscode-cordova/files/6171471/cordova-tools-2.2.0.vsix.zip)
2. Uninstall the extension
3. Reopen VS Code
4. Click Extensions -> Views and More Actions... -> Install from VSIX... And select the downloaded VSIX

Feel free to ask if you have any questions.

**Comment by bonjourjoel** [comment]
Hi @etatanova,
Thanks for your message.
I have done as you said and I can tell you this:

1) when i installed the extension and started my websocket server, i had the following message in "Output > Cordova" : "cordova-simulate dependency not present. Installing it...
......"
2) It works whatever you fixed and now I can work normally.
3) During the quick test I did, one thing didn't work perfectly but it's not a big deal for me. Maybe you will want to investigate it though, depending on your current priorities, because it could hide something worth knowing: In one of the tests, I started the server, then one android client, then one chrome client. And then i closed the android client: The server didn't crash but the client process was hanging in the debug call stack view. Finally I closed the chrome client and it hanged too. I had to disconnect them manually, both of them, but the server didn't crash.

One more thing, please could you tell me what I should do with my extension setup? Because when there will be an update, will my vscode update even if i have installed from a local VSIX file? Or do I have to do a procedure or something? Maybe it's explained in a link somewhere?

Thanks for the good work and best regards.

**Comment by etatanova** [comment]
Hi @bonjourjoel, thanks for your help.

> when i installed the extension and started my websocket server, i had the following message in "Output > Cordova" : "cordova-simulate dependency not present. Installing it...

[Cordova-Simulate](https://github.com/microsoft/cordova-simulate) package is used in the extension to run and simulate Cordova applications in the browser. The package is installed automatically when `Simulate in browser` or `Run Browser` debugging scenario is launched for the first time. [The message in the output shows the downloading](https://github.com/microsoft/vscode-cordova/blob/master/src/extension/simulate.ts#L132-L147) of cordova-simulate package.

> In one of the tests, I started the server, then one android client, then one chrome client. And then i closed the android client: The server didn't crash but the client process was hanging in the debug call stack view. Finally I closed the chrome client and it hanged too. I had to disconnect them manually, both of them, but the server didn't crash.

We tried to reproduce this case with closing client processes (Android emulator, Chrome) and with a debugging session hanging in a call stack and came to the conclusion that this is the expected behavior at the moment.

> One more thing, please could you tell me what I should do with my extension setup? Because when there will be an update, will my vscode update even if i have installed from a local VSIX file? Or do I have to do a procedure or something? Maybe it's explained in a link somewhere?

There is no need to do anything with the extension setup. When a new version of extension is released, there will be the button ‘Update to 2.x.x’ in the `EXTENSIONS` panel:

![image](https://user-images.githubusercontent.com/77284023/112018861-fbe19e80-8b3f-11eb-90c9-dae6b6d76651.png)

Also you can [configure](https://code.visualstudio.com/docs/editor/extension-gallery#_extension-autoupdate) extension auto-update.

**Comment by bonjourjoel** [comment]
Ok great thanks a lot!
