### ISSUE TITLE
Why is -UseModernBuildSystem=0 added by default (fixed)?

### ISSUE THREAD

**Issue by ChristianKuhn** [microsoft/vscode-cordova#708]
Hi!
My Cordova app does not build, when -UseModernBuildSystem=0 is set. Building/running from command line without this flag works.
Is there a reason, why this build flag is fixed in the plugin? This way it cannot be overriden, even when adding -UseModernBuildSystem=1 manually using runArguments.
https://github.com/microsoft/vscode-cordova/blob/860b1d787d0c6957abc61db3596443e30deaa168/src/debugger/cordovaDebugSession.ts#L615

Thanks, in advance.

**Comment by etatanova** [comment]
Hi @ChristianKuhn, thanks for reaching us. We've investigated this issue and opened the [PR](https://github.com/microsoft/vscode-cordova/pull/710) with a fix. Could you please check if this fix works for you?

You can install the extension with this fix by following these steps:

1. Download and unzip compiled extension [VSIX](https://github.com/microsoft/vscode-cordova/files/6212802/cordova-tools-2.2.0.vsix.zip)
2. Uninstall the extension
3. Reopen VS Code
4. Click Extensions -> Views and More Actions... -> Install from VSIX... And select the downloaded VSIX

Feel free to ask if you have any questions.

**Comment by etatanova** [comment]
Hi @ChristianKuhn, do you have a chance to look at this?

**Comment by ChristianKuhn** [comment]
> Hi @ChristianKuhn, do you have a chance to look at this?

Hi! Sorry but I haven't had time to work on this project. But I will get to this either today or tomorrow.

**Comment by etatanova** [comment]
Hi @ChristianKuhn, do you have any updates?

**Comment by etatanova** [comment]
Hi @ChristianKuhn, we are closing this issue since it's fixed. Changes will be available in the nearest release of Cordova Tools extension.
