### ISSUE TITLE
Having issues while trying to debug android device

### ISSUE THREAD

**Issue by Franco-Alejandro** [microsoft/vscode-cordova#744]
## Actual Behavior
1. Tried to debug my Cordova-Angular project on an android device and placed a breakpoint
2. Breakpoint is greyed out
3. A breakpoint hits on the native js code generated, and not the actual typescript code i have

## Expected Behavior
1. Place a breakpoint after running "Run Android on device"
2. Breakpoint should hit on the ts code

## Software versions
- Cordova VS Code extension version: 2.3.0
- VSCode version: 1.61
- OS platform and version: Windows 10, 10.0.19041
- NodeJS version: 12.18.0 
- Cordova version: 10.0.0 (cordova-lib@10.1.0)
- Cordova-Android/iOS/Windows version: 10.1.1

## Outputs 
- Output of the Debug Console (View -> Toggle Debug Console):
```
Channel not fired: onPluginsReady localhost/cordova.js:1230
Could not read source map for https://localhost/main-es2015.js: Unexpected 503 response from https://localhost/main-es2015.js.map: connect ECONNREFUSED 127.0.0.1:443
Ionic Native: deviceready did not fire within 5000ms. This can happen when plugins are in an inconsistent state. Try removing plugins from plugins/ and reinstalling them. localhost/vendor-es2015.js:191000
Angular is running in the development mode. Call enableProdMode() to enable the production mode. localhost/vendor-es2015.js:101406
WARNING: Processing source-maps of https://localhost/2-es2015.js took longer than 5656.9414 ms so we continued execution without waiting for all the breakpoints for the script to be set.Could not read source map for https://localhost/2-es2015.js: Unexpected 503 response from https://localhost/2-es2015.js.map: connect ECONNREFUSED 127.0.0.1:443
WARNING: Processing source-maps of https://localhost/default~chat-chat-module~home-home-module~offers-offers-module~profile-profile-module~taskDetails-ta~e533450e-es2015.js took longer than 990.6151 ms so we continued execution without waiting for all the breakpoints for the script to be set.WARNING: Processing source-maps of https://localhost/common-es2015.js took longer than 989.0862999999999 ms so we continued execution without waiting for all the breakpoints for the script to be set.WARNING: Processing source-maps of https://localhost/17-es2015.js took longer than 989.0862999999999 ms so we continued execution without waiting for all the breakpoints for the script to be set.
```

NOTE: Hey so, a bit of context here, I used to use an older version of this extension that worked just fine. I wanted to update the version to use the latest but started having these issues even after I updated every dependency to its latest.

I apologize if this doesn't belong on the issues tab, I just don't know if anyone else has had this problem and I didn't know where to ask. 

Thanks in advance, have a good week!

**Comment by RedMickey** [comment]
Hi @Franco-Alejandro and thanks for reaching us. We've investigated the issue and proposed the fix for it in the [PR](https://github.com/microsoft/vscode-cordova/pull/741). Could you please check if this fix works for you by following these steps?

- Download and unzip compiled extension [VSIX](https://github.com/microsoft/vscode-cordova/files/7453712/cordova-tools-2.3.0.vsix.zip)
- Uninstall the extension
- Close VS Code
- Open VS Code
- Click `Extensions -> ... -> Install from VSIX...` and select downloaded VSIX

Please let us know about your results.

**Comment by Franco-Alejandro** [comment]
Okay! I'll try it in a few hours and get back to you, thanks!!!!

**Comment by Franco-Alejandro** [comment]
okay so, breakpoints are NOT hitting the js code, which is nice and fixes my issue... but they are greyed out when placing them so each time i place a breakpoint i need to restart the debugger

**Comment by RedMickey** [comment]
@Franco-Alejandro We improved debugger behavior in this [VSIX](https://github.com/microsoft/vscode-cordova/files/7468388/cordova-tools-2.3.0.vsix.zip). Could you please try it out?
If the problem with breakpoints remains, could you please create and send us a minimal demo project with this problem? It will help us to reproduce the problem and investigate it faster. Thanks.

**Comment by Franco-Alejandro** [comment]
On it

**Comment by Franco-Alejandro** [comment]
The latest VSIX you sent is working amazingly on my device. It for sure works better than before and it has made my life easier.

**Comment by RedMickey** [comment]
@Franco-Alejandro Glad to hear that and thanks for your assistance! Then I'm closing this issue. We'll release a new version of the extension with this fix soon.
