### ISSUE TITLE
Google Chrome not found on WSL / Windows 11

### ISSUE THREAD

**Issue by jhubsharp** [microsoft/vscode-cordova#747]
## Actual Behavior
1. Simulating Android in the browser fails to find Google Chrome

## Expected Behavior
1. The browser starts and routes to the application

## Software versions
- Cordova VS Code extension version: 2.4.0
- VSCode version: 1.62.2
- OS platform and version: Windows 11 running WSL2 Ubuntu 20.04
- NodeJS version: v12.22.7
- Cordova version: 10.0.0

## Outputs (Include if relevant)
- Output of the Debug Console (View -> Toggle Debug Console):
```
Error executing "google-chrome --user-data-dir=/tmp/temp_chrome_user_data_dir_for_cordova http://localhost:8000/simulator/index.html": /bin/sh: 1: google-chrome: not found
```
I'm sure this is a step in the configuration I'm missing, but I haven't been able to get this to run from inside WSL. I set up an alias in .bashrc to hit chrome on Windows and it works fine using that alias from WSL bash. I just want to get it to work from the debugger in VSCode.

**Comment by RedMickey** [comment]
Hi @jhubsharp and thanks for reaching us. Could you please tell us if you're using [VS Code Remote Development](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.vscode-remote-extensionpack) and [Remote - Containers](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-containers) extensions to develop your Cordova app in Linux environment on Windows?

**Comment by jhubsharp** [comment]
I have Remote WSL and Remote Containers installed.

**Comment by RedMickey** [comment]
@jhubsharp we investigated the issue and found out that the current version of the extension doesn't support development (apps simulating) in Docker containers or via WSL. The extension and the external package for simulating Cordova apps in the browser require some modifications to work correctly in containers. We have added the issue to our backlog and will pick it up in order of priorities.

**Comment by EzioLi01** [comment]
Debugger should work fine on Win11, for remote dev, this extension is not support so far. We will investigate on dependent package firstly in the future. Close this issue so far as not plan.
