### ISSUE TITLE
Use Brave browser instead of Chrome, when simulating Android in the browser?

### ISSUE THREAD

**Issue by ajck** [microsoft/vscode-cordova#755]
Is it possible to somehow have the Brave browser as the target for browser simulation of Android, rather than Chrome? Reason being that Brave is lighter weight and I already have it open for many things, so would prefer to open it in that rather than also load Chrome (my PC is resource limited). Thanks.

I opened launch.json and changed
` "target": "chrome",`
to
`"target": "brave",`
but got this output in the debug console when trying to start debugging:
```
Launching for android (This may take a while)...
Could not recognize type of the target brave
Continue using standard CLI workflow.
Command failed: adb devices
'adb' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by RedMickey** [comment]
Hi @ajck and thanks for your feedback, currently the extension doesn't support the Brave browser. We'll consider adding support for it and manage in order of priorities.

**Comment by EzioLi01** [comment]
Checked in [Apache Cordova Serve](https://github.com/apache/cordova-serve), the brave browser or chromiun browser is not in support list. We need to push some updates for the new support for cordova-serve firstly.

**Comment by EzioLi01** [comment]
No further updates from cordova-serve owner to add other chromium browsers. Will close this issue for now, and if we can start to work on this, will create new issue for it.
