### ISSUE TITLE
Launch cordova -> Uncaught exceptions is auto-unchecked

### ISSUE THREAD

**Issue by bonjourjoel** [microsoft/vscode-cordova#765]
## Actual Behavior
1. In vscode, in the "Run and debug" / "Breakpoints" panel, I have "Uncaught exceptions" == checked.
2. When I run anything with cordova tools, it gets automatically unchecked.
3. Then I re-check it manually.

This is clearly non-blocking. It could even be a feature that I fail to understand. But as far as I'm concerned, it's quite annoying, and i may have re-checked this box one hundred thousand times in the past year.

## Expected Behavior
1. Not change the checked-status of "Uncaught exceptions" upon cordova-tools launch?

## Software versions
- Cordova VS Code extension version: 2.4.1
- VSCode version: 1.66.0
- OS platform and version: Windows 10 Home
- NodeJS version: v17.1.0
- Cordova version: 11.0.0
- Cordova-Android/iOS/Windows version:
Installed platforms:
  android 10.1.1
  browser 6.0.0
  ios 6.2.0

## Please see attached screenshots
![cordova_tools_uncaught_exception_1](https://user-images.githubusercontent.com/78134277/163702371-537f15cd-6194-4656-8f55-71d430970c2a.png)
![cordova_tools_uncaught_exception_2](https://user-images.githubusercontent.com/78134277/163702377-2948e9b2-b945-4a58-a354-3bd99ab28ad6.png)

**Comment by JiglioNero** [comment]
Hi @bonjourjoel  and we're sorry for the long response. We have fixed this error and created a test VSIX. You can install it by following these steps:

1. Download and unzip compiled extension [VSIX](https://github.com/microsoft/vscode-cordova/files/8581804/cordova-tools-2.4.1.vsix.zip)
2. Uninstall the extension
3. Close VS Code
4. Open VS Code
5. Click Extensions -> ... -> Install from VSIX... and select downloaded VSIX

Could you please test this VSIX?

**Comment by bonjourjoel** [comment]
Thanks a lot! It works. You just saved another 100.000 x 2 seconds of my life!

**Comment by JiglioNero** [comment]
LoL, you are welcome ;D. These changes will appear in the next version of Cordova Tools

**Comment by EzioLi01** [comment]
Will investigate on this.

**Comment by EzioLi01** [comment]
Hey @bonjourjoel , I have tried on cordova-tools 2.6.1, VSCode 1.74.2, Win11, it works well on my side. I will keep investigating on this.
![image1](https://user-images.githubusercontent.com/19662219/210934208-d5d0b8cf-6a69-4631-ab2f-f5c74829dc4d.gif)

**Comment by EzioLi01** [comment]
We have some changes on debug session on 2022, maybe it caused by this change. Will find workaround on it.

**Comment by EzioLi01** [comment]
Create enhancement issue [#1901 ](https://github.com/microsoft/vscode-react-native/issues/1901)for this, will implement it by working plan.
