### ISSUE TITLE
Launch cordova browser chrome after hard stop -> Chrome did not shut down correctly

### ISSUE THREAD

**Issue by bonjourjoel** [microsoft/vscode-cordova#766]
## Actual Behavior
1. During a browser/chrome debug session, i stop the program using vscode interface instead of closing the chrome window.
2. Next time i run the same debug configuration, i get a boring popup in chrome: "Chrome did not shut down correctly".
3. I have to dismiss it everytime. And I always do.

Like my previous issue, this is non-blocking. But it's annoying, and I have to repeat the same click over and over, and it seems a waste of my energy because it's always the same action i'm performing, and a few lines of code might do it automatically. Though I don't know if chrome would allow you do that.

## Expected Behavior
1. Get rid of that annoying prompt if possible?

## Software versions
- Cordova VS Code extension version: 2.4.1
- VSCode version: 1.66.0
- OS platform and version: Windows 10 Home
- NodeJS version: v17.1.0
- Cordova version: 11.0.0
- Cordova-Android/iOS/Windows version:
Installed platforms:
  android 10.1.1
  browser 6.0.0
  ios 6.2.0

## Please see attached screenshot
![cordova_tools_chrome_did_not_blabla](https://user-images.githubusercontent.com/78134277/163702873-61bac913-a6c5-4fb7-8a93-9274a94702f7.png)

**Comment by JiglioNero** [comment]
Hi @bonjourjoel and thanks for reaching us. We implemented a small workaround to this problem and created a test VSIX.
You can install it by following these steps:

1. Download and unzip compiled extension [VSIX](https://github.com/microsoft/vscode-cordova/files/8507026/cordova-tools-2.4.1.vsix.zip)
2. Uninstall the extension
3. Close VS Code
4. Open VS Code
5. Click Extensions -> ... -> Install from VSIX... and select downloaded VSIX

Could you please test this VSIX?

**Comment by bonjourjoel** [comment]
Hi @JiglioNero. The prompt is gone, indeed. It works fine. Thanks.

**Comment by JiglioNero** [comment]
Great, then these changes will appear in the next version of Cordova Tools
