### ISSUE TITLE
Unable to Debug on iOS Device

### ISSUE THREAD

**Issue by a51095** [microsoft/vscode-cordova#777]
- Node: 10.16.2
- nvm: 0.39.1
- Cordova: 9.0.0 (cordova-lib@9.0.1)
- Xcode: 13.4 (13F17a)
- Cordova Tools: 2.4.12022

```
        {
            "name": "Run iOS on device",
            "type": "cordova",
            "request": "launch",
            "platform": "ios",
            "target": "device",
            "port": 9220,
            "sourceMaps": true,
            "cwd": "${workspaceFolder}"
        }
```
`Run iOS on device` in VSCode, and the console reports the following error information
<img width="931" alt="error" src="https://user-images.githubusercontent.com/29021369/171555213-ac1afe9b-9849-43a4-b39e-7ef588e4ebc4.png">

Can you help me, thank you!

**Comment by JiglioNero** [comment]
Hi @a51095 and sorry for the long response. This error does not reproduce for me for a project created in the following way:

1. Create Cordova app with command `cordova create cordova_app`
2. Add iOS platform via command `cordova platform add ios`
3. Run following debug config:
```json
        {
            "name": "Run iOS on device",
            "type": "cordova",
            "request": "launch",
            "platform": "ios",
            "target": "device",
            "port": 9220,
            "sourceMaps": true,
            "cwd": "${workspaceFolder}"
        }
```
Could you please indicate what type of project you are using (Cordova/Ionic) and the steps to reproduce this error? It would also be great if you could provide us with a small demo project that reproduces this error.
P.S. It seems that your Node version is pretty old, you also can try it with newer one.

**Comment by a51095** [comment]
Hi, @JiglioNero
Think for review, This is a `Cordova` project, not ionic.
`cordova run ios --device --buildFlag=-UseModernBuildSystem=0 --no-update-notifier` and `Info.plist file not found`, Looks suspicious,  `Info.Plist` has been modified to `KapselLogin-Info.Plist`, so do I need to specify it again?
I think this error seems to be related to the `runArguments` key value pair. I only see that it should be an `array` type, but I don't know how to fill in the corresponding value of `runArguments`. Can you give me an example? Thank you!

**Comment by JiglioNero** [comment]
I'm not sure if this is related to `runArguments`, most likely a problem with connecting to your iOS device, because judging by the logs you provided, the app is trying to run on the simulator. This happens when there is no access to the connected device.

**Comment by AndreiLobanovich** [comment]
@a51095 did you have a chance to check?

**Comment by EzioLi01** [comment]
@a51095 Close inactive issue, please reopen and let me know if you still blocking by this issue.
