### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by BimaDitya** [microsoft/vscode-cordova#782]
- Issue Type: `Performance`
- Extension Name: `cordova-tools`
- Extension Version: `2.4.1`
- OS Version: `Windows_NT x64 10.0.19044`
- VS Code version: `1.71.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///c%3A/Users/IDEAPA~1/AppData/Local/Temp/msjsdiag.cordova-tools-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by EzioLi01** [comment]
@BimaDitya Thanks for reaching us, will investigate this and any found will update here.

**Comment by EzioLi01** [comment]
Hi @BimaDitya, I cannot get your profile file, could you please drag file to upload it directly?

**Comment by EzioLi01** [comment]
Hey @BimaDitya, could you please provide your profile file again? I cannot repro this from my side.

**Comment by EzioLi01** [comment]
Close this issue since customer have no further updates. Please reopen this or create a new one if you still need help. Thanks!
