### ISSUE TITLE
Typescript + Android simulator - breakpoints not binding outside of cordova directory

### ISSUE THREAD

**Issue by brunolau** [microsoft/vscode-cordova#807]
Maybe I'm just missing something, but when I reference a typescript file that is one level above my cordova project folder, I cannot bind a breakpoint to it. 

Is there a way to tell the debugger to also look one level up for the .ts file ?

**Comment by EzioLi01** [comment]
Hey @brunolau , now we're not supporting that, but we'd like to plan to add this in the future. Could you please share a sample to describe your request?

**Comment by toldo-app** [comment]
Hi, here it goes

[cdv-repro.zip](https://github.com/microsoft/vscode-cordova/files/9958597/cdv-repro.zip)

**Comment by brunolau** [comment]
Hi, here it goes

[cdv-repro.zip](https://github.com/microsoft/vscode-cordova/files/9958602/cdv-repro.zip)

**Comment by EzioLi01** [comment]
> Hi, here it goes
> 
> [cdv-repro.zip](https://github.com/microsoft/vscode-cordova/files/9958602/cdv-repro.zip)

Looking into this, maybe we can add some parameters in debugger setup to help user debug out of cordova root folder, investigating...

**Comment by brunolau** [comment]
Any news on this? Would help us tremendously

**Comment by EzioLi01** [comment]
> Any news on this? Would help us tremendously

Thanks for your patience. We have investigated on this, it needs to refactor a lot of core logic in extension. We will work on this based on your task plan, and any update will note here. Thank you!

**Comment by EzioLi01** [comment]
Hey @brunolau , could you please try on the latest version 2.6.4 and check if it's working? Thank you!

**Comment by brunolau** [comment]
@EzioLi01 I'm out of office now, will be back in approx 2 weeks, then I will give it a try. Thanks

**Comment by EzioLi01** [comment]
I will close this issue, please try it if you have a chance, any issue you can reopen this or create a new issue. Thanks!
