### ISSUE TITLE
Prevent some sourcemaps from loading

### ISSUE THREAD

**Issue by brunolau** [microsoft/vscode-cordova#810]
Anytime my app iframes an youtube video with js enabled I receive message like mentioned below causing the app to hang. Is there a way to omit specific source maps from loading ?

The message:
WARNING: Processing source-maps of 1904 took longer than 11000 ms so we continued execution without waiting for all the breakpoints for the script to be set.WARNING: Processing source-maps of 1906 took longer than 993.0357999999997 ms so we continued execution without waiting for all the breakpoints for the script to be set.WARNING: Processing source-maps of 2063 took longer than 986.9799999999997 ms so we continued execution without waiting for all the breakpoints for the script to be set.WARNING: Processing source-maps of 2065 took longer than 986.9799999999997 ms so we continued execution without waiting for all the breakpoints for the script to be set.WARNING: Processing source-maps of 2224 took longer than 986.9799999999997 ms so we continued execution without waiting for all the breakpoints for the script to be set.WARNING: Processing source-maps of 2226 took longer than 986.9799999999997 ms so we continued execution without waiting for all the breakpoints for the script to be set.WARNING: Processing source-maps of https://www.google.com/js/th/EWuoZ_9LU3hL76PT3YFLg_EjKJdTpZ6rgtgTJA98OBY.js took longer than 986.9799999999997 ms so we continued execution without waiting for all the breakpoints for the script to be set.WARNING: Processing source-maps of 2396 took longer than 986.9799999999997 ms so we continued execution without waiting for all the breakpoints for the script to be set.WARNING: Processing source-maps of https://www.google.com/js/th/EWuoZ_9LU3hL76PT3YFLg_EjKJdTpZ6rgtgTJA98OBY.js took longer than 986.3357999999997 ms so we continued execution without waiting for all the breakpoints for the script to be set.WARNING: Processing source-maps of 2399 took longer than 986.3357999999997 ms so we continued execution without waiting for all the breakpoints for the script to be set.WARNING: Processing source-maps of https://www.google.com/js/th/EWuoZ_9LU3hL76PT3YFLg_EjKJdTpZ6rgtgTJA98OBY.js took longer than 986.3357999999997 ms so we continued execution without waiting for all the breakpoints for the script to be set.WARNING: Processing source-maps of 2402 took longer than 986.3357999999997 ms so we continued execution without waiting for all the breakpoints for the script to be set.

**Comment by brunolau** [comment]
Or maybe to add - it would be sufficient if no sourcemaps from iframe were loaded

**Comment by EzioLi01** [comment]
Hey @brunolau , we had `sourceMaps` in config to disable it, but not support to ignore specific sourcemap, did you try this way in your application?

**Comment by EzioLi01** [comment]
Close this issue since it had no updates so far. Please reopen this issue or create new one if you still have any new updates. Thank you!
