### ISSUE TITLE
[Bug] Attach debugger will stuck at breakpoint on Chrome V111

### ISSUE THREAD

**Issue by brunolau** [microsoft/vscode-cordova#849]
Today the extension stopped working for me and my colleagues on our project. I am unable to determine the cause. It's stuck at loading

![image](https://user-images.githubusercontent.com/15102770/224680074-1035fe83-fde2-4952-bad0-280f68684d6b.png)

This is the "loaded scripts" section
![image](https://user-images.githubusercontent.com/15102770/224680176-d18ffef2-59a4-4764-b4a0-4469d693c082.png)

Once I hit the "stop" button, app gets loaded, but the breakpoints are ignored.
![image](https://user-images.githubusercontent.com/15102770/224680299-08aa49ec-fc8d-4c2b-a522-8fdabd9d07ba.png)

Is there a way I can diagnose what's the problem?

**Comment by EzioLi01** [comment]
Thanks @brunolau reporting this, extension have no release recently, should not cause by code changes. I will check chrome debugging on my local firstly, thank you!

**Comment by EzioLi01** [comment]
> Thanks @brunolau reporting this, extension have no release recently, should not cause by code changes. I will check chrome debugging on my local firstly, thank you!

I can repro this issue.

**Comment by EzioLi01** [comment]
@brunolau Seems it happened on Chrome latest release 111, not sure it's the bug or some policies changes, will try to find a workaround for this. Thank you!

**Comment by EzioLi01** [comment]
Update: will try to add arguments for chrome 111 to fix this issue. Seems it blocked by chrome origin allow policy.

**Comment by EzioLi01** [comment]
Hey @brunolau , the extension is depended on vscode-js-debug, this issue has been fixed on vscode-js-debug, but it should not release on prod so far, maybe you can use MS Edge for debugging until new release is coming. If you willing to use Chrome for debugging, I suggest you can use vscode-insiders or vscode-js-debug nightly version.
Please see: https://github.com/microsoft/vscode-js-debug/issues/1600

**Comment by EzioLi01** [comment]
Please try this to install `js-debug-nightly` in vscode, please let me know if this workaround is working for you.

1. Open the extensions view (ctrl+shift+x) and search for @builtin @id:ms-vscode.js-debug
2. Right click on the JavaScript Debugger extension and Disable it.
3. Search for @id:ms-vscode.js-debug-nightly in the extensions view.
4. Install that extension.

**Comment by brunolau** [comment]
Thank you, it works

**Comment by EzioLi01** [comment]
I will keep this issue opening for checking until the bug is fixed on js-debug prod version.

**Comment by EzioLi01** [comment]
Close this issue since the fixed version of js-debug is release, please update vscode to latest version to install js-debug built-in extension.
