### ISSUE TITLE
"env" variables not working any more

### ISSUE THREAD

**Issue by bonjourjoel** [microsoft/vscode-cordova#914]
Hi,
My launch.jsons contains several vscode-cordova launch configurations, and some of them use the "env" argument. It used to work, but now the "env" variable is ignored, and all env variables are undefined.
Did you guys remove this feature? Is it replaced by another? How to pass variables from launch.json to a cordova hook?

**Comment by benjaminbi** [comment]
Hello, thank you for the feedback. "env" is still supported. We have just given it a try and it works. Could you please share the details of your configuration so that we can try to repro from our end?

**Comment by bonjourjoel** [comment]
Hi, thanks for the quick answer, i will share this and also i have been running tests and i'll share these results because they are interesting.


This is my launch configuration using an environment variable:

>        { // configuration to connect to player22.com socket directly, to debug the real app's client
>            "name": "client-app: dbgrelease",
>            "type": "cordova",
>            "request": "launch",
>            "platform": "browser",
>            "target": "chrome",
>            "simulatePort": 8000,
>            "livereload": false,
>            "sourceMaps": true,
>            "cwd": "${workspaceFolder}",
>            "skipFiles": [
>                "<node_internals>/**",
>                "${workspaceFolder}/node_modules/**/*.js",
>                "${workspaceFolder}/app-src/shared/utils/ext-libs/**/*.js",
>            ],
>            "env":  {
>                "PREPARE_MODE": "CLIENT_DBGRELEASE",
>            },
>        },

This is how i read an environment variable in "Cordova hook BeforePrepare":

> const prepareMode : string = process.env.PREPARE_MODE;


Now something also interesting IMO, i have been testing reverting to several older versions of vscode-cordova, and these are my findings:

- cordova tools 2.5.0: env variables are processed
- cordova tools 2.6.0: for some reason, can't run cordova tools launch configuration after reverting to this version
- cordova tools 2.6.1 and above: env variables are not processed

**Conclusion:** In the version 2.6.0 or 2.6.1, some code was changed and as a result, env variables are not processed (at least in my project).

**Comment by benjaminbi** [comment]
Thank you for the details. There was a refactor of the code in 2.6.0. And that might be the reason. We will investigate and update.

**Comment by EzioLi01** [comment]
Hey @bonjourjoel , is it possible to share a small demo to repro this issue? It can help us to identify the core issue quickly, thank you!

**Comment by bonjourjoel** [comment]
Hi and thanks for the response. The issue is **not** resolved with this .vsix :

Although it seems to work based on the minimal reproducer, it does save the environment variable value somewhere, and then it's not able to change it, making it as useless as a constant in the CordovaHookBeforePrepare.js

Here is how to reproduce the new issue:

- Change the launch configurations for these 2, where I only changed the value of the env var:
>        {
>            "name": "Run Browser 1",
>            "type": "cordova",
>            "request": "launch",
>            "platform": "browser",
>            "target": "chrome",
>            "simulatePort": 8000,
>            "livereload": true,
>            "sourceMaps": true,
>            "cwd": "${workspaceFolder}",
>            "env": {
>                "ENV_VAR_TEST": "OK1",
>            },
>        },
>        {
>            "name": "Run Browser 2",
>            "type": "cordova",
>            "request": "launch",
>            "platform": "browser",
>            "target": "chrome",
>            "simulatePort": 8000,
>            "livereload": true,
>            "sourceMaps": true,
>            "cwd": "${workspaceFolder}",
>            "env": {
>                "ENV_VAR_TEST": "OK2",
>            },
>        },

- Run the first, and it outputs "OK1" in the log.
- Run the second, and it output "OK1" in the log instead of "OK2"

**Comment by EzioLi01** [comment]
Ops, my fault. Please try it again.

[cordova-tools-2.6.5(new).vsix.zip](https://github.com/microsoft/vscode-cordova/files/12427143/cordova-tools-2.6.5.new.vsix.zip)

**Comment by EzioLi01** [comment]
Cool @bonjourjoel , you can use this extension for the debugging, and we will fix this issue on next prod release version.
