### ISSUE TITLE
v2.6.6 can't launch browser

### ISSUE THREAD

**Issue by bonjourjoel** [microsoft/vscode-cordova#929]
Hi, it's me again.

## Actual Behavior
1. The extension is broken in update v2.6.6
2. This is a simple reproducer, which is the strict minimum one would expect from the extension:
- $> cordova create test
- $> cd test
- $> cordova platform add browser
- $> code .
- go to the debug tab, and add a launch.json, with Run Browser
- launch the app
- BUG --> It is not ready

## Expected Behavior
1. App ready

## Hint 1
The window with the remote controls is not opening, as it was before. Not that i need it, because it annoys me more than not. But it might be related to this issue.

## Hint 2
[vscode-debugadapter-7f366dbd.json.gz](https://github.com/microsoft/vscode-cordova/files/13278528/vscode-debugadapter-7f366dbd.json.gz)

## Impossible to downgrade
Also i want to add that i can't revert the update. I tried to downgrade the extension, but the bug remains. Once i have made the update, it's impossible to use the extension again, even with an older version. I have also tried to copy the old .vscode/simulate files from an archive before the update, but it doesn't work.

## Software versions
- Cordova VS Code extension version: 2.6.6
- VSCode version: 1.64.1
- OS platform and version: windows 10
- NodeJS version: v20.9.0
- Cordova version: 12.0.0 (cordova-lib@12.0.1)
- Cordova-Android/iOS/Windows version: n/A

## Outputs (Include if relevant)
- Output of the Debug Console (View -> Toggle Debug Console):
```
Launching for browser (This may take a while)...
Attaching to browser
Attaching to app
Could not read source map for file:///C:/.vscode/extensions/msjsdiag.cordova-tools-2.6.6/node_modules/cordova-simulate/src/third-party/jquery.min.js: ENOENT: no such file or directory, open 'c:\.vscode\extensions\msjsdiag.cordova-tools-2.6.6\node_modules\cordova-simulate\src\third-party\jquery.min.map'
deviceready has not fired after 5 seconds.
Channel not fired: onNativeReady
Channel not fired: onCordovaReady
Channel not fired: onCordovaSimulateReady
```

**Comment by seamlink-aalves** [comment]
I have the exact same problem with the latest version

**Comment by EzioLi01** [comment]
Thanks @bonjourjoel , @seamlink-aalves , it should related to some updates on cordova-simulate, will investigate on this with priority, any updates will comment here. Thanks!

**Comment by EzioLi01** [comment]
Update: The issue related to new run argument `showbrowser`, it not handle cordova-tools passed argument correctly. We will fix this issue on cordova-simulate and release new version soon. For the temporary workaround, please try below steps:
1. Install cordova-tools and run browser debug to install cordova-simulate
2. Navigate to `C:\Users\xxx\.vscode\extensions\msjsdiag.cordova-tools-2.6.6\node_modules\cordova-simulate\src\browsers\browser.js`
3. Add ` showBrowser = true;` at line 20, the new code should be
```
   let showBrowser = opts.showBrowser;
    showBrowser = true;
    if (!showBrowser) {
        return;
    }
```
4. Debug app

Please try this and let me know if this workaround is working. Thanks!

**Comment by bonjourjoel** [comment]
@EzioLi01 Thank you for your response
I have tested the workaround you proposed and I can tell you that it **does not work** correctly: It does make the app ready alright, but it sends the **event ready twice**, which is not correct.

**Comment by EzioLi01** [comment]
Thanks for the details, I have checked ready event active twice is also happened on previous version, so it should be the separate issue we need to investigate, I will create an new issue for it.

**Comment by EzioLi01** [comment]
> @EzioLi01 Thank you for your response I have tested the workaround you proposed and I can tell you that it **does not work** correctly: It does make the app ready alright, but it sends the **event ready twice**, which is not correct.

Thanks for the details, I have tried on my local, not it's not repro on my side. I think it should be the separate issue. I will investigate on this and try to repro it firstly. Will create a new issue to track it if it's need to fix. Thank you!

**Comment by bonjourjoel** [comment]
@EzioLi01 Ok, i understand. I will add a line in my code to ignore the second event.

Also i attach a trace of the double event bug. This is on the simple example with `cordova create test` / `cordova platform add browser`. My machine is windows 10 home Version 22H2 OsBuild 19045.3516 and i have the latest everything installed.

[vscode-debugadapter-ddb8f6bb.json.gz](https://github.com/microsoft/vscode-cordova/files/13303703/vscode-debugadapter-ddb8f6bb.json.gz)

**Comment by EzioLi01** [comment]
Thank you for the trace will keep an eye on this in the future.

**Comment by EzioLi01** [comment]
Update: I will start our release process for the cordova-simulate, it should be working fine in next week for cordova-simulate v1.2.2.

**Comment by EzioLi01** [comment]
Hey guys, cordova-simulate 1.2.2 is released, I have checked this issue is no longer existing. Please update your cordova-simulate version to 1.2.2 to fix it. Close this issue, please let me know if you're still facing this.
