### ISSUE TITLE
[Feature] Add Chromium as target for the simulate in browser options

### ISSUE THREAD

**Issue by DaanSchuitmaker** [microsoft/vscode-cordova#930]
Chromium is not allowed as a valid browser target. but since Chrome build 119 the websql functionality is removed.

To test and maintain older software i would like to spin up an older Chromium browser (with the WebSql support)

At this moment this is some how possible but not quite what you want.
You need to set that Chromium as default browser then when you're running simulate in browser the simulation part starts in chromium but the app starts in chrome.
Closing chrome and using the url in a new Chromium instance will work but it's a work around.

**Comment by EzioLi01** [comment]
Hey @DaanSchuitmaker , nice to see you again. I remember you have created a nice issue in cordova-simulate. Just want to confirm, do you need to add chromium to cordova-simulate? If so I will move this issue to repo https://github.com/microsoft/cordova-simulate. This is the repo for other project, it's different from cordova-simulate. Thanks!

**Comment by EzioLi01** [comment]
Hey @DaanSchuitmaker , could you please clarify on this?

**Comment by EzioLi01** [comment]
Move this issue into cordova-simulate. @DaanSchuitmaker Anything please navigate to simulate repo.
