### ISSUE TITLE
Simulate Browser Android not Working

### ISSUE THREAD

**Issue by nandarbin** [microsoft/vscode-cordova#934]
## Actual Behavior
1. 
![err](https://github.com/microsoft/vscode-cordova/assets/29623176/64e357d0-778e-430b-b030-66331064fbf7)
 browser not launcher where runing simulate browser android

2  
![image](https://github.com/microsoft/vscode-cordova/assets/29623176/f363ef45-b818-4547-92e4-481419d9949a)

## Expected Behavior
1.
2.

## Software versions
- Cordova VS Code extension version: 2.6.6
- VSCode version: 1.76.2
- OS platform and version: windows 10 64 Bit
- NodeJS version: 18.17.1
- Cordova version: 12.0.0
- Cordova-Android/iOS/Windows version: android 12.0.0

## Outputs (Include if relevant)
- Output of the Debug Console (View -> Toggle Debug Console):
`  not launcher browser    : Browser has been closed with exit code: 2147483651

PASTE OUTPUT HERE
``` Browser has been closed with exit code: 2147483651

- Output of the Cordova output channel (View -> Toggle Output -> Select Cordova in ListBox):
```
PASTE OUTPUT HERE
```
- Output of the Developer Tools console (Help -> Toggle Developer Tools -> Select Console tab):
```
PASTE OUTPUT HERE
```

**Comment by nandarbin** [comment]
error on vs code runtime 
![image](https://github.com/microsoft/vscode-cordova/assets/29623176/b6ea6be1-e2c7-4a2e-9de0-7a1b6ede3836)

**Comment by EzioLi01** [comment]
Hey @nandarbin , thanks for reaching us. I have tried on my local but no luck to repro this issue, could you please share a demo for this issue?
