### ISSUE TITLE
Cordova options not included in vs code debug

### ISSUE THREAD

**Issue by chitgoks** [microsoft/vscode-cordova#948]
## Actual Behavior
1. WHile the screenshots of this github page look different for vscode, my version has a run and debug button. when clicked, the cordova option is not included.

## Expected Behavior
1. Cordova should be seen in the debug list options

## Software versions
- Cordova VS Code extension version:
- VSCode version:Version: 1.86.1 (Universal)
- OS platform and version: MacOSX Sonoma 14.3.1
- NodeJS version:21.6.1
- Cordova version:12.0.0
- Cordova-Android/iOS/Windows version: ios 17.2

Cordova tools extension has already been installed.

**Comment by EzioLi01** [comment]
Hey @chitgoks, please using launch.json to add your cordova debug configure.

**Comment by chitgoks** [comment]
hi @EzioLi01  i thought once you choose cordova in the list, a launch.json is created for you. so you have to manually create launch.json? can you please include in the docs how to, after creating launch.json what to do next? can help newbies.

**Comment by EzioLi01** [comment]
Hey @chitgoks , after creating `launch.json` file, you can click `Add configuration` button and in the list you can see cordova debugging options. Normally I suggest that you can using Android emulator or browser for debugging. For iOS debugging, we used a 3rd party tool to setup debugging proxy, but it not support some latest iOS versions. So if you failed on iOS debugging in latest iOS version, you can replace it by browser debugging.
![image](https://github.com/microsoft/vscode-cordova/assets/19662219/2040db00-db5d-4c54-aa39-99d94e32c9c0)

**Comment by EzioLi01** [comment]
Hey @chitgoks , do you have any update or question on this?

**Comment by chitgoks** [comment]
hi @EzioLi01 ill get back to you. was away. will check next week.

**Comment by EzioLi01** [comment]
Cool, thanks!

**Comment by chitgoks** [comment]
@EzioLi01  hi. nothing comes out in the selection once the cursor is on the configurations array property. i already have the launch.json file.

**Comment by chitgoks** [comment]
@EzioLi01 thanks! it works. so it has to be manual now.

**Comment by EzioLi01** [comment]
@chitgoks If you're using the latest iOS I think it's some limitations in 3rd party ios proxy tools in our extension. Also cordova-ios also have some issues when launching simulator. If you're failed to work on simulator, I suggestion that you can try to use `Run Browser` to simulate and debug you app in browser.

**Comment by EzioLi01** [comment]
Sorry, I cannot repro this issue in my local, if you still want to dig it out, is it possible if you can share some demo to repro it?

**Comment by chitgoks** [comment]
can i email the project to you or  i post it here? its small. im just
trying to see how to package an angular app using cordova.

**Comment by EzioLi01** [comment]
Sounds good if you can add demo here.

**Comment by chitgoks** [comment]
[my-app.zip](https://github.com/microsoft/vscode-cordova/files/14338745/my-app.zip)
@EzioLi01  here it is. to summarize

my issue here in :
1) ios - when debugged, the console says variable cordova is undefined
2) android - when app is run, prompts err_connection_refused. in console, it says website not available.

thank you for entertaining this.

**Comment by EzioLi01** [comment]
@chitgoks One thing I want to confirm, can you run all scenarios successfully according to this tutorial without debugging?

**Comment by chitgoks** [comment]
both, no. without debugging in

ios - just a blank white screen
android - dialog prompt with message err_connection_refused.

**Comment by EzioLi01** [comment]
@chitgoks Actually I think it's not an extension issue. But I will still help to look into it. Any updates will comment here.

**Comment by chitgoks** [comment]
Hi @EzioLi01  yes. it is not an extension issue. thank you for wanting to help out.

**Comment by EzioLi01** [comment]
I have a try on this but also get error on this, I'm not sure for the root cause, but this tutorial is a little bit obsoleted. I suggest that you can create an issue on [cordova official repo](https://github.com/apache/cordova-cli) to get some help. Thanks!
