### ISSUE TITLE
Readme documentation is outdated for VS Code 1.92.2, and debugger selection does not work

### ISSUE THREAD

**Issue by Lukenickerson** [microsoft/vscode-cordova#994]
## Actual Behavior
1. When you open the Extension in VS Code, the instructions there (which match the README), are inaccurate:
   - The debug environment has a different icon and is now called "Run and Debug"
   - It's not clear what the "View bar" is.
   - You need to click Run and Debug (also if you have an existing `launch.json`, you'll need to delete or rename it)
   - VS Code needs to be restarted before "Cordova" is listed as a debugger
2. Selecting Cordova as a debugger does nothing; you need to click the link underneath it

## Expected Behavior
1. The documentation reflects the most up-ot-date VS Code, or the most common version of VS Code that users have.
2. Selecting Cordova as debugger should create a `launch.json` if there isn't one already, using the checkbox interface to select options

## Software versions
- Cordova VS Code extension version: 2.7.0
- VSCode version: 1.92.2
- OS platform and version: Windows 10
- NodeJS version: 20.5.0
- Cordova version: 12.0.0
- Cordova-Android/iOS/Windows version: 13.0.0

## Outputs (Include if relevant)

![image](https://github.com/user-attachments/assets/d4ecf79f-9e6d-4c57-bc7b-f51d9e6167b2)

After you click "Create a launch.json file" link, you get this:

![image](https://github.com/user-attachments/assets/3bad1962-c9c0-406a-8a95-0b08545109e0)

**Comment by lexie011** [comment]
Hi @Lukenickerson, Readme documentation will be updated to match the current UI interface. As for debugger selection, you'll need to pick debugger configurations after select the Cordova as debugger. Thanks for your advice.
